-- OSEE_SERVER_LOOKUP
CREATE TABLE OSEE_SERVER_LOOKUP (
	ACCEPTS_REQUESTS SMALLINT NOT NULL,
	VERSION_ID VARCHAR(100) NOT NULL,
	SERVER_ID VARCHAR(40) NOT NULL,
	START_TIME TIMESTAMP NOT NULL,
	SERVER_URI VARCHAR(255) NOT NULL,
	CONSTRAINT OSEE_SERVER_LOOKUP_PK PRIMARY KEY(SERVER_URI,VERSION_ID)
);

-- OSEE_SESSION
CREATE TABLE OSEE_SESSION (
	CLIENT_ADDRESS VARCHAR(255) NOT NULL,
	USER_ID VARCHAR(100) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	CLIENT_PORT INTEGER NOT NULL,
	CLIENT_VERSION VARCHAR(100) NOT NULL,
	SESSION_ID VARCHAR(28) NOT NULL,
	CLIENT_MACHINE_NAME VARCHAR(100) NOT NULL,
	CONSTRAINT OSEE_SESSION_PK PRIMARY KEY(SESSION_ID)
);