/*********************************************************************
 * Copyright (c) 2021 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/

import { applicabilitySentinel } from '@osee/applicability/types';
import { PlatformTypeSentinel } from '@osee/messaging/shared/enumerations';
import type {
	structure,
	structureWithChanges,
} from '@osee/messaging/shared/types';

export const structuresMock: Required<structure>[] = [
	{
		id: '1',
		gammaId: '-1',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		elements: [
			//@ts-ignore
			{
				id: '1',
				gammaId: '-1',
				name: {
					id: '-1',
					gammaId: '-1',
					typeId: '1152921504606847088',
					value: 'name2',
				},
				description: {
					id: '-1',
					gammaId: '-1',
					typeId: '1152921504606847090',
					value: 'description2',
				},
				notes: {
					id: '-1',
					gammaId: '-1',
					typeId: '1152921504606847085',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					gammaId: '-1',
					typeId: '2455059983007225802',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					gammaId: '-1',
					typeId: '2455059983007225801',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					gammaId: '-1',
					typeId: '2455059983007225788',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					gammaId: '-1',
					typeId: '1523923981411079299',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					gammaId: '-1',
					typeId: '3313203088521964923',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					gammaId: '-1',
					typeId: '3313203088521964924',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					gammaId: '-1',
					typeId: '2886273464685805413',
					value: 'name2',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					gammaId: '-1',
					typeId: '6818939106523472581',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
		],
		numElements: 1,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		incorrectlySized: false,
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
		autogenerated: false,
	},
];

export const structuresPreChanges: structure[] = [
	{
		id: '201364',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		elements: [
			//@ts-ignore
			{
				id: '201351',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
			//@ts-ignore
			{
				id: '201371',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
			//@ts-ignore
			{
				id: '201360',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
		],
		numElements: 1,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
	},
	{
		id: '201365',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		elements: [
			//@ts-ignore
			{
				id: '1',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
		],
		numElements: 1,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
	},
	{
		id: '201370',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		elements: [
			//@ts-ignore
			{
				id: '1',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
		],
		numElements: 1,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
	},
];

export const structuresMockWithChangesMulti: (
	| structure
	| structureWithChanges
)[] = [
	{
		id: '201364',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		elements: [
			//@ts-ignore
			{
				id: '1',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'hello',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: '',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: '',
				},
				deleted: true,
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},

				platformType: new PlatformTypeSentinel(),
				arrayElements: [],
				changes: {
					name: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'hello',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					description: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					notes: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					platformType: {
						//@ts-ignore
						previousValue: new PlatformTypeSentinel(),
						//@ts-ignore
						currentValue: new PlatformTypeSentinel(),
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementIndexEnd: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 1,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 1,
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementIndexStart: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225801',
							gammaId: '-1',
							value: 0,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225801',
							gammaId: '-1',
							value: 0,
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementAlterable: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: true,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: true,
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					applicability: {
						previousValue: applicabilitySentinel,
						currentValue: {
							id: '1',
							name: 'Base',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					enumLiteral: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225803',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225803',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
				},
			},
			{
				id: '201351',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
				added: true,
				changes: {
					applicability: {
						previousValue: applicabilitySentinel,
						currentValue: {
							id: '1',
							name: 'Base',
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementAlterable: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: false,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: true,
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					platformType: {
						//@ts-ignore
						previousValue: new PlatformTypeSentinel(),
						//@ts-ignore
						currentValue: {
							...new PlatformTypeSentinel(),
							name: {
								id: '-1',
								typeId: '1152921504606847088',
								gammaId: '-1',
								value: 'boolean',
							},
							id: '9',
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					name: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'name',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'name2',
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					description: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: 'description2',
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementIndexEnd: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 0,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 1,
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementIndexStart: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225801',
							gammaId: '-1',
							value: 0,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225801',
							gammaId: '-1',
							value: 0,
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					notes: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: 'notes',
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
					units: {
						previousValue: 'hertz',
						currentValue: 'feet²/second²',
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
					enumLiteral: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225803',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225803',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1222',
							branchId: '2780650236653788489',
						},
					},
				},
			},
			{
				id: '201360',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],

				changes: {
					units: {
						previousValue: 'hertz',
						currentValue: 'feet²/second²',
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
					platformType: {
						//@ts-ignore
						previousValue: new PlatformTypeSentinel(),
						//@ts-ignore
						currentValue: {
							...new PlatformTypeSentinel(),
							name: {
								id: '-1',
								typeId: '1152921504606847088',
								gammaId: '-1',
								value: 'testingUnits',
							},
							id: '9',
						},
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementIndexEnd: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 7,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 9,
						},
						transactionToken: {
							id: '1229',
							branchId: '2780650236653788489',
						},
					},
					notes: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: 'testing notes',
						},
						transactionToken: {
							id: '1265',
							branchId: '2780650236653788489',
						},
					},
				},
			},
			{
				id: '201371',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],

				changes: {
					units: {
						previousValue: 'hertz',
						currentValue: 'feet²/second²',
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
					applicability: {
						previousValue: applicabilitySentinel,
						currentValue: {
							id: '1',
							name: 'Base',
						},
						transactionToken: {
							id: '1225',
							branchId: '2780650236653788489',
						},
					},
					name: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'testaddingelement',
						},
						transactionToken: {
							id: '1225',
							branchId: '2780650236653788489',
						},
					},
					description: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: 'sdfads',
						},
						transactionToken: {
							id: '1225',
							branchId: '2780650236653788489',
						},
					},
					notes: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1225',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementAlterable: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: false,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: true,
						},
						transactionToken: {
							id: '1225',
							branchId: '2780650236653788489',
						},
					},
					platformType: {
						//@ts-ignore
						previousValue: new PlatformTypeSentinel(),
						//@ts-ignore
						currentValue: {
							...new PlatformTypeSentinel(),
							name: {
								id: '-1',
								typeId: '1152921504606847088',
								gammaId: '-1',
								value: 'Name',
							},
							id: '9',
						},
						transactionToken: {
							id: '1225',
							branchId: '2780650236653788489',
						},
					},
				},
			},
		],
		numElements: 4,
		hasElementChanges: true,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: {
			id: '2119518475782991281',
			name: 'ROBOT_SPEAKER = SPKR_B',
		},
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
		added: true,
		changes: {
			numElements: true,
			applicability: {
				previousValue: {
					id: '1',
					name: 'Base',
				},
				currentValue: {
					id: '2119518475782991281',
					name: 'ROBOT_SPEAKER = SPKR_B',
				},
				transactionToken: {
					id: '1215',
					branchId: '2780650236653788489',
				},
			},
			name: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'teststructuremodify',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'teststructuremodify2',
				},
				transactionToken: {
					id: '1219',
					branchId: '2780650236653788489',
				},
			},
			description: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'adsfas',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'changed description',
				},
				transactionToken: {
					id: '1214',
					branchId: '2780650236653788489',
				},
			},
			interfaceMaxSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '0',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '44',
				},
				transactionToken: {
					id: '1218',
					branchId: '2780650236653788489',
				},
			},
			interfaceStructureCategory: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: 'N/A',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: 'Status',
				},
				transactionToken: {
					id: '1216',
					branchId: '2780650236653788489',
				},
			},
			interfaceTaskFileType: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 0,
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 5,
				},
				transactionToken: {
					id: '1217',
					branchId: '2780650236653788489',
				},
			},
		},
	},
	{
		id: '201365',
		gammaId: '-1',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		elements: [
			{
				id: '1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],

				changes: {
					platformType: {
						//@ts-ignore
						previousValue: new PlatformTypeSentinel(),
						//@ts-ignore
						currentValue: {
							...new PlatformTypeSentinel(),
							name: {
								id: '-1',
								typeId: '1152921504606847088',
								gammaId: '-1',
								value: 'testingUnits',
							},
							id: '9',
						},
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
					units: {
						previousValue: 'hertz',
						currentValue: 'feet²/second²',
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
				},
			},
		],
		numElements: 1,
		hasElementChanges: true,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
		changes: {
			name: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'teststructuredelete',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'teststructuredelete',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			description: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'dafda',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'dafda',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceMaxSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '0',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '0',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceMinSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '6',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '6',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceStructureCategory: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: 'N/A',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: 'N/A',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceTaskFileType: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 0,
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 0,
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
		},
	},
	{
		id: '201370',
		gammaId: '-1',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		added: true,
		elements: [
			{
				id: '1',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],

				changes: {
					platformType: {
						//@ts-ignore
						previousValue: new PlatformTypeSentinel(),
						//@ts-ignore
						currentValue: {
							...new PlatformTypeSentinel(),
							name: {
								id: '-1',
								typeId: '1152921504606847088',
								gammaId: '-1',
								value: 'testingUnits',
							},
							id: '9',
						},
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
					units: {
						previousValue: 'hertz',
						currentValue: 'feet²/second²',
						transactionToken: {
							id: '1322',
							branchId: '2780650236653788489',
						},
					},
				},
			},
		],
		numElements: 1,
		sizeInBytes: 0,
		hasElementChanges: true,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
		changes: {
			applicability: {
				previousValue: applicabilitySentinel,
				currentValue: {
					id: '1',
					name: 'Base',
				},
				transactionToken: {
					id: '1220',
					branchId: '2780650236653788489',
				},
			},
			name: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: '',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'testaddingstruct',
				},
				transactionToken: {
					id: '1220',
					branchId: '2780650236653788489',
				},
			},
			description: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: '',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'dfaad',
				},
				transactionToken: {
					id: '1220',
					branchId: '2780650236653788489',
				},
			},
			interfaceMaxSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '5',
				},
				transactionToken: {
					id: '1220',
					branchId: '2780650236653788489',
				},
			},
			interfaceMinSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '98',
				},
				transactionToken: {
					id: '1220',
					branchId: '2780650236653788489',
				},
			},
			interfaceStructureCategory: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: '',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: 'N/A',
				},
				transactionToken: {
					id: '1220',
					branchId: '2780650236653788489',
				},
			},
			interfaceTaskFileType: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 0,
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 0,
				},
				transactionToken: {
					id: '1220',
					branchId: '2780650236653788489',
				},
			},
		},
	},
	{
		id: '201364',
		gammaId: '-1',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
		deleted: true,
		added: true,
		elements: [
			//@ts-ignore
			{
				id: '1',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'hello',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: '',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: '',
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				deleted: true,

				platformType: new PlatformTypeSentinel(),
				arrayElements: [],
				changes: {
					name: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'hello',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					description: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847090',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					notes: {
						previousValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '1152921504606847085',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					platformType: {
						//@ts-ignore
						previousValue: new PlatformTypeSentinel(),
						//@ts-ignore
						currentValue: new PlatformTypeSentinel(),
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementIndexEnd: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 1,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225802',
							gammaId: '-1',
							value: 1,
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementIndexStart: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225801',
							gammaId: '-1',
							value: 0,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225801',
							gammaId: '-1',
							value: 0,
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					interfaceElementAlterable: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: true,
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225788',
							gammaId: '-1',
							value: true,
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					applicability: {
						previousValue: applicabilitySentinel,
						currentValue: {
							id: '1',
							name: 'Base',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
					enumLiteral: {
						previousValue: {
							id: '-1',
							typeId: '2455059983007225803',
							gammaId: '-1',
							value: '',
						},
						currentValue: {
							id: '-1',
							typeId: '2455059983007225803',
							gammaId: '-1',
							value: '',
						},
						transactionToken: {
							id: '1223',
							branchId: '2780650236653788489',
						},
					},
				},
			},
			//@ts-ignore
			{
				id: '201351',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
			//@ts-ignore
			{
				id: '201360',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
			//@ts-ignore
			{
				id: '201371',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
		],
		numElements: 4,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		changes: {
			numElements: true,
			name: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1230',
					branchId: '2780650236653788489',
				},
			},
			description: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1230',
					branchId: '2780650236653788489',
				},
			},
			interfaceMaxSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '0',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1230',
					branchId: '2780650236653788489',
				},
			},
			interfaceMinSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '1',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1230',
					branchId: '2780650236653788489',
				},
			},
			interfaceTaskFileType: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 1,
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 0,
				},
				transactionToken: {
					id: '1230',
					branchId: '2780650236653788489',
				},
			},
			interfaceStructureCategory: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: 'Category 1',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1230',
					branchId: '2780650236653788489',
				},
			},
			applicability: {
				previousValue: {
					id: '1',
					name: 'Base',
				},
				currentValue: applicabilitySentinel,
				transactionToken: {
					id: '1230',
					branchId: '2780650236653788489',
				},
			},
		},
	},
	{
		id: '201364',
		gammaId: '-1',
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'name',
		},
		nameAbbrev: {
			id: '-1',
			typeId: '8355308043647703563',
			gammaId: '-1',
			value: '',
		},
		interfaceStructureCategory: {
			id: '-1',
			typeId: '2455059983007225764',
			gammaId: '-1',
			value: 'Category 1',
		},
		deleted: true,
		added: false,
		elements: [
			//@ts-ignore
			{
				id: '201351',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
			//@ts-ignore
			{
				id: '201371',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
			//@ts-ignore
			{
				id: '201360',
				gammaId: '-1',
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name2',
				},
				description: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description2',
				},
				notes: {
					id: '-1',
					typeId: '1152921504606847085',
					gammaId: '-1',
					value: 'notes',
				},
				interfaceElementIndexEnd: {
					id: '-1',
					typeId: '2455059983007225802',
					gammaId: '-1',
					value: 1,
				},
				interfaceElementIndexStart: {
					id: '-1',
					typeId: '2455059983007225801',
					gammaId: '-1',
					value: 0,
				},
				interfaceElementAlterable: {
					id: '-1',
					typeId: '2455059983007225788',
					gammaId: '-1',
					value: true,
				},
				interfaceElementBlockData: {
					id: '-1',
					typeId: '1523923981411079299',
					gammaId: '-1',
					value: false,
				},
				interfaceElementArrayHeader: {
					id: '-1',
					typeId: '3313203088521964923',
					gammaId: '-1',
					value: false,
				},
				interfaceElementWriteArrayHeaderName: {
					id: '-1',
					typeId: '3313203088521964924',
					gammaId: '-1',
					value: false,
				},
				interfaceDefaultValue: {
					id: '-1',
					typeId: '2886273464685805413',
					gammaId: '-1',
					value: '',
				},
				interfaceElementArrayIndexOrder: {
					id: '-1',
					typeId: '6818939106523472581',
					gammaId: '-1',
					value: 'OUTER_INNER',
				},
				interfaceElementArrayIndexDelimiterOne: {
					id: '-1',
					typeId: '6818939106523472582',
					gammaId: '-1',
					value: ' ',
				},
				interfaceElementArrayIndexDelimiterTwo: {
					id: '-1',
					typeId: '6818939106523472583',
					gammaId: '-1',
					value: ' ',
				},
				enumLiteral: {
					id: '-1',
					typeId: '2455059983007225803',
					gammaId: '-1',
					value: '',
				},
				platformType: {
					...new PlatformTypeSentinel(),
					name: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'boolean',
					},
					id: '9',
				},
				arrayElements: [],
			},
		],
		numElements: 1,
		sizeInBytes: 0,
		bytesPerSecondMaximum: 0,
		bytesPerSecondMinimum: 0,
		applicability: { id: '1', name: 'Base' },
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: 'description',
		},
		interfaceMaxSimultaneity: {
			id: '-1',
			typeId: '2455059983007225756',
			gammaId: '-1',
			value: '0',
		},
		interfaceMinSimultaneity: {
			id: '-1',
			typeId: '2455059983007225755',
			gammaId: '-1',
			value: '1',
		},
		interfaceTaskFileType: {
			id: '-1',
			typeId: '2455059983007225760',
			gammaId: '-1',
			value: 1,
		},
		changes: {
			numElements: true,
			name: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'name',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			description: {
				previousValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: 'description',
				},
				currentValue: {
					id: '-1',
					typeId: '1152921504606847090',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceMaxSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '0',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225756',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceMinSimultaneity: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '1',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225755',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceTaskFileType: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 1,
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225760',
					gammaId: '-1',
					value: 0,
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			interfaceStructureCategory: {
				previousValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: 'Category 1',
				},
				currentValue: {
					id: '-1',
					typeId: '2455059983007225764',
					gammaId: '-1',
					value: '',
				},
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
			applicability: {
				previousValue: {
					id: '1',
					name: 'Base',
				},
				currentValue: applicabilitySentinel,
				transactionToken: {
					id: '1213',
					branchId: '2780650236653788489',
				},
			},
		},
	},
];
export const structureRepeatingWithChanges: Partial<structureWithChanges> = {
	id: '201364',
	gammaId: '-1',
	name: {
		id: '-1',
		typeId: '1152921504606847088',
		gammaId: '-1',
		value: 'name',
	},
	elements: [
		//@ts-ignore
		{
			id: '1',
			gammaId: '-1',
			name: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'hello',
			},
			description: {
				id: '-1',
				typeId: '1152921504606847090',
				gammaId: '-1',
				value: '',
			},
			notes: {
				id: '-1',
				typeId: '1152921504606847085',
				gammaId: '-1',
				value: '',
			},
			interfaceElementAlterable: {
				id: '-1',
				typeId: '2455059983007225788',
				gammaId: '-1',
				value: true,
			},
			interfaceElementBlockData: {
				id: '-1',
				typeId: '1523923981411079299',
				gammaId: '-1',
				value: false,
			},
			interfaceElementArrayHeader: {
				id: '-1',
				typeId: '3313203088521964923',
				gammaId: '-1',
				value: false,
			},
			interfaceElementWriteArrayHeaderName: {
				id: '-1',
				typeId: '3313203088521964924',
				gammaId: '-1',
				value: false,
			},
			interfaceElementIndexEnd: {
				id: '-1',
				typeId: '2455059983007225802',
				gammaId: '-1',
				value: 1,
			},
			interfaceElementIndexStart: {
				id: '-1',
				typeId: '2455059983007225801',
				gammaId: '-1',
				value: 0,
			},
			interfaceDefaultValue: {
				id: '-1',
				typeId: '2886273464685805413',
				gammaId: '-1',
				value: '',
			},
			interfaceElementArrayIndexOrder: {
				id: '-1',
				typeId: '6818939106523472581',
				gammaId: '-1',
				value: 'OUTER_INNER',
			},
			interfaceElementArrayIndexDelimiterOne: {
				id: '-1',
				typeId: '6818939106523472582',
				gammaId: '-1',
				value: ' ',
			},
			interfaceElementArrayIndexDelimiterTwo: {
				id: '-1',
				typeId: '6818939106523472583',
				gammaId: '-1',
				value: ' ',
			},
			enumLiteral: {
				id: '-1',
				typeId: '2455059983007225803',
				gammaId: '-1',
				value: '',
			},
			deleted: true,

			platformType: new PlatformTypeSentinel(),
			arrayElements: [],
			changes: {
				name: {
					previousValue: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'hello',
					},
					currentValue: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: '',
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				description: {
					previousValue: {
						id: '-1',
						typeId: '1152921504606847090',
						gammaId: '-1',
						value: '',
					},
					currentValue: {
						id: '-1',
						typeId: '1152921504606847090',
						gammaId: '-1',
						value: '',
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				notes: {
					previousValue: {
						id: '-1',
						typeId: '1152921504606847085',
						gammaId: '-1',
						value: '',
					},
					currentValue: {
						id: '-1',
						typeId: '1152921504606847085',
						gammaId: '-1',
						value: '',
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				platformType: {
					//@ts-ignore
					previousValue: new PlatformTypeSentinel(),
					//@ts-ignore
					currentValue: new PlatformTypeSentinel(),
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				interfaceElementIndexEnd: {
					previousValue: {
						id: '-1',
						typeId: '2455059983007225802',
						gammaId: '-1',
						value: 1,
					},
					currentValue: {
						id: '-1',
						typeId: '2455059983007225802',
						gammaId: '-1',
						value: 1,
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				interfaceElementIndexStart: {
					previousValue: {
						id: '-1',
						typeId: '2455059983007225801',
						gammaId: '-1',
						value: 0,
					},
					currentValue: {
						id: '-1',
						typeId: '2455059983007225801',
						gammaId: '-1',
						value: 0,
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				interfaceElementAlterable: {
					previousValue: {
						id: '-1',
						typeId: '2455059983007225788',
						gammaId: '-1',
						value: true,
					},
					currentValue: {
						id: '-1',
						typeId: '2455059983007225788',
						gammaId: '-1',
						value: true,
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				applicability: {
					previousValue: applicabilitySentinel,
					currentValue: {
						id: '1',
						name: 'Base',
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
				enumLiteral: {
					previousValue: {
						id: '-1',
						typeId: '2455059983007225803',
						gammaId: '-1',
						value: '',
					},
					currentValue: {
						id: '-1',
						typeId: '2455059983007225803',
						gammaId: '-1',
						value: '',
					},
					transactionToken: {
						id: '1223',
						branchId: '2780650236653788489',
					},
				},
			},
		},
		//@ts-ignore
		{
			id: '201351',
			gammaId: '-1',
			name: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'name2',
			},
			description: {
				id: '-1',
				typeId: '1152921504606847090',
				gammaId: '-1',
				value: 'description2',
			},
			notes: {
				id: '-1',
				typeId: '1152921504606847085',
				gammaId: '-1',
				value: 'notes',
			},
			interfaceElementIndexEnd: {
				id: '-1',
				typeId: '2455059983007225802',
				gammaId: '-1',
				value: 1,
			},
			interfaceElementIndexStart: {
				id: '-1',
				typeId: '2455059983007225801',
				gammaId: '-1',
				value: 0,
			},
			interfaceElementAlterable: {
				id: '-1',
				typeId: '2455059983007225788',
				gammaId: '-1',
				value: true,
			},
			interfaceElementBlockData: {
				id: '-1',
				typeId: '1523923981411079299',
				gammaId: '-1',
				value: false,
			},
			interfaceElementArrayHeader: {
				id: '-1',
				typeId: '3313203088521964923',
				gammaId: '-1',
				value: false,
			},
			interfaceElementWriteArrayHeaderName: {
				id: '-1',
				typeId: '3313203088521964924',
				gammaId: '-1',
				value: false,
			},
			platformType: {
				...new PlatformTypeSentinel(),
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'boolean',
				},
				id: '9',
			},
			arrayElements: [],
			interfaceDefaultValue: {
				id: '-1',
				typeId: '2886273464685805413',
				gammaId: '-1',
				value: '',
			},
			interfaceElementArrayIndexOrder: {
				id: '-1',
				typeId: '6818939106523472581',
				gammaId: '-1',
				value: 'OUTER_INNER',
			},
			interfaceElementArrayIndexDelimiterOne: {
				id: '-1',
				typeId: '6818939106523472582',
				gammaId: '-1',
				value: ' ',
			},
			interfaceElementArrayIndexDelimiterTwo: {
				id: '-1',
				typeId: '6818939106523472583',
				gammaId: '-1',
				value: ' ',
			},
			enumLiteral: {
				id: '-1',
				typeId: '2455059983007225803',
				gammaId: '-1',
				value: '',
			},

			added: true,
			changes: {
				applicability: {
					previousValue: {
						id: '1',
						name: 'Base',
					},
					currentValue: {
						id: '1',
						name: 'Base',
					},
					transactionToken: {
						id: '1222',
						branchId: '2780650236653788489',
					},
				},
				interfaceElementAlterable: {
					previousValue: {
						id: '-1',
						typeId: '2455059983007225788',
						gammaId: '-1',
						value: true,
					},
					currentValue: {
						id: '-1',
						typeId: '2455059983007225788',
						gammaId: '-1',
						value: false,
					},
					transactionToken: {
						id: '1227',
						branchId: '2780650236653788489',
					},
				},
				platformType: {
					previousValue: {
						...new PlatformTypeSentinel(),
						name: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'Name',
						},
						id: '0', //? don't know why this is getting this value
						interfaceLogicalType: {
							id: '-1',
							typeId: '2455059983007225762',
							gammaId: '-1',
							value: '',
						},
						interfacePlatformType2sComplement: {
							id: '-1',
							typeId: '3899709087455064784',
							gammaId: '-1',
							value: false,
						},
						interfacePlatformTypeAnalogAccuracy: {
							id: '-1',
							typeId: '3899709087455064788',
							gammaId: '-1',
							value: '',
						},
						interfacePlatformTypeCompRate: {
							id: '-1',
							typeId: '3899709087455064787',
							gammaId: '-1',
							value: '',
						},
						interfaceDefaultValue: {
							id: '-1',
							typeId: '2886273464685805413',
							gammaId: '-1',
							value: '',
						},
						interfacePlatformTypeUnits: {
							id: '-1',
							typeId: '4026643196432874344',
							gammaId: '-1',
							value: '',
						},
						interfacePlatformTypeValidRangeDescription: {
							id: '-1',
							typeId: '2121416901992068417',
							gammaId: '-1',
							value: '',
						},
						applicability: {
							id: '1',
							name: 'Base',
						},
						interfacePlatformTypeBitSize: {
							id: '-1',
							typeId: '2455059983007225786',
							gammaId: '-1',
							value: '8',
						},
						interfacePlatformTypeBitsResolution: {
							id: '-1',
							typeId: '3899709087455064786',
							gammaId: '-1',
							value: '8',
						},
						interfacePlatformTypeMaxval: {
							id: '-1',
							typeId: '3899709087455064783',
							gammaId: '-1',
							value: '1',
						},
						interfacePlatformTypeMinval: {
							id: '-1',
							typeId: '3899709087455064782',
							gammaId: '-1',
							value: '1',
						},
						interfacePlatformTypeMsbValue: {
							id: '-1',
							typeId: '3899709087455064785',
							gammaId: '-1',
							value: '0',
						},
					},
					currentValue: {
						...new PlatformTypeSentinel(),
						name: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'Name',
						},
						id: '9',
					},
					transactionToken: {
						id: '1226',
						branchId: '2780650236653788489',
					},
				},
			},
		},
		//@ts-ignore
		{
			id: '201360',
			gammaId: '-1',
			name: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'name2',
			},
			description: {
				id: '-1',
				typeId: '1152921504606847090',
				gammaId: '-1',
				value: 'description2',
			},
			notes: {
				id: '-1',
				typeId: '1152921504606847085',
				gammaId: '-1',
				value: 'notes',
			},
			interfaceElementIndexEnd: {
				id: '-1',
				typeId: '2455059983007225802',
				gammaId: '-1',
				value: 1,
			},
			interfaceElementIndexStart: {
				id: '-1',
				typeId: '2455059983007225801',
				gammaId: '-1',
				value: 0,
			},
			interfaceElementAlterable: {
				id: '-1',
				typeId: '2455059983007225788',
				gammaId: '-1',
				value: true,
			},
			interfaceElementBlockData: {
				id: '-1',
				typeId: '1523923981411079299',
				gammaId: '-1',
				value: false,
			},
			interfaceElementArrayHeader: {
				id: '-1',
				typeId: '3313203088521964923',
				gammaId: '-1',
				value: false,
			},
			interfaceElementWriteArrayHeaderName: {
				id: '-1',
				typeId: '3313203088521964924',
				gammaId: '-1',
				value: false,
			},
			platformType: {
				...new PlatformTypeSentinel(),
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'boolean',
				},
				id: '9',
			},
			arrayElements: [],
			interfaceDefaultValue: {
				id: '-1',
				typeId: '2886273464685805413',
				gammaId: '-1',
				value: '',
			},
			interfaceElementArrayIndexOrder: {
				id: '-1',
				typeId: '6818939106523472581',
				gammaId: '-1',
				value: 'OUTER_INNER',
			},
			interfaceElementArrayIndexDelimiterOne: {
				id: '-1',
				typeId: '6818939106523472582',
				gammaId: '-1',
				value: ' ',
			},
			interfaceElementArrayIndexDelimiterTwo: {
				id: '-1',
				typeId: '6818939106523472583',
				gammaId: '-1',
				value: ' ',
			},
			enumLiteral: {
				id: '-1',
				typeId: '2455059983007225803',
				gammaId: '-1',
				value: '',
			},

			changes: {
				interfaceElementIndexEnd: {
					previousValue: {
						id: '-1',
						typeId: '2455059983007225802',
						gammaId: '-1',
						value: 7,
					},
					currentValue: {
						id: '-1',
						typeId: '2455059983007225802',
						gammaId: '-1',
						value: 9,
					},
					transactionToken: {
						id: '1229',
						branchId: '2780650236653788489',
					},
				},
			},
		},
		//@ts-ignore
		{
			id: '201371',
			gammaId: '-1',
			name: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'name2',
			},
			description: {
				id: '-1',
				typeId: '1152921504606847090',
				gammaId: '-1',
				value: 'description2',
			},
			notes: {
				id: '-1',
				typeId: '1152921504606847085',
				gammaId: '-1',
				value: 'notes',
			},
			interfaceElementIndexEnd: {
				id: '-1',
				typeId: '2455059983007225802',
				gammaId: '-1',
				value: 1,
			},
			interfaceElementIndexStart: {
				id: '-1',
				typeId: '2455059983007225801',
				gammaId: '-1',
				value: 0,
			},
			interfaceElementAlterable: {
				id: '-1',
				typeId: '2455059983007225788',
				gammaId: '-1',
				value: true,
			},
			interfaceElementBlockData: {
				id: '-1',
				typeId: '1523923981411079299',
				gammaId: '-1',
				value: false,
			},
			interfaceElementArrayHeader: {
				id: '-1',
				typeId: '3313203088521964923',
				gammaId: '-1',
				value: false,
			},
			interfaceElementWriteArrayHeaderName: {
				id: '-1',
				typeId: '3313203088521964924',
				gammaId: '-1',
				value: false,
			},
			platformType: {
				...new PlatformTypeSentinel(),
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'boolean',
				},
				id: '9',
			},
			arrayElements: [],
			interfaceDefaultValue: {
				id: '-1',
				typeId: '2886273464685805413',
				gammaId: '-1',
				value: '',
			},
			interfaceElementArrayIndexOrder: {
				id: '-1',
				typeId: '6818939106523472581',
				gammaId: '-1',
				value: 'OUTER_INNER',
			},
			interfaceElementArrayIndexDelimiterOne: {
				id: '-1',
				typeId: '6818939106523472582',
				gammaId: '-1',
				value: ' ',
			},
			interfaceElementArrayIndexDelimiterTwo: {
				id: '-1',
				typeId: '6818939106523472583',
				gammaId: '-1',
				value: ' ',
			},
			enumLiteral: {
				id: '-1',
				typeId: '2455059983007225803',
				gammaId: '-1',
				value: '',
			},

			changes: {
				applicability: {
					previousValue: {
						id: '1',
						name: 'Base',
					},
					currentValue: {
						id: '1',
						name: 'Base',
					},
					transactionToken: {
						id: '1225',
						branchId: '2780650236653788489',
					},
				},
				name: {
					previousValue: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: '',
					},
					currentValue: {
						id: '-1',
						typeId: '1152921504606847088',
						gammaId: '-1',
						value: 'testaddingelement',
					},
					transactionToken: {
						id: '1225',
						branchId: '2780650236653788489',
					},
				},
				description: {
					previousValue: {
						id: '-1',
						typeId: '1152921504606847090',
						gammaId: '-1',
						value: '',
					},
					currentValue: {
						id: '-1',
						typeId: '1152921504606847090',
						gammaId: '-1',
						value: 'dsfads',
					},
					transactionToken: {
						id: '1225',
						branchId: '2780650236653788489',
					},
				},
				interfaceElementAlterable: {
					previousValue: {
						id: '-1',
						typeId: '2455059983007225788',
						gammaId: '-1',
						value: false,
					},
					currentValue: {
						id: '-1',
						typeId: '2455059983007225788',
						gammaId: '-1',
						value: true,
					},
					transactionToken: {
						id: '1225',
						branchId: '2780650236653788489',
					},
				},
				platformType: {
					previousValue: new PlatformTypeSentinel(),
					currentValue: {
						...new PlatformTypeSentinel(),
						name: {
							id: '-1',
							typeId: '1152921504606847088',
							gammaId: '-1',
							value: 'Name',
						},
						id: '9',
					},
					transactionToken: {
						id: '1225',
						branchId: '2780650236653788489',
					},
				},
			},
		},
	],
	numElements: 2,
	hasElementChanges: true,
	sizeInBytes: 0,
	bytesPerSecondMaximum: 0,
	bytesPerSecondMinimum: 0,
	applicability: {
		id: '2119518475782991281',
		name: 'ROBOT_SPEAKER = SPKR_B',
	},
	description: {
		id: '-1',
		typeId: '1152921504606847090',
		gammaId: '-1',
		value: 'description',
	},
	interfaceMaxSimultaneity: {
		id: '-1',
		typeId: '2455059983007225756',
		gammaId: '-1',
		value: '0',
	},
	interfaceMinSimultaneity: {
		id: '-1',
		typeId: '2455059983007225755',
		gammaId: '-1',
		value: '1',
	},
	interfaceTaskFileType: {
		id: '-1',
		typeId: '2455059983007225760',
		gammaId: '-1',
		value: 1,
	},
	interfaceStructureCategory: {
		id: '-1',
		typeId: '2455059983007225764',
		gammaId: '-1',
		value: 'Category 1',
	},
	added: true,
	changes: {
		numElements: true,
		applicability: {
			previousValue: {
				id: '1',
				name: 'Base',
			},
			currentValue: {
				id: '2119518475782991281',
				name: 'ROBOT_SPEAKER = SPKR_B',
			},
			transactionToken: { id: '1215', branchId: '2780650236653788489' },
		},
		name: {
			previousValue: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'teststructuremodify',
			},
			currentValue: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'teststructuremodify2',
			},
			transactionToken: { id: '1219', branchId: '2780650236653788489' },
		},
		description: {
			previousValue: {
				id: '-1',
				typeId: '1152921504606847090',
				gammaId: '-1',
				value: 'adsfas',
			},
			currentValue: {
				id: '-1',
				typeId: '1152921504606847090',
				gammaId: '-1',
				value: 'changed description',
			},
			transactionToken: { id: '1214', branchId: '2780650236653788489' },
		},
		interfaceMaxSimultaneity: {
			previousValue: {
				id: '-1',
				typeId: '2455059983007225756',
				gammaId: '-1',
				value: '0',
			},
			currentValue: {
				id: '-1',
				typeId: '2455059983007225756',
				gammaId: '-1',
				value: '44',
			},
			transactionToken: { id: '1218', branchId: '2780650236653788489' },
		},
		interfaceStructureCategory: {
			previousValue: {
				id: '-1',
				typeId: '2455059983007225764',
				gammaId: '-1',
				value: 'N/A',
			},
			currentValue: {
				id: '-1',
				typeId: '2455059983007225764',
				gammaId: '-1',
				value: 'Status',
			},
			transactionToken: { id: '1216', branchId: '2780650236653788489' },
		},
		interfaceTaskFileType: {
			previousValue: {
				id: '-1',
				typeId: '2455059983007225760',
				gammaId: '-1',
				value: 0,
			},
			currentValue: {
				id: '-1',
				typeId: '2455059983007225760',
				gammaId: '-1',
				value: 5,
			},
			transactionToken: { id: '1217', branchId: '2780650236653788489' },
		},
	},
};
export const structuresMockWithChanges: structureWithChanges = {
	id: '1',
	gammaId: '-1',
	name: {
		id: '-1',
		typeId: '1152921504606847088',
		gammaId: '-1',
		value: 'name',
	},
	nameAbbrev: {
		id: '-1',
		typeId: '8355308043647703563',
		gammaId: '-1',
		value: '',
	},
	elements: [
		//@ts-ignore
		{
			id: '1',
			gammaId: '-1',
			name: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'name2',
			},
			description: {
				id: '-1',
				typeId: '1152921504606847090',
				gammaId: '-1',
				value: 'description2',
			},
			notes: {
				id: '-1',
				typeId: '1152921504606847085',
				gammaId: '-1',
				value: 'notes',
			},
			interfaceElementIndexEnd: {
				id: '-1',
				typeId: '2455059983007225802',
				gammaId: '-1',
				value: 1,
			},
			interfaceElementIndexStart: {
				id: '-1',
				typeId: '2455059983007225801',
				gammaId: '-1',
				value: 0,
			},
			interfaceElementAlterable: {
				id: '-1',
				typeId: '2455059983007225788',
				gammaId: '-1',
				value: true,
			},
			interfaceElementBlockData: {
				id: '-1',
				typeId: '1523923981411079299',
				gammaId: '-1',
				value: false,
			},
			interfaceElementArrayHeader: {
				id: '-1',
				typeId: '3313203088521964923',
				gammaId: '-1',
				value: false,
			},
			interfaceElementWriteArrayHeaderName: {
				id: '-1',
				typeId: '3313203088521964924',
				gammaId: '-1',
				value: false,
			},
			platformType: {
				...new PlatformTypeSentinel(),
				name: {
					id: '-1',
					typeId: '1152921504606847088',
					gammaId: '-1',
					value: 'boolean',
				},
				id: '9',
			},
			arrayElements: [],
			interfaceDefaultValue: {
				id: '-1',
				typeId: '2886273464685805413',
				gammaId: '-1',
				value: '',
			},
			interfaceElementArrayIndexOrder: {
				id: '-1',
				typeId: '6818939106523472581',
				gammaId: '-1',
				value: 'OUTER_INNER',
			},
			interfaceElementArrayIndexDelimiterOne: {
				id: '-1',
				typeId: '6818939106523472582',
				gammaId: '-1',
				value: ' ',
			},
			interfaceElementArrayIndexDelimiterTwo: {
				id: '-1',
				typeId: '6818939106523472583',
				gammaId: '-1',
				value: ' ',
			},
			enumLiteral: {
				id: '-1',
				typeId: '2455059983007225803',
				gammaId: '-1',
				value: '',
			},
		},
	],
	numElements: 1,
	sizeInBytes: 0,
	bytesPerSecondMaximum: 0,
	bytesPerSecondMinimum: 0,
	applicability: { id: '1', name: 'Base' },
	description: {
		id: '-1',
		typeId: '1152921504606847090',
		gammaId: '-1',
		value: 'description',
	},
	interfaceMaxSimultaneity: {
		id: '-1',
		typeId: '2455059983007225756',
		gammaId: '-1',
		value: '0',
	},
	interfaceMinSimultaneity: {
		id: '-1',
		typeId: '2455059983007225755',
		gammaId: '-1',
		value: '1',
	},
	interfaceTaskFileType: {
		id: '-1',
		typeId: '2455059983007225760',
		gammaId: '-1',
		value: 1,
	},
	interfaceStructureCategory: {
		id: '-1',
		typeId: '2455059983007225764',
		gammaId: '-1',
		value: 'Category 1',
	},
	added: false,
	deleted: false,
	hasElementChanges: false,
	autogenerated: false,
	changes: {
		name: {
			previousValue: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'a',
			},
			currentValue: {
				id: '-1',
				typeId: '1152921504606847088',
				gammaId: '-1',
				value: 'b',
			},
			transactionToken: { id: '1234', branchId: '8' },
		},
	},
	incorrectlySized: false,
};
