/*********************************************************************
 * Copyright (c) 2021 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/
import type { subMessage, subMessageWithChanges } from '../types/sub-messages';

export const subMessagesMock: Required<subMessage | subMessageWithChanges>[] = [
	{
		name: {
			id: '-1',
			typeId: '1152921504606847088',
			gammaId: '-1',
			value: 'submessage0',
		},
		description: {
			id: '-1',
			typeId: '1152921504606847090',
			gammaId: '-1',
			value: '',
		},
		interfaceSubMessageNumber: {
			id: '-1',
			typeId: '2455059983007225769',
			gammaId: '-1',
			value: '0',
		},
		id: '1',
		gammaId: '1',
		autogenerated: false,
		applicability: {
			id: '1',
			name: 'Base',
		},
		changes: {
			name: {
				previousValue: '',
				currentValue: 'submessage0',
				transactionToken: {
					id: '-1',
					branchId: '-1',
				},
			},
		},
	},
];
