/*
* generated by Xtext
*/
package org.eclipse.osee.orcs.script.dsl.ui.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.osee.orcs.script.dsl.services.OrcsScriptDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class OrcsScriptDslParser extends AbstractContentAssistParser {

   @Inject
   private OrcsScriptDslGrammarAccess grammarAccess;

   private Map<AbstractElement, String> nameMappings;

   @Override
   protected org.eclipse.osee.orcs.script.dsl.ui.contentassist.antlr.internal.InternalOrcsScriptDslParser createParser() {
      org.eclipse.osee.orcs.script.dsl.ui.contentassist.antlr.internal.InternalOrcsScriptDslParser result =
         new org.eclipse.osee.orcs.script.dsl.ui.contentassist.antlr.internal.InternalOrcsScriptDslParser(null);
      result.setGrammarAccess(grammarAccess);
      return result;
   }

   @Override
   protected String getRuleName(AbstractElement element) {
      if (nameMappings == null) {
         nameMappings = new HashMap<AbstractElement, String>() {
            private static final long serialVersionUID = 1L;

            {
               put(grammarAccess.getScriptStatementAccess().getAlternatives(), "rule__ScriptStatement__Alternatives");
               put(grammarAccess.getOsAssignmentValueAccess().getAlternatives(),
                  "rule__OsAssignmentValue__Alternatives");
               put(grammarAccess.getOsLiteralAccess().getAlternatives(), "rule__OsLiteral__Alternatives");
               put(grammarAccess.getOsBooleanLiteralAccess().getAlternatives_1(),
                  "rule__OsBooleanLiteral__Alternatives_1");
               put(grammarAccess.getOsQueryAccess().getAlternatives(), "rule__OsQuery__Alternatives");
               put(grammarAccess.getOsCritieriaAccess().getAlternatives(), "rule__OsCritieria__Alternatives");
               put(grammarAccess.getOsClauseAccess().getAlternatives(), "rule__OsClause__Alternatives");
               put(grammarAccess.getOsMetaTypeIdAccess().getAlternatives(), "rule__OsMetaTypeId__Alternatives");
               put(grammarAccess.getOsTxIdAccess().getAlternatives(), "rule__OsTxId__Alternatives");
               put(grammarAccess.getOsBranchIdAccess().getAlternatives(), "rule__OsBranchId__Alternatives");
               put(grammarAccess.getOsBranchIdOrNameAccess().getAlternatives(), "rule__OsBranchIdOrName__Alternatives");
               put(grammarAccess.getOsArtifactIdAccess().getAlternatives(), "rule__OsArtifactId__Alternatives");
               put(grammarAccess.getOsArtifactGuidAccess().getAlternatives(), "rule__OsArtifactGuid__Alternatives");
               put(grammarAccess.getOsTxTimestampAccess().getAlternatives(), "rule__OsTxTimestamp__Alternatives");
               put(grammarAccess.getOsBranchNameAccess().getAlternatives(), "rule__OsBranchName__Alternatives");
               put(grammarAccess.getOsBranchPatternAccess().getAlternatives(), "rule__OsBranchPattern__Alternatives");
               put(grammarAccess.getOsTxCommentAccess().getAlternatives(), "rule__OsTxComment__Alternatives");
               put(grammarAccess.getOsTxCommentPatternAccess().getAlternatives(),
                  "rule__OsTxCommentPattern__Alternatives");
               put(grammarAccess.getOsAliasAccess().getAlternatives(), "rule__OsAlias__Alternatives");
               put(grammarAccess.getOsLimitAccess().getAlternatives(), "rule__OsLimit__Alternatives");
               put(grammarAccess.getOsAttributeValueAccess().getAlternatives(), "rule__OsAttributeValue__Alternatives");
               put(grammarAccess.getOsFieldIdAccess().getAlternatives(), "rule__OsFieldId__Alternatives");
               put(grammarAccess.getOsFieldMatchingKeywordsAccess().getAlternatives(),
                  "rule__OsFieldMatchingKeywords__Alternatives");
               put(grammarAccess.getOsCollectTypeIdAccess().getAlternatives(), "rule__OsCollectTypeId__Alternatives");
               put(grammarAccess.getOsCollectExpressionAccess().getAlternatives(),
                  "rule__OsCollectExpression__Alternatives");
               put(grammarAccess.getOsCollectItemExpressionAccess().getAlternatives(),
                  "rule__OsCollectItemExpression__Alternatives");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getAlternatives_4(),
                  "rule__OsCollectObjectExpression__Alternatives_4");
               put(grammarAccess.getOsBranchQueryAccess().getAlternatives(), "rule__OsBranchQuery__Alternatives");
               put(grammarAccess.getOsBranchCriteriaAccess().getAlternatives(), "rule__OsBranchCriteria__Alternatives");
               put(grammarAccess.getOsBranchNameClauseAccess().getAlternatives(),
                  "rule__OsBranchNameClause__Alternatives");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getAlternatives_2(),
                  "rule__OsBranchTypeCriteria__Alternatives_2");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getAlternatives_2(),
                  "rule__OsBranchStateCriteria__Alternatives_2");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getAlternatives_2(),
                  "rule__OsBranchIdCriteria__Alternatives_2");
               put(grammarAccess.getOsBranchClauseAccess().getAlternatives(), "rule__OsBranchClause__Alternatives");
               put(grammarAccess.getOsTxQueryAccess().getAlternatives(), "rule__OsTxQuery__Alternatives");
               put(grammarAccess.getOsTxCriteriaAccess().getAlternatives(), "rule__OsTxCriteria__Alternatives");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getAlternatives_2(),
                  "rule__OsTxTypeCriteria__Alternatives_2");
               put(grammarAccess.getOsTxCommentClauseAccess().getAlternatives(),
                  "rule__OsTxCommentClause__Alternatives");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getAlternatives_2(),
                  "rule__OsTxBranchIdCriteria__Alternatives_2");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getAlternatives_2(),
                  "rule__OsTxAuthorIdCriteria__Alternatives_2");
               put(grammarAccess.getOsTxCommitIdClauseAccess().getAlternatives(),
                  "rule__OsTxCommitIdClause__Alternatives");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getAlternatives_1(),
                  "rule__OsTxCommitIdEqualsClause__Alternatives_1");
               put(grammarAccess.getOsTxIdClauseAccess().getAlternatives(), "rule__OsTxIdClause__Alternatives");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getAlternatives_1(),
                  "rule__OsTxIdEqualsClause__Alternatives_1");
               put(grammarAccess.getOsTxTimestampClauseAccess().getAlternatives(),
                  "rule__OsTxTimestampClause__Alternatives");
               put(grammarAccess.getOsArtifactQueryAccess().getAlternatives(), "rule__OsArtifactQuery__Alternatives");
               put(grammarAccess.getOsItemCriteriaAccess().getAlternatives(), "rule__OsItemCriteria__Alternatives");
               put(grammarAccess.getOsArtifactCriteriaAccess().getAlternatives(),
                  "rule__OsArtifactCriteria__Alternatives");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getAlternatives_2(),
                  "rule__OsArtifactIdCriteria__Alternatives_2");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getAlternatives_2(),
                  "rule__OsArtifactGuidCriteria__Alternatives_2");
               put(grammarAccess.getOsArtifactTypeClauseAccess().getAlternatives(),
                  "rule__OsArtifactTypeClause__Alternatives");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getAlternatives_1(),
                  "rule__OsArtifactTypeEqualsClause__Alternatives_1");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getAlternatives_1(),
                  "rule__OsArtifactTypeInstanceOfClause__Alternatives_1");
               put(grammarAccess.getOsAttributeClauseAccess().getAlternatives(),
                  "rule__OsAttributeClause__Alternatives");
               put(grammarAccess.getOsAttributeExistClauseAccess().getAlternatives_2(),
                  "rule__OsAttributeExistClause__Alternatives_2");
               put(grammarAccess.getOseAttributeOpClauseAccess().getAlternatives_2(),
                  "rule__OseAttributeOpClause__Alternatives_2");
               put(grammarAccess.getOseAttributeOpClauseAccess().getAlternatives_3(),
                  "rule__OseAttributeOpClause__Alternatives_3");
               put(grammarAccess.getOseAttributeOpClauseAccess().getAlternatives_4(),
                  "rule__OseAttributeOpClause__Alternatives_4");
               put(grammarAccess.getOsRelationClauseAccess().getAlternatives(), "rule__OsRelationClause__Alternatives");
               put(grammarAccess.getOsRelatedToClauseAccess().getAlternatives_7(),
                  "rule__OsRelatedToClause__Alternatives_7");
               put(grammarAccess.getNumberAccess().getAlternatives(), "rule__Number__Alternatives");
               put(grammarAccess.getOsBranchStateAccess().getAlternatives(), "rule__OsBranchState__Alternatives");
               put(grammarAccess.getOsBranchTypeAccess().getAlternatives(), "rule__OsBranchType__Alternatives");
               put(grammarAccess.getOsBranchArchiveFilterAccess().getAlternatives(),
                  "rule__OsBranchArchiveFilter__Alternatives");
               put(grammarAccess.getOsTxTypeAccess().getAlternatives(), "rule__OsTxType__Alternatives");
               put(grammarAccess.getOsRelationSideAccess().getAlternatives(), "rule__OsRelationSide__Alternatives");
               put(grammarAccess.getOsOperatorAccess().getAlternatives(), "rule__OsOperator__Alternatives");
               put(grammarAccess.getOsNonEqualOperatorAccess().getAlternatives(),
                  "rule__OsNonEqualOperator__Alternatives");
               put(grammarAccess.getOsExistenceOperatorAccess().getAlternatives(),
                  "rule__OsExistenceOperator__Alternatives");
               put(grammarAccess.getOsQueryOptionAccess().getAlternatives(), "rule__OsQueryOption__Alternatives");
               put(grammarAccess.getOrcsScriptAccess().getGroup(), "rule__OrcsScript__Group__0");
               put(grammarAccess.getScriptVersionAccess().getGroup(), "rule__ScriptVersion__Group__0");
               put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
               put(grammarAccess.getOsVariableDeclarationAccess().getGroup(), "rule__OsVariableDeclaration__Group__0");
               put(grammarAccess.getOsVariableDeclarationAccess().getGroup_3(),
                  "rule__OsVariableDeclaration__Group_3__0");
               put(grammarAccess.getOsVariableAccess().getGroup(), "rule__OsVariable__Group__0");
               put(grammarAccess.getOsVariableAccess().getGroup_2(), "rule__OsVariable__Group_2__0");
               put(grammarAccess.getOsTemplateIdAccess().getGroup(), "rule__OsTemplateId__Group__0");
               put(grammarAccess.getOsTemplateIdAccess().getGroup_1(), "rule__OsTemplateId__Group_1__0");
               put(grammarAccess.getOsAssignmentAccess().getGroup(), "rule__OsAssignment__Group__0");
               put(grammarAccess.getOsBooleanLiteralAccess().getGroup(), "rule__OsBooleanLiteral__Group__0");
               put(grammarAccess.getOsNullLiteralAccess().getGroup(), "rule__OsNullLiteral__Group__0");
               put(grammarAccess.getOsNumberLiteralAccess().getGroup(), "rule__OsNumberLiteral__Group__0");
               put(grammarAccess.getOsStringLiteralAccess().getGroup(), "rule__OsStringLiteral__Group__0");
               put(grammarAccess.getOsTemplateLiteralAccess().getGroup(), "rule__OsTemplateLiteral__Group__0");
               put(grammarAccess.getOsListLiteralAccess().getGroup(), "rule__OsListLiteral__Group__0");
               put(grammarAccess.getOsListLiteralAccess().getGroup_2(), "rule__OsListLiteral__Group_2__0");
               put(grammarAccess.getOsListLiteralAccess().getGroup_2_1(), "rule__OsListLiteral__Group_2_1__0");
               put(grammarAccess.getOsVariableReferenceAccess().getGroup(), "rule__OsVariableReference__Group__0");
               put(grammarAccess.getOsDotExpressionAccess().getGroup(), "rule__OsDotExpression__Group__0");
               put(grammarAccess.getOsDotExpressionAccess().getGroup_1(), "rule__OsDotExpression__Group_1__0");
               put(grammarAccess.getOsQueryExpressionAccess().getGroup(), "rule__OsQueryExpression__Group__0");
               put(grammarAccess.getOsQueryStatementAccess().getGroup(), "rule__OsQueryStatement__Group__0");
               put(grammarAccess.getOsCollectClauseAccess().getGroup(), "rule__OsCollectClause__Group__0");
               put(grammarAccess.getOsLimitClauseAccess().getGroup(), "rule__OsLimitClause__Group__0");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getGroup(),
                  "rule__OsCollectObjectExpression__Group__0");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getGroup_2(),
                  "rule__OsCollectObjectExpression__Group_2__0");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getGroup_4_1(),
                  "rule__OsCollectObjectExpression__Group_4_1__0");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getGroup_4_1_1(),
                  "rule__OsCollectObjectExpression__Group_4_1_1__0");
               put(grammarAccess.getOsCollectAllFieldsExpressionAccess().getGroup(),
                  "rule__OsCollectAllFieldsExpression__Group__0");
               put(grammarAccess.getOsCollectFieldExpressionAccess().getGroup(),
                  "rule__OsCollectFieldExpression__Group__0");
               put(grammarAccess.getOsCollectFieldExpressionAccess().getGroup_2(),
                  "rule__OsCollectFieldExpression__Group_2__0");
               put(grammarAccess.getOsFindClauseAccess().getGroup(), "rule__OsFindClause__Group__0");
               put(grammarAccess.getOsBranchQueryStatementAccess().getGroup(),
                  "rule__OsBranchQueryStatement__Group__0");
               put(grammarAccess.getOsBranchQueryByPredicateAccess().getGroup(),
                  "rule__OsBranchQueryByPredicate__Group__0");
               put(grammarAccess.getOsBranchQueryByPredicateAccess().getGroup_2(),
                  "rule__OsBranchQueryByPredicate__Group_2__0");
               put(grammarAccess.getOsBranchNameCriteriaAccess().getGroup(), "rule__OsBranchNameCriteria__Group__0");
               put(grammarAccess.getOsBranchNameEqualsClauseAccess().getGroup(),
                  "rule__OsBranchNameEqualsClause__Group__0");
               put(grammarAccess.getOsBranchNamePatternClauseAccess().getGroup(),
                  "rule__OsBranchNamePatternClause__Group__0");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getGroup(), "rule__OsBranchTypeCriteria__Group__0");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getGroup_2_1(),
                  "rule__OsBranchTypeCriteria__Group_2_1__0");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsBranchTypeCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getGroup(), "rule__OsBranchStateCriteria__Group__0");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getGroup_2_1(),
                  "rule__OsBranchStateCriteria__Group_2_1__0");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsBranchStateCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsBranchArchivedCriteriaAccess().getGroup(),
                  "rule__OsBranchArchivedCriteria__Group__0");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getGroup(), "rule__OsBranchIdCriteria__Group__0");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getGroup_2_1(),
                  "rule__OsBranchIdCriteria__Group_2_1__0");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsBranchIdCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsBranchOfCriteriaAccess().getGroup(), "rule__OsBranchOfCriteria__Group__0");
               put(grammarAccess.getOsBranchChildOfClauseAccess().getGroup(), "rule__OsBranchChildOfClause__Group__0");
               put(grammarAccess.getOsBranchParentOfClauseAccess().getGroup(),
                  "rule__OsBranchParentOfClause__Group__0");
               put(grammarAccess.getOsTxQueryStatementAccess().getGroup(), "rule__OsTxQueryStatement__Group__0");
               put(grammarAccess.getOsTxQueryByPredicateAccess().getGroup(), "rule__OsTxQueryByPredicate__Group__0");
               put(grammarAccess.getOsTxQueryByPredicateAccess().getGroup_2(),
                  "rule__OsTxQueryByPredicate__Group_2__0");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getGroup(), "rule__OsTxTypeCriteria__Group__0");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getGroup_2_1(), "rule__OsTxTypeCriteria__Group_2_1__0");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsTxTypeCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsTxCommentCriteriaAccess().getGroup(), "rule__OsTxCommentCriteria__Group__0");
               put(grammarAccess.getOsTxCommentEqualsClauseAccess().getGroup(),
                  "rule__OsTxCommentEqualsClause__Group__0");
               put(grammarAccess.getOsTxCommentPatternClauseAccess().getGroup(),
                  "rule__OsTxCommentPatternClause__Group__0");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getGroup(), "rule__OsTxBranchIdCriteria__Group__0");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getGroup_2_1(),
                  "rule__OsTxBranchIdCriteria__Group_2_1__0");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsTxBranchIdCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsTxHeadOfBranchIdCriteriaAccess().getGroup(),
                  "rule__OsTxHeadOfBranchIdCriteria__Group__0");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getGroup(), "rule__OsTxAuthorIdCriteria__Group__0");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getGroup_2_1(),
                  "rule__OsTxAuthorIdCriteria__Group_2_1__0");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsTxAuthorIdCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsTxCommitIdCriteriaAccess().getGroup(), "rule__OsTxCommitIdCriteria__Group__0");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getGroup(),
                  "rule__OsTxCommitIdEqualsClause__Group__0");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getGroup_1_1(),
                  "rule__OsTxCommitIdEqualsClause__Group_1_1__0");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getGroup_1_1_2(),
                  "rule__OsTxCommitIdEqualsClause__Group_1_1_2__0");
               put(grammarAccess.getOsTxCommitIdIsNullClauseAccess().getGroup(),
                  "rule__OsTxCommitIdIsNullClause__Group__0");
               put(grammarAccess.getOsTxIdCriteriaAccess().getGroup(), "rule__OsTxIdCriteria__Group__0");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getGroup(), "rule__OsTxIdEqualsClause__Group__0");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getGroup_1_1(),
                  "rule__OsTxIdEqualsClause__Group_1_1__0");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getGroup_1_1_2(),
                  "rule__OsTxIdEqualsClause__Group_1_1_2__0");
               put(grammarAccess.getOsTxIdOpClauseAccess().getGroup(), "rule__OsTxIdOpClause__Group__0");
               put(grammarAccess.getOsTxIdRangeClauseAccess().getGroup(), "rule__OsTxIdRangeClause__Group__0");
               put(grammarAccess.getOsTxTimestampCriteriaAccess().getGroup(), "rule__OsTxTimestampCriteria__Group__0");
               put(grammarAccess.getOsTxTimestampOpClauseAccess().getGroup(), "rule__OsTxTimestampOpClause__Group__0");
               put(grammarAccess.getOsTxTimestampRangeClauseAccess().getGroup(),
                  "rule__OsTxTimestampRangeClause__Group__0");
               put(grammarAccess.getOsArtifactQueryStatementAccess().getGroup(),
                  "rule__OsArtifactQueryStatement__Group__0");
               put(grammarAccess.getOsArtifactQueryByPredicateAccess().getGroup(),
                  "rule__OsArtifactQueryByPredicate__Group__0");
               put(grammarAccess.getOsArtifactQueryByPredicateAccess().getGroup_2(),
                  "rule__OsArtifactQueryByPredicate__Group_2__0");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getGroup(), "rule__OsArtifactIdCriteria__Group__0");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getGroup_2_1(),
                  "rule__OsArtifactIdCriteria__Group_2_1__0");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsArtifactIdCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getGroup(),
                  "rule__OsArtifactGuidCriteria__Group__0");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getGroup_2_1(),
                  "rule__OsArtifactGuidCriteria__Group_2_1__0");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getGroup_2_1_2(),
                  "rule__OsArtifactGuidCriteria__Group_2_1_2__0");
               put(grammarAccess.getOsArtifactTypeCriteriaAccess().getGroup(),
                  "rule__OsArtifactTypeCriteria__Group__0");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getGroup(),
                  "rule__OsArtifactTypeEqualsClause__Group__0");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getGroup_1_1(),
                  "rule__OsArtifactTypeEqualsClause__Group_1_1__0");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getGroup_1_1_2(),
                  "rule__OsArtifactTypeEqualsClause__Group_1_1_2__0");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getGroup(),
                  "rule__OsArtifactTypeInstanceOfClause__Group__0");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getGroup_1_1(),
                  "rule__OsArtifactTypeInstanceOfClause__Group_1_1__0");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getGroup_1_1_2(),
                  "rule__OsArtifactTypeInstanceOfClause__Group_1_1_2__0");
               put(grammarAccess.getOsAttributeCriteriaAccess().getGroup(), "rule__OsAttributeCriteria__Group__0");
               put(grammarAccess.getOsAttributeExistClauseAccess().getGroup(),
                  "rule__OsAttributeExistClause__Group__0");
               put(grammarAccess.getOsAttributeExistClauseAccess().getGroup_2_1(),
                  "rule__OsAttributeExistClause__Group_2_1__0");
               put(grammarAccess.getOsAttributeExistClauseAccess().getGroup_2_1_2(),
                  "rule__OsAttributeExistClause__Group_2_1_2__0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getGroup(), "rule__OseAttributeOpClause__Group__0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getGroup_2_1(),
                  "rule__OseAttributeOpClause__Group_2_1__0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getGroup_2_1_2(),
                  "rule__OseAttributeOpClause__Group_2_1_2__0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getGroup_3_1(),
                  "rule__OseAttributeOpClause__Group_3_1__0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getGroup_3_1_2(),
                  "rule__OseAttributeOpClause__Group_3_1_2__0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getGroup_4_1(),
                  "rule__OseAttributeOpClause__Group_4_1__0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getGroup_4_1_2(),
                  "rule__OseAttributeOpClause__Group_4_1_2__0");
               put(grammarAccess.getOsRelationCriteriaAccess().getGroup(), "rule__OsRelationCriteria__Group__0");
               put(grammarAccess.getOsRelationExistClauseAccess().getGroup(), "rule__OsRelationExistClause__Group__0");
               put(grammarAccess.getOsRelationExistClauseAccess().getGroup_4(),
                  "rule__OsRelationExistClause__Group_4__0");
               put(grammarAccess.getOsRelatedToClauseAccess().getGroup(), "rule__OsRelatedToClause__Group__0");
               put(grammarAccess.getOsRelatedToClauseAccess().getGroup_7_1(), "rule__OsRelatedToClause__Group_7_1__0");
               put(grammarAccess.getOsRelatedToClauseAccess().getGroup_7_1_2(),
                  "rule__OsRelatedToClause__Group_7_1_2__0");
               put(grammarAccess.getOsFollowClauseAccess().getGroup(), "rule__OsFollowClause__Group__0");
               put(grammarAccess.getOsFollowRelationTypeAccess().getGroup(), "rule__OsFollowRelationType__Group__0");
               put(grammarAccess.getOsFollowRelationTypeAccess().getGroup_6(),
                  "rule__OsFollowRelationType__Group_6__0");
               put(grammarAccess.getOsFollowRelationTypeAccess().getGroup_6_2(),
                  "rule__OsFollowRelationType__Group_6_2__0");
               put(grammarAccess.getOrcsScriptAccess().getVersionAssignment_0(),
                  "rule__OrcsScript__VersionAssignment_0");
               put(grammarAccess.getOrcsScriptAccess().getStatementsAssignment_1(),
                  "rule__OrcsScript__StatementsAssignment_1");
               put(grammarAccess.getScriptVersionAccess().getNameAssignment_0(),
                  "rule__ScriptVersion__NameAssignment_0");
               put(grammarAccess.getScriptVersionAccess().getVersionAssignment_1(),
                  "rule__ScriptVersion__VersionAssignment_1");
               put(grammarAccess.getOsVariableDeclarationAccess().getElementsAssignment_2(),
                  "rule__OsVariableDeclaration__ElementsAssignment_2");
               put(grammarAccess.getOsVariableDeclarationAccess().getElementsAssignment_3_1(),
                  "rule__OsVariableDeclaration__ElementsAssignment_3_1");
               put(grammarAccess.getOsVariableAccess().getNameAssignment_1(), "rule__OsVariable__NameAssignment_1");
               put(grammarAccess.getOsVariableAccess().getRightAssignment_2_1(),
                  "rule__OsVariable__RightAssignment_2_1");
               put(grammarAccess.getOsAssignmentAccess().getRightAssignment_1(),
                  "rule__OsAssignment__RightAssignment_1");
               put(grammarAccess.getOsBooleanLiteralAccess().getIsTrueAssignment_1_1(),
                  "rule__OsBooleanLiteral__IsTrueAssignment_1_1");
               put(grammarAccess.getOsNumberLiteralAccess().getValueAssignment_1(),
                  "rule__OsNumberLiteral__ValueAssignment_1");
               put(grammarAccess.getOsStringLiteralAccess().getValueAssignment_1(),
                  "rule__OsStringLiteral__ValueAssignment_1");
               put(grammarAccess.getOsTemplateLiteralAccess().getValueAssignment_2(),
                  "rule__OsTemplateLiteral__ValueAssignment_2");
               put(grammarAccess.getOsListLiteralAccess().getElementsAssignment_2_0(),
                  "rule__OsListLiteral__ElementsAssignment_2_0");
               put(grammarAccess.getOsListLiteralAccess().getElementsAssignment_2_1_1(),
                  "rule__OsListLiteral__ElementsAssignment_2_1_1");
               put(grammarAccess.getOsVariableReferenceAccess().getRefAssignment_1(),
                  "rule__OsVariableReference__RefAssignment_1");
               put(grammarAccess.getOsDotExpressionAccess().getTailAssignment_1_2(),
                  "rule__OsDotExpression__TailAssignment_1_2");
               put(grammarAccess.getOsQueryExpressionAccess().getNameAssignment_1(),
                  "rule__OsQueryExpression__NameAssignment_1");
               put(grammarAccess.getOsQueryExpressionAccess().getQueryAssignment_3(),
                  "rule__OsQueryExpression__QueryAssignment_3");
               put(grammarAccess.getOsQueryExpressionAccess().getClauseAssignment_4(),
                  "rule__OsQueryExpression__ClauseAssignment_4");
               put(grammarAccess.getOsQueryStatementAccess().getStmtAssignment_0(),
                  "rule__OsQueryStatement__StmtAssignment_0");
               put(grammarAccess.getOsCollectClauseAccess().getNameAssignment_0(),
                  "rule__OsCollectClause__NameAssignment_0");
               put(grammarAccess.getOsCollectClauseAccess().getExpressionAssignment_1(),
                  "rule__OsCollectClause__ExpressionAssignment_1");
               put(grammarAccess.getOsCollectClauseAccess().getLimitAssignment_2(),
                  "rule__OsCollectClause__LimitAssignment_2");
               put(grammarAccess.getOsLimitClauseAccess().getNameAssignment_0(),
                  "rule__OsLimitClause__NameAssignment_0");
               put(grammarAccess.getOsLimitClauseAccess().getLimitAssignment_1(),
                  "rule__OsLimitClause__LimitAssignment_1");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getNameAssignment_1(),
                  "rule__OsCollectObjectExpression__NameAssignment_1");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getAliasAssignment_2_1(),
                  "rule__OsCollectObjectExpression__AliasAssignment_2_1");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getExpressionsAssignment_4_0(),
                  "rule__OsCollectObjectExpression__ExpressionsAssignment_4_0");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getExpressionsAssignment_4_1_0(),
                  "rule__OsCollectObjectExpression__ExpressionsAssignment_4_1_0");
               put(grammarAccess.getOsCollectObjectExpressionAccess().getExpressionsAssignment_4_1_1_1(),
                  "rule__OsCollectObjectExpression__ExpressionsAssignment_4_1_1_1");
               put(grammarAccess.getOsCollectAllFieldsExpressionAccess().getNameAssignment_1(),
                  "rule__OsCollectAllFieldsExpression__NameAssignment_1");
               put(grammarAccess.getOsCollectFieldExpressionAccess().getNameAssignment_1(),
                  "rule__OsCollectFieldExpression__NameAssignment_1");
               put(grammarAccess.getOsCollectFieldExpressionAccess().getAliasAssignment_2_1(),
                  "rule__OsCollectFieldExpression__AliasAssignment_2_1");
               put(grammarAccess.getOsFindClauseAccess().getNameAssignment_0(), "rule__OsFindClause__NameAssignment_0");
               put(grammarAccess.getOsFindClauseAccess().getQueryAssignment_1(),
                  "rule__OsFindClause__QueryAssignment_1");
               put(grammarAccess.getOsBranchQueryStatementAccess().getNameAssignment_0(),
                  "rule__OsBranchQueryStatement__NameAssignment_0");
               put(grammarAccess.getOsBranchQueryStatementAccess().getDataAssignment_1(),
                  "rule__OsBranchQueryStatement__DataAssignment_1");
               put(grammarAccess.getOsBranchQueryStatementAccess().getCollectAssignment_2(),
                  "rule__OsBranchQueryStatement__CollectAssignment_2");
               put(grammarAccess.getOsBranchQueryByIdAccess().getNameAssignment(),
                  "rule__OsBranchQueryById__NameAssignment");
               put(grammarAccess.getOsBranchQueryAllAccess().getNameAssignment(),
                  "rule__OsBranchQueryAll__NameAssignment");
               put(grammarAccess.getOsBranchQueryByPredicateAccess().getNameAssignment_0(),
                  "rule__OsBranchQueryByPredicate__NameAssignment_0");
               put(grammarAccess.getOsBranchQueryByPredicateAccess().getCriteriaAssignment_1(),
                  "rule__OsBranchQueryByPredicate__CriteriaAssignment_1");
               put(grammarAccess.getOsBranchQueryByPredicateAccess().getCriteriaAssignment_2_1(),
                  "rule__OsBranchQueryByPredicate__CriteriaAssignment_2_1");
               put(grammarAccess.getOsBranchNameCriteriaAccess().getNameAssignment_0(),
                  "rule__OsBranchNameCriteria__NameAssignment_0");
               put(grammarAccess.getOsBranchNameCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsBranchNameCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsBranchNameEqualsClauseAccess().getNameAssignment_0(),
                  "rule__OsBranchNameEqualsClause__NameAssignment_0");
               put(grammarAccess.getOsBranchNameEqualsClauseAccess().getValueAssignment_1(),
                  "rule__OsBranchNameEqualsClause__ValueAssignment_1");
               put(grammarAccess.getOsBranchNamePatternClauseAccess().getNameAssignment_0(),
                  "rule__OsBranchNamePatternClause__NameAssignment_0");
               put(grammarAccess.getOsBranchNamePatternClauseAccess().getValueAssignment_1(),
                  "rule__OsBranchNamePatternClause__ValueAssignment_1");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getNameAssignment_0(),
                  "rule__OsBranchTypeCriteria__NameAssignment_0");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getTypesAssignment_2_0(),
                  "rule__OsBranchTypeCriteria__TypesAssignment_2_0");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getTypesAssignment_2_1_1(),
                  "rule__OsBranchTypeCriteria__TypesAssignment_2_1_1");
               put(grammarAccess.getOsBranchTypeCriteriaAccess().getTypesAssignment_2_1_2_1(),
                  "rule__OsBranchTypeCriteria__TypesAssignment_2_1_2_1");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getNameAssignment_0(),
                  "rule__OsBranchStateCriteria__NameAssignment_0");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getStatesAssignment_2_0(),
                  "rule__OsBranchStateCriteria__StatesAssignment_2_0");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getStatesAssignment_2_1_1(),
                  "rule__OsBranchStateCriteria__StatesAssignment_2_1_1");
               put(grammarAccess.getOsBranchStateCriteriaAccess().getStatesAssignment_2_1_2_1(),
                  "rule__OsBranchStateCriteria__StatesAssignment_2_1_2_1");
               put(grammarAccess.getOsBranchArchivedCriteriaAccess().getNameAssignment_0(),
                  "rule__OsBranchArchivedCriteria__NameAssignment_0");
               put(grammarAccess.getOsBranchArchivedCriteriaAccess().getFilterAssignment_2(),
                  "rule__OsBranchArchivedCriteria__FilterAssignment_2");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getNameAssignment_0(),
                  "rule__OsBranchIdCriteria__NameAssignment_0");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getIdsAssignment_2_0(),
                  "rule__OsBranchIdCriteria__IdsAssignment_2_0");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getIdsAssignment_2_1_1(),
                  "rule__OsBranchIdCriteria__IdsAssignment_2_1_1");
               put(grammarAccess.getOsBranchIdCriteriaAccess().getIdsAssignment_2_1_2_1(),
                  "rule__OsBranchIdCriteria__IdsAssignment_2_1_2_1");
               put(grammarAccess.getOsBranchOfCriteriaAccess().getNameAssignment_0(),
                  "rule__OsBranchOfCriteria__NameAssignment_0");
               put(grammarAccess.getOsBranchOfCriteriaAccess().getClauseAssignment_2(),
                  "rule__OsBranchOfCriteria__ClauseAssignment_2");
               put(grammarAccess.getOsBranchChildOfClauseAccess().getNameAssignment_0(),
                  "rule__OsBranchChildOfClause__NameAssignment_0");
               put(grammarAccess.getOsBranchChildOfClauseAccess().getIdAssignment_1(),
                  "rule__OsBranchChildOfClause__IdAssignment_1");
               put(grammarAccess.getOsBranchParentOfClauseAccess().getNameAssignment_0(),
                  "rule__OsBranchParentOfClause__NameAssignment_0");
               put(grammarAccess.getOsBranchParentOfClauseAccess().getIdAssignment_1(),
                  "rule__OsBranchParentOfClause__IdAssignment_1");
               put(grammarAccess.getOsTxQueryStatementAccess().getNameAssignment_0(),
                  "rule__OsTxQueryStatement__NameAssignment_0");
               put(grammarAccess.getOsTxQueryStatementAccess().getDataAssignment_1(),
                  "rule__OsTxQueryStatement__DataAssignment_1");
               put(grammarAccess.getOsTxQueryStatementAccess().getCollectAssignment_2(),
                  "rule__OsTxQueryStatement__CollectAssignment_2");
               put(grammarAccess.getOsTxQueryByIdAccess().getNameAssignment(), "rule__OsTxQueryById__NameAssignment");
               put(grammarAccess.getOsTxQueryAllAccess().getNameAssignment(), "rule__OsTxQueryAll__NameAssignment");
               put(grammarAccess.getOsTxQueryByPredicateAccess().getNameAssignment_0(),
                  "rule__OsTxQueryByPredicate__NameAssignment_0");
               put(grammarAccess.getOsTxQueryByPredicateAccess().getCriteriaAssignment_1(),
                  "rule__OsTxQueryByPredicate__CriteriaAssignment_1");
               put(grammarAccess.getOsTxQueryByPredicateAccess().getCriteriaAssignment_2_1(),
                  "rule__OsTxQueryByPredicate__CriteriaAssignment_2_1");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxTypeCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getTypesAssignment_2_0(),
                  "rule__OsTxTypeCriteria__TypesAssignment_2_0");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getTypesAssignment_2_1_1(),
                  "rule__OsTxTypeCriteria__TypesAssignment_2_1_1");
               put(grammarAccess.getOsTxTypeCriteriaAccess().getTypesAssignment_2_1_2_1(),
                  "rule__OsTxTypeCriteria__TypesAssignment_2_1_2_1");
               put(grammarAccess.getOsTxCommentCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxCommentCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxCommentCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsTxCommentCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsTxCommentEqualsClauseAccess().getNameAssignment_0(),
                  "rule__OsTxCommentEqualsClause__NameAssignment_0");
               put(grammarAccess.getOsTxCommentEqualsClauseAccess().getValueAssignment_1(),
                  "rule__OsTxCommentEqualsClause__ValueAssignment_1");
               put(grammarAccess.getOsTxCommentPatternClauseAccess().getNameAssignment_0(),
                  "rule__OsTxCommentPatternClause__NameAssignment_0");
               put(grammarAccess.getOsTxCommentPatternClauseAccess().getValueAssignment_1(),
                  "rule__OsTxCommentPatternClause__ValueAssignment_1");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxBranchIdCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getIdsAssignment_2_0(),
                  "rule__OsTxBranchIdCriteria__IdsAssignment_2_0");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getIdsAssignment_2_1_1(),
                  "rule__OsTxBranchIdCriteria__IdsAssignment_2_1_1");
               put(grammarAccess.getOsTxBranchIdCriteriaAccess().getIdsAssignment_2_1_2_1(),
                  "rule__OsTxBranchIdCriteria__IdsAssignment_2_1_2_1");
               put(grammarAccess.getOsTxHeadOfBranchIdCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxHeadOfBranchIdCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxHeadOfBranchIdCriteriaAccess().getIdAssignment_3(),
                  "rule__OsTxHeadOfBranchIdCriteria__IdAssignment_3");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxAuthorIdCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getIdsAssignment_2_0(),
                  "rule__OsTxAuthorIdCriteria__IdsAssignment_2_0");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getIdsAssignment_2_1_1(),
                  "rule__OsTxAuthorIdCriteria__IdsAssignment_2_1_1");
               put(grammarAccess.getOsTxAuthorIdCriteriaAccess().getIdsAssignment_2_1_2_1(),
                  "rule__OsTxAuthorIdCriteria__IdsAssignment_2_1_2_1");
               put(grammarAccess.getOsTxCommitIdCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxCommitIdCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxCommitIdCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsTxCommitIdCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getNameAssignment_0(),
                  "rule__OsTxCommitIdEqualsClause__NameAssignment_0");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getIdsAssignment_1_0(),
                  "rule__OsTxCommitIdEqualsClause__IdsAssignment_1_0");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getIdsAssignment_1_1_1(),
                  "rule__OsTxCommitIdEqualsClause__IdsAssignment_1_1_1");
               put(grammarAccess.getOsTxCommitIdEqualsClauseAccess().getIdsAssignment_1_1_2_1(),
                  "rule__OsTxCommitIdEqualsClause__IdsAssignment_1_1_2_1");
               put(grammarAccess.getOsTxCommitIdIsNullClauseAccess().getNameAssignment_0(),
                  "rule__OsTxCommitIdIsNullClause__NameAssignment_0");
               put(grammarAccess.getOsTxIdCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxIdCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxIdCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsTxIdCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getNameAssignment_0(),
                  "rule__OsTxIdEqualsClause__NameAssignment_0");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getIdsAssignment_1_0(),
                  "rule__OsTxIdEqualsClause__IdsAssignment_1_0");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getIdsAssignment_1_1_1(),
                  "rule__OsTxIdEqualsClause__IdsAssignment_1_1_1");
               put(grammarAccess.getOsTxIdEqualsClauseAccess().getIdsAssignment_1_1_2_1(),
                  "rule__OsTxIdEqualsClause__IdsAssignment_1_1_2_1");
               put(grammarAccess.getOsTxIdOpClauseAccess().getOpAssignment_0(), "rule__OsTxIdOpClause__OpAssignment_0");
               put(grammarAccess.getOsTxIdOpClauseAccess().getIdAssignment_1(), "rule__OsTxIdOpClause__IdAssignment_1");
               put(grammarAccess.getOsTxIdRangeClauseAccess().getNameAssignment_0(),
                  "rule__OsTxIdRangeClause__NameAssignment_0");
               put(grammarAccess.getOsTxIdRangeClauseAccess().getFromIdAssignment_2(),
                  "rule__OsTxIdRangeClause__FromIdAssignment_2");
               put(grammarAccess.getOsTxIdRangeClauseAccess().getToIdAssignment_4(),
                  "rule__OsTxIdRangeClause__ToIdAssignment_4");
               put(grammarAccess.getOsTxTimestampCriteriaAccess().getNameAssignment_0(),
                  "rule__OsTxTimestampCriteria__NameAssignment_0");
               put(grammarAccess.getOsTxTimestampCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsTxTimestampCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsTxTimestampOpClauseAccess().getOpAssignment_0(),
                  "rule__OsTxTimestampOpClause__OpAssignment_0");
               put(grammarAccess.getOsTxTimestampOpClauseAccess().getTimestampAssignment_1(),
                  "rule__OsTxTimestampOpClause__TimestampAssignment_1");
               put(grammarAccess.getOsTxTimestampRangeClauseAccess().getNameAssignment_0(),
                  "rule__OsTxTimestampRangeClause__NameAssignment_0");
               put(grammarAccess.getOsTxTimestampRangeClauseAccess().getFromAssignment_2(),
                  "rule__OsTxTimestampRangeClause__FromAssignment_2");
               put(grammarAccess.getOsTxTimestampRangeClauseAccess().getToAssignment_4(),
                  "rule__OsTxTimestampRangeClause__ToAssignment_4");
               put(grammarAccess.getOsArtifactQueryStatementAccess().getNameAssignment_0(),
                  "rule__OsArtifactQueryStatement__NameAssignment_0");
               put(grammarAccess.getOsArtifactQueryStatementAccess().getDataAssignment_1(),
                  "rule__OsArtifactQueryStatement__DataAssignment_1");
               put(grammarAccess.getOsArtifactQueryStatementAccess().getCollectAssignment_2(),
                  "rule__OsArtifactQueryStatement__CollectAssignment_2");
               put(grammarAccess.getOsArtifactQueryAllAccess().getNameAssignment(),
                  "rule__OsArtifactQueryAll__NameAssignment");
               put(grammarAccess.getOsArtifactQueryByPredicateAccess().getNameAssignment_0(),
                  "rule__OsArtifactQueryByPredicate__NameAssignment_0");
               put(grammarAccess.getOsArtifactQueryByPredicateAccess().getCriteriaAssignment_1(),
                  "rule__OsArtifactQueryByPredicate__CriteriaAssignment_1");
               put(grammarAccess.getOsArtifactQueryByPredicateAccess().getCriteriaAssignment_2_1(),
                  "rule__OsArtifactQueryByPredicate__CriteriaAssignment_2_1");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getNameAssignment_0(),
                  "rule__OsArtifactIdCriteria__NameAssignment_0");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getIdsAssignment_2_0(),
                  "rule__OsArtifactIdCriteria__IdsAssignment_2_0");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getIdsAssignment_2_1_1(),
                  "rule__OsArtifactIdCriteria__IdsAssignment_2_1_1");
               put(grammarAccess.getOsArtifactIdCriteriaAccess().getIdsAssignment_2_1_2_1(),
                  "rule__OsArtifactIdCriteria__IdsAssignment_2_1_2_1");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getNameAssignment_0(),
                  "rule__OsArtifactGuidCriteria__NameAssignment_0");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getIdsAssignment_2_0(),
                  "rule__OsArtifactGuidCriteria__IdsAssignment_2_0");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getIdsAssignment_2_1_1(),
                  "rule__OsArtifactGuidCriteria__IdsAssignment_2_1_1");
               put(grammarAccess.getOsArtifactGuidCriteriaAccess().getIdsAssignment_2_1_2_1(),
                  "rule__OsArtifactGuidCriteria__IdsAssignment_2_1_2_1");
               put(grammarAccess.getOsArtifactTypeCriteriaAccess().getNameAssignment_0(),
                  "rule__OsArtifactTypeCriteria__NameAssignment_0");
               put(grammarAccess.getOsArtifactTypeCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsArtifactTypeCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getNameAssignment_0(),
                  "rule__OsArtifactTypeEqualsClause__NameAssignment_0");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getTypesAssignment_1_0(),
                  "rule__OsArtifactTypeEqualsClause__TypesAssignment_1_0");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getTypesAssignment_1_1_1(),
                  "rule__OsArtifactTypeEqualsClause__TypesAssignment_1_1_1");
               put(grammarAccess.getOsArtifactTypeEqualsClauseAccess().getTypesAssignment_1_1_2_1(),
                  "rule__OsArtifactTypeEqualsClause__TypesAssignment_1_1_2_1");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getNameAssignment_0(),
                  "rule__OsArtifactTypeInstanceOfClause__NameAssignment_0");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getTypesAssignment_1_0(),
                  "rule__OsArtifactTypeInstanceOfClause__TypesAssignment_1_0");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getTypesAssignment_1_1_1(),
                  "rule__OsArtifactTypeInstanceOfClause__TypesAssignment_1_1_1");
               put(grammarAccess.getOsArtifactTypeInstanceOfClauseAccess().getTypesAssignment_1_1_2_1(),
                  "rule__OsArtifactTypeInstanceOfClause__TypesAssignment_1_1_2_1");
               put(grammarAccess.getOsAttributeCriteriaAccess().getNameAssignment_0(),
                  "rule__OsAttributeCriteria__NameAssignment_0");
               put(grammarAccess.getOsAttributeCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsAttributeCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsAttributeExistClauseAccess().getTypesAssignment_2_0(),
                  "rule__OsAttributeExistClause__TypesAssignment_2_0");
               put(grammarAccess.getOsAttributeExistClauseAccess().getTypesAssignment_2_1_1(),
                  "rule__OsAttributeExistClause__TypesAssignment_2_1_1");
               put(grammarAccess.getOsAttributeExistClauseAccess().getTypesAssignment_2_1_2_1(),
                  "rule__OsAttributeExistClause__TypesAssignment_2_1_2_1");
               put(grammarAccess.getOsAttributeExistClauseAccess().getNameAssignment_3(),
                  "rule__OsAttributeExistClause__NameAssignment_3");
               put(grammarAccess.getOseAttributeOpClauseAccess().getNameAssignment_1(),
                  "rule__OseAttributeOpClause__NameAssignment_1");
               put(grammarAccess.getOseAttributeOpClauseAccess().getTypesAssignment_2_0(),
                  "rule__OseAttributeOpClause__TypesAssignment_2_0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getTypesAssignment_2_1_1(),
                  "rule__OseAttributeOpClause__TypesAssignment_2_1_1");
               put(grammarAccess.getOseAttributeOpClauseAccess().getTypesAssignment_2_1_2_1(),
                  "rule__OseAttributeOpClause__TypesAssignment_2_1_2_1");
               put(grammarAccess.getOseAttributeOpClauseAccess().getOptionsAssignment_3_0(),
                  "rule__OseAttributeOpClause__OptionsAssignment_3_0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getOptionsAssignment_3_1_1(),
                  "rule__OseAttributeOpClause__OptionsAssignment_3_1_1");
               put(grammarAccess.getOseAttributeOpClauseAccess().getOptionsAssignment_3_1_2_1(),
                  "rule__OseAttributeOpClause__OptionsAssignment_3_1_2_1");
               put(grammarAccess.getOseAttributeOpClauseAccess().getValuesAssignment_4_0(),
                  "rule__OseAttributeOpClause__ValuesAssignment_4_0");
               put(grammarAccess.getOseAttributeOpClauseAccess().getValuesAssignment_4_1_1(),
                  "rule__OseAttributeOpClause__ValuesAssignment_4_1_1");
               put(grammarAccess.getOseAttributeOpClauseAccess().getValuesAssignment_4_1_2_1(),
                  "rule__OseAttributeOpClause__ValuesAssignment_4_1_2_1");
               put(grammarAccess.getOsRelationCriteriaAccess().getNameAssignment_0(),
                  "rule__OsRelationCriteria__NameAssignment_0");
               put(grammarAccess.getOsRelationCriteriaAccess().getClauseAssignment_1(),
                  "rule__OsRelationCriteria__ClauseAssignment_1");
               put(grammarAccess.getOsRelationExistClauseAccess().getNameAssignment_0(),
                  "rule__OsRelationExistClause__NameAssignment_0");
               put(grammarAccess.getOsRelationExistClauseAccess().getTypeAssignment_2(),
                  "rule__OsRelationExistClause__TypeAssignment_2");
               put(grammarAccess.getOsRelationExistClauseAccess().getOpAssignment_3(),
                  "rule__OsRelationExistClause__OpAssignment_3");
               put(grammarAccess.getOsRelationExistClauseAccess().getSideAssignment_4_1(),
                  "rule__OsRelationExistClause__SideAssignment_4_1");
               put(grammarAccess.getOsRelatedToClauseAccess().getNameAssignment_0(),
                  "rule__OsRelatedToClause__NameAssignment_0");
               put(grammarAccess.getOsRelatedToClauseAccess().getTypeAssignment_2(),
                  "rule__OsRelatedToClause__TypeAssignment_2");
               put(grammarAccess.getOsRelatedToClauseAccess().getSideAssignment_4(),
                  "rule__OsRelatedToClause__SideAssignment_4");
               put(grammarAccess.getOsRelatedToClauseAccess().getIdsAssignment_7_0(),
                  "rule__OsRelatedToClause__IdsAssignment_7_0");
               put(grammarAccess.getOsRelatedToClauseAccess().getIdsAssignment_7_1_1(),
                  "rule__OsRelatedToClause__IdsAssignment_7_1_1");
               put(grammarAccess.getOsRelatedToClauseAccess().getIdsAssignment_7_1_2_1(),
                  "rule__OsRelatedToClause__IdsAssignment_7_1_2_1");
               put(grammarAccess.getOsFollowClauseAccess().getNameAssignment_0(),
                  "rule__OsFollowClause__NameAssignment_0");
               put(grammarAccess.getOsFollowClauseAccess().getStmtAssignment_1(),
                  "rule__OsFollowClause__StmtAssignment_1");
               put(grammarAccess.getOsFollowRelationTypeAccess().getNameAssignment_0(),
                  "rule__OsFollowRelationType__NameAssignment_0");
               put(grammarAccess.getOsFollowRelationTypeAccess().getTypeAssignment_3(),
                  "rule__OsFollowRelationType__TypeAssignment_3");
               put(grammarAccess.getOsFollowRelationTypeAccess().getSideAssignment_5(),
                  "rule__OsFollowRelationType__SideAssignment_5");
               put(grammarAccess.getOsFollowRelationTypeAccess().getCriteriaAssignment_6_1(),
                  "rule__OsFollowRelationType__CriteriaAssignment_6_1");
               put(grammarAccess.getOsFollowRelationTypeAccess().getCriteriaAssignment_6_2_1(),
                  "rule__OsFollowRelationType__CriteriaAssignment_6_2_1");
               put(grammarAccess.getOsFollowRelationTypeAccess().getCollectAssignment_7(),
                  "rule__OsFollowRelationType__CollectAssignment_7");
            }
         };
      }
      return nameMappings.get(element);
   }

   @Override
   protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
      try {
         org.eclipse.osee.orcs.script.dsl.ui.contentassist.antlr.internal.InternalOrcsScriptDslParser typedParser =
            (org.eclipse.osee.orcs.script.dsl.ui.contentassist.antlr.internal.InternalOrcsScriptDslParser) parser;
         typedParser.entryRuleOrcsScript();
         return typedParser.getFollowElements();
      } catch (RecognitionException ex) {
         throw new RuntimeException(ex);
      }
   }

   @Override
   protected String[] getInitialHiddenTokens() {
      return new String[] {"RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT"};
   }

   public OrcsScriptDslGrammarAccess getGrammarAccess() {
      return this.grammarAccess;
   }

   public void setGrammarAccess(OrcsScriptDslGrammarAccess grammarAccess) {
      this.grammarAccess = grammarAccess;
   }
}
