/*********************************************************************
 * Copyright (c) 2023 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/
import { navigationElement } from '@osee/shared/types';

// if isDropdown, it has children
// if !isDropdown, it has no children

export const helpNavigationStructure: navigationElement[] = [
	// Level-1
	{
		label: 'MIM Overview',
		cypressLabel: 'mim-overview',
		pageTitle: 'MIM Overview - MIM Help',
		isDropdown: false,
		isDropdownOpen: false,
		requiredRoles: [],
		routerLink: 'mim-overview',
		icon: '',
		description: '',
		usesBranch: false,
		children: [],
	},
	{
		label: 'Data Model',
		cypressLabel: 'datamodel',
		pageTitle: 'Data Model - MIM Help',
		isDropdown: false,
		isDropdownOpen: false,
		requiredRoles: [],
		routerLink: 'datamodel',
		icon: '',
		description: '',
		usesBranch: false,
		children: [],
	},
	{
		label: 'Example ICD',
		cypressLabel: 'example-icd',
		pageTitle: 'Example ICD - MIM Help',
		isDropdown: false,
		isDropdownOpen: false,
		requiredRoles: [],
		routerLink: 'example-icd',
		icon: '',
		description: '',
		usesBranch: false,
		children: [],
	},
	{
		label: 'Guides',
		cypressLabel: 'guides',
		pageTitle: '',
		isDropdown: true,
		isDropdownOpen: true,
		requiredRoles: [],
		routerLink: '',
		icon: '',
		description: '',
		usesBranch: false,
		children: [
			{
				label: 'Creating an ICD',
				cypressLabel: 'creating-an-icd-dropdown',
				pageTitle: '',
				isDropdown: true,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '',
				icon: '',
				description: '',
				usesBranch: false,
				children: [
					{
						label: 'Creating an ICD',
						cypressLabel: 'creating-an-icd',
						pageTitle: 'Creating an ICD - MIM Help',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: 'create-icd',
						icon: '',
						description: '',
						usesBranch: false,
						children: [],
					},
					{
						label: 'Creating Elements',
						cypressLabel: 'creating-elements',
						pageTitle: 'Creating Elements - MIM Help',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: 'create-elements',
						icon: '',
						description: '',
						usesBranch: false,
						children: [],
					},
				],
			},
			{
				label: 'Editing ICDs',
				cypressLabel: 'edit-icd',
				pageTitle: 'Editing ICDs - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'edit-icd',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
			{
				label: 'Peer Review Workflow',
				cypressLabel: 'peer-review-workflow',
				pageTitle: 'Peer Review Workflow - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'peer-review',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
			{
				label: 'Treaceability',
				cypressLabel: 'traceability',
				pageTitle: 'Traceability - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'traceability',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
		],
	},
	{
		label: 'Pages',
		cypressLabel: 'pages',
		pageTitle: '',
		isDropdown: true,
		isDropdownOpen: true,
		requiredRoles: [],
		routerLink: '',
		icon: '',
		description: '',
		usesBranch: false,
		children: [
			{
				label: 'List Configuration',
				cypressLabel: 'list-config',
				pageTitle: 'List Configuration - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'list-config',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
			{
				label: 'Platform Types',
				cypressLabel: 'platform-types',
				pageTitle: 'Platform Types - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'platform-types',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
			{
				label: 'Reports',
				cypressLabel: 'reports',
				pageTitle: 'Reports - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'reports',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
			{
				label: 'Transport Types',
				cypressLabel: 'transport-types',
				pageTitle: 'Transport Types - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'transport-types',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
			{
				label: 'Cross References',
				cypressLabel: 'cross-references',
				pageTitle: 'Cross References - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'cross-references',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
			{
				label: 'Import',
				cypressLabel: 'import',
				pageTitle: 'Import - MIM Help',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: 'import',
				icon: '',
				description: '',
				usesBranch: false,
				children: [],
			},
		],
	},
];
export default helpNavigationStructure;
