pipeline {
  agent {
    kubernetes {
      label 'my-agent-pod'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    volumeMounts:
    - name: volume-known-hosts
      mountPath: /home/jenkins/.ssh
  - name: win_gnu
    image: tomaka/rust-mingw-docker
    tty: true
    command:
    - cat
    resources:
      limits:
        memory: 3Gi
        cpu: 1
      requests:
        memory: 3Gi
        cpu: 1
    env:
    - name: "HOME"
      value: "/home/jenkins"
    - name: "CARGO_HOME"
      value: "/home/jenkins/.cargo/"
    volumeMounts:
    - mountPath: "/home/jenkins"
      name: "jenkins-home"
      readOnly: false
  volumes:
  - name: volume-known-hosts
    configMap:
      name: known-hosts
  - name: "jenkins-home"
    emptyDir: {}
"""
    }
  }
  options {
    timestamps()
  }

  stages {
  
    stage('Test') {
      steps {
        container('win_gnu') {
          sh 'cargo test --target x86_86-pc-windows-gnu'
        }
      }
    }

    stage('Build') {
      steps {
        container('win_gnu') {
          sh 'cargo build --target x86_86-pc-windows-gnu --release'
        }
      }
    }
    stage('Deploy') {
      steps {
        container('jnlp') {
          sshagent ( ['projects-storage.eclipse.org-bot-ssh']) {
            sh '''
              ssh -o BatchMode=yes genie.osee@projects-storage.eclipse.org rm -rf /home/data/httpd/download.eclipse.org/technology/osee/downloads/bat/x86_64-win/1.0.0
              ssh -o BatchMode=yes genie.osee@projects-storage.eclipse.org mkdir -p /home/data/httpd/download.eclipse.org/technology/osee/downloads/bat/x86_64-win/1.0.0
              scp -o BatchMode=yes -r target/release/bat genie.osee@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/technology/osee/downloads/bat/x86_64-win/1.0.0
            '''
          }
        }
      }
    }
  }
}