java_test(
    name = "AtsServer_JUnit_TestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["@maven//:org_mockito_mockito_core", "//framework_core_packages", 
            "//:ats_api", "//:ats_core", "//:ats_rest", "//:orcs"]
)