java_test(
    name = "AtsServer_JUnit_TestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["@maven//:org_mockito_mockito_core", "//org.eclipse.osee.framework.core.packages", 
            "//org.eclipse.osee.ats.api", "//org.eclipse.osee.ats.core", "//org.eclipse.osee.ats.rest", "//org.eclipse.osee.orcs"]
)
