/*
 * generated by Xtext
 */
package org.eclipse.osee.ats.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 */
public class AtsDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
   //
}
