# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image: $DOCKER_REGISTRY/python:latest

before_script:
  - python --version
  - git --version

stages:
  - validate

validate-job:
  stage: validate
  script:
    - FILES=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHORT_SHA)
    - echo "Files to validate:"
    - echo $FILES
    - python validateFiles.py $EXCLUDED_KEYWORDS $FILES

