include:
  - project: $TEMPLATE_PROJECT_LOCATION
    ref: dev
    file:
      - $BUILD_OSEE_TEMPLATE
      - $BUILD_AND_TEST_OSEE_TEMPLATE
      - $VALIDATE_OSEE_BUILD_TEMPLATE

stages:
  - prepare
  - validate
  - build_OSEE
  - build_and_test_OSEE
  - validate_OSEE_build

variables:
  VARIABLES_FILE: ./variables.txt
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

Get file list:
  stage: prepare
  image: $DOCKER_IMAGE_GIT
  script:
    - git --version
    - git fetch
    - FILES=$(git diff --name-only origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | awk '{print $1}' | sed "s/^/'/;s/$/'/")
    - echo $FILES > $VARIABLES_FILE
    - echo "Files to validate:"
    - echo $FILES | tr " " "\n"
  artifacts:
    paths:
      - $VARIABLES_FILE
  only:
    - merge_requests

Validate files:
  stage: validate
  image: $DOCKER_IMAGE_PYTHON
  script:
    - python --version
    - FILES=$(cat $VARIABLES_FILE)
    - echo $FILES | tr " " "\n"
    - python plugins/org.eclipse.osee.support.dev/validationScripts/validateFiles.py "$EXCLUDED_KEYWORDS" $FILES
  only:
    - merge_requests

Angular Tests:
  stage: validate
  image: $DOCKER_IMAGE_NODE_CHROME
  before_script:
    - cd plugins/org.eclipse.osee.web
    - npm -v
    - node -v
    - npm config set strict-ssl false
    - npm config list
    - npm ci --cache $CI_PROJECT_DIR/plugins/org.eclipse.osee.web/.npm/ --prefer-offline
  script:
    - npx -p @angular/cli ng lint
    - npx prettier --check .
    - npx stylelint '**/*.scss'
    - npx -p @angular/cli ng test --browsers=ChromeHeadless --watch=false
    - npx -p @angular/cli ng build -c production
  cache:
    key:
      files:
        - $CI_PROJECT_DIR/plugins/org.eclipse.osee.web/package-lock.json
    paths:
      - $CI_PROJECT_DIR/plugins/org.eclipse.osee.web/.npm/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        paths:
          - plugins/org.eclipse.osee.web/**/*

Build_Org_Eclipse_OSEE:
  stage: build_OSEE
  when: manual

Build_And_Test_Org_Eclipse_OSEE:
  stage: build_and_test_OSEE
  when: manual

Validate_Org_Eclipse_OSEE_Build:
  stage: validate_OSEE_build
  only:
    - merge_requests
