# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:
  - prepare
  - validate

variables:
  VARIABLES_FILE: ./variables.txt

Get file list:
  stage: prepare
  image: $DOCKER_IMAGE_GIT
  script:
    - git --version
    - git fetch
    - FILES=$(git diff --name-only origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME)
    - echo $FILES > $VARIABLES_FILE
    - echo "Files to validate:"
    - echo $FILES | tr " " "\n"
  artifacts:
    paths:
      - $VARIABLES_FILE
  only:
    - merge_requests

Validate files:
  stage: validate
  image: $DOCKER_IMAGE_PYTHON
  script:
    - python --version
    - FILES=$(cat $VARIABLES_FILE)
    - echo $FILES | tr " " "\n"
    - python plugins/org.eclipse.osee.support.dev/validationScripts/validateFiles.py "$EXCLUDED_KEYWORDS" $FILES
  only:
    - merge_requests
