packages:
  - web/apps/*
  - web/packages/*
  - plugins/org.eclipse.oss.ajax
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
overrides:
  "ngx-markdown@18.1.0>mermaid": "-"
