java_test(
    name = "OrcsRest_JUnit_TestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.orcs.rest", "//org.eclipse.osee.framework.core",
            "//org.eclipse.osee.framework.jdk.core","//org.eclipse.osee.orcs.rest.model",
            "@maven//:org_mockito_mockito_core"]
)
