java_test(
    name = "OrcsRest_JUnit_TestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//:orcs_rest", "//org.eclipse.osee.framework.core:framework_core",
            "//org.eclipse.osee.framework.jdk.core:framework_jdk_core","//:orcs_rest_model",
            "@maven//:org_mockito_mockito_core"]
)