
-- OSEE_ACCOUNT_SESSION
CREATE TABLE OSEE_ACCOUNT_SESSION (
	CREATED_ON TIMESTAMP NOT NULL,
	ACCOUNT_ID ${db.bigint} NOT NULL,
	ACCESSED_FROM VARCHAR(255) NOT NULL,
	ACCESS_DETAILS VARCHAR(255) NOT NULL,
	LAST_ACCESSED_ON TIMESTAMP NOT NULL,
	SESSION_TOKEN VARCHAR(255) NOT NULL,
	CONSTRAINT OSEE_ACCOUNT_SESSION_PK PRIMARY KEY(ACCOUNT_ID,SESSION_TOKEN)
);

CREATE INDEX OSEE_ACCOUNT_SESSION_T_IDX ON OSEE_ACCOUNT_SESSION(SESSION_TOKEN);

