java_test(
	name = "OsgiMain",
	srcs = ["src/org/eclipse/osee/logger/OsgiMain.java"],
	deps = ["@ext_jars//:eclipse_osgi_services","@maven//:org_apache_sling_org_apache_sling_testing_osgi_mock_junit5",
	"@maven//:org_apache_sling_org_apache_sling_testing_osgi_mock_core"],
	visibility = ["//visibility:public"]		
)
