java_test(
    name = "AllConsoleAdminTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//:console_admin","//org.eclipse.osee.framework.jdk.core:framework_jdk_core",
            "@ext_jars//:eclipse_osgi_services"]
)
