java_test(
    name = "AllConsoleAdminTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.console.admin","//org.eclipse.osee.framework.jdk.core",
            "@ext_jars//:eclipse_osgi_services"]
)
