//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.07 at 08:56:57 PM MST 
//


package org.eclipse.osee.framework.messaging.event.res.msgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.eclipse.osee.framework.messaging.event.res.RemoteEvent;


/**
 * <p>Java class for RemoteBranchRenameEvent1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoteBranchRenameEvent1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modTypeGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branchGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="networkSender" type="{}RemoteNetworkSender1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoteBranchRenameEvent1", propOrder = {
    "name",
    "shortName",
    "modTypeGuid",
    "branchGuid",
    "networkSender"
})
public class RemoteBranchRenameEvent1
    extends RemoteEvent
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String shortName;
    @XmlElement(required = true)
    protected String modTypeGuid;
    @XmlElement(required = true)
    protected String branchGuid;
    @XmlElement(required = true)
    protected RemoteNetworkSender1 networkSender;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the modTypeGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModTypeGuid() {
        return modTypeGuid;
    }

    /**
     * Sets the value of the modTypeGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModTypeGuid(String value) {
        this.modTypeGuid = value;
    }

    /**
     * Gets the value of the branchGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchGuid() {
        return branchGuid;
    }

    /**
     * Sets the value of the branchGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchGuid(String value) {
        this.branchGuid = value;
    }

    /**
     * Gets the value of the networkSender property.
     * 
     * @return
     *     possible object is
     *     {@link RemoteNetworkSender1 }
     *     
     */
    public RemoteNetworkSender1 getNetworkSender() {
        return networkSender;
    }

    /**
     * Sets the value of the networkSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoteNetworkSender1 }
     *     
     */
    public void setNetworkSender(RemoteNetworkSender1 value) {
        this.networkSender = value;
    }

}
