/*********************************************************************
 * Copyright (c) 2023 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.14 at 05:06:42 PM MST
//

package org.eclipse.osee.framework.messaging.event.res.msgs;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.eclipse.osee.framework.messaging.event.res.RemoteEvent;

/**
 * <p>
 * Java class for RemoteNetworkSender1 complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoteNetworkSender1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceObject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="machineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="machineIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clientVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoteNetworkSender1", propOrder = {
   "sourceObject",
   "sessionId",
   "machineName",
   "userId",
   "machineIp",
   "clientVersion",
   "port"})
public class RemoteNetworkSender1 extends RemoteEvent {

   @XmlElement(required = true)
   protected String sourceObject;
   @XmlElement(required = true)
   protected String sessionId;
   @XmlElement(required = true)
   protected String machineName;
   @XmlElement(required = true)
   protected String userId;
   @XmlElement(required = true)
   protected String machineIp;
   @XmlElement(required = true)
   protected String clientVersion;
   protected int port;

   /**
    * Gets the value of the sourceObject property.
    * 
    * @return possible object is {@link String }
    */
   public String getSourceObject() {
      return sourceObject;
   }

   /**
    * Sets the value of the sourceObject property.
    * 
    * @param value allowed object is {@link String }
    */
   public void setSourceObject(String value) {
      this.sourceObject = value;
   }

   /**
    * Gets the value of the sessionId property.
    * 
    * @return possible object is {@link String }
    */
   public String getSessionId() {
      return sessionId;
   }

   /**
    * Sets the value of the sessionId property.
    * 
    * @param value allowed object is {@link String }
    */
   public void setSessionId(String value) {
      this.sessionId = value;
   }

   /**
    * Gets the value of the machineName property.
    * 
    * @return possible object is {@link String }
    */
   public String getMachineName() {
      return machineName;
   }

   /**
    * Sets the value of the machineName property.
    * 
    * @param value allowed object is {@link String }
    */
   public void setMachineName(String value) {
      this.machineName = value;
   }

   /**
    * Gets the value of the userId property.
    * 
    * @return possible object is {@link String }
    */
   public String getUserId() {
      return userId;
   }

   /**
    * Sets the value of the userId property.
    * 
    * @param value allowed object is {@link String }
    */
   public void setUserId(String value) {
      this.userId = value;
   }

   /**
    * Gets the value of the machineIp property.
    * 
    * @return possible object is {@link String }
    */
   public String getMachineIp() {
      return machineIp;
   }

   /**
    * Sets the value of the machineIp property.
    * 
    * @param value allowed object is {@link String }
    */
   public void setMachineIp(String value) {
      this.machineIp = value;
   }

   /**
    * Gets the value of the clientVersion property.
    * 
    * @return possible object is {@link String }
    */
   public String getClientVersion() {
      return clientVersion;
   }

   /**
    * Sets the value of the clientVersion property.
    * 
    * @param value allowed object is {@link String }
    */
   public void setClientVersion(String value) {
      this.clientVersion = value;
   }

   /**
    * Gets the value of the port property.
    */
   public int getPort() {
      return port;
   }

   /**
    * Sets the value of the port property.
    */
   public void setPort(int value) {
      this.port = value;
   }

}
