//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.14 at 05:06:42 PM MST
//

package org.eclipse.osee.framework.messaging.event.res.msgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import org.eclipse.osee.framework.core.data.ArtifactTypeId;
import org.eclipse.osee.framework.core.data.BranchId;
import org.eclipse.osee.framework.jdk.core.util.Strings;
import org.eclipse.osee.framework.messaging.event.res.RemoteEvent;

/**
 * <p>
 * Java class for RemoteBasicGuidArtifact1 complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RemoteBasicGuidArtifact1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modTypeGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branchGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artTypeGuid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="artGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attributes" type="{}RemoteAttributeChange1" maxOccurs="unbounded"/>
 *         &lt;element name="toArtTypeGuid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoteBasicGuidArtifact1", propOrder = {
   "modTypeGuid",
   "branchGuid",
   "artTypeGuid",
   "artGuid",
   "attributes",
   "toArtTypeGuid"})
public class RemoteBasicGuidArtifact1 extends RemoteEvent {

   @XmlElement(required = true)
   protected String modTypeGuid;
   @XmlElement(required = true)
   protected String branchGuid;
   protected long artTypeGuid;
   @XmlElement(required = true)
   protected String artGuid;
   @XmlElement(required = true)
   protected List<RemoteAttributeChange1> attributes;
   protected long toArtTypeGuid;
   @XmlTransient
   private BranchId branch;

   /**
    * Gets the value of the modTypeGuid property.
    *
    * @return possible object is {@link String }
    */
   public String getModTypeGuid() {
      return modTypeGuid;
   }

   /**
    * Sets the value of the modTypeGuid property.
    *
    * @param value allowed object is {@link String }
    */
   public void setModTypeGuid(String value) {
      this.modTypeGuid = value;
   }

   /**
    * Gets the value of the branchGuid property.
    *
    * @return possible object is {@link String }
    */
   public String getBranchGuid() {
      return branchGuid;
   }

   public BranchId getBranch() {
      if (branch == null && Strings.isNumeric(branchGuid)) {
         branch = BranchId.valueOf(branchGuid);
      }

      return branch;
   }

   public void setBranch(BranchId branch) {
      this.branch = branch;
      this.branchGuid = branch.getIdString();
   }

   /**
    * Gets the value of the artTypeGuid property.
    */
   public long getArtTypeGuid() {
      return artTypeGuid;
   }

   public ArtifactTypeId getArtifactType() {
      return ArtifactTypeId.valueOf(artTypeGuid);
   }

   public void setArtifactType(ArtifactTypeId type) {
      this.artTypeGuid = type.getId();
   }

   /**
    * Sets the value of the artTypeGuid property.
    */
   public void setArtTypeGuid(long value) {
      this.artTypeGuid = value;
   }

   /**
    * Gets the value of the artGuid property.
    *
    * @return possible object is {@link String }
    */
   public String getArtGuid() {
      return artGuid;
   }

   /**
    * Sets the value of the artGuid property.
    *
    * @param value allowed object is {@link String }
    */
   public void setArtGuid(String value) {
      this.artGuid = value;
   }

   /**
    * Gets the value of the attributes property.
    * <p>
    * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
    * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
    * the attributes property.
    * <p>
    * For example, to add a new item, do as follows:
    *
    * <pre>
    * getAttributes().add(newItem);
    * </pre>
    * <p>
    * Objects of the following type(s) are allowed in the list {@link RemoteAttributeChange1 }
    */
   public List<RemoteAttributeChange1> getAttributes() {
      if (attributes == null) {
         attributes = new ArrayList<>();
      }
      return this.attributes;
   }

   /**
    * Gets the value of the toArtTypeGuid property.
    */
   public long getToArtTypeGuid() {
      return toArtTypeGuid;
   }

   public ArtifactTypeId getToArtifactType() {
      return ArtifactTypeId.valueOf(toArtTypeGuid);
   }

   public void setToArtifactType(ArtifactTypeId type) {
      this.toArtTypeGuid = type.getId();
   }

   /**
    * Sets the value of the toArtTypeGuid property.
    */
   public void setToArtTypeGuid(long value) {
      this.toArtTypeGuid = value;
   }

}
