//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.07 at 08:56:57 PM MST 
//


package org.eclipse.osee.framework.messaging.event.res.msgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.eclipse.osee.framework.messaging.event.res.RemoteEvent;


/**
 * <p>Java class for RemoteBasicGuidArtifact1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoteBasicGuidArtifact1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="branchGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artTypeGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoteBasicGuidArtifact1", propOrder = {
    "branchGuid",
    "artTypeGuid",
    "artGuid"
})
public class RemoteBasicGuidArtifact1
    extends RemoteEvent
{

    @XmlElement(required = true)
    protected String branchGuid;
    @XmlElement(required = true)
    protected String artTypeGuid;
    @XmlElement(required = true)
    protected String artGuid;

    /**
     * Gets the value of the branchGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchGuid() {
        return branchGuid;
    }

    /**
     * Sets the value of the branchGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchGuid(String value) {
        this.branchGuid = value;
    }

    /**
     * Gets the value of the artTypeGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtTypeGuid() {
        return artTypeGuid;
    }

    /**
     * Sets the value of the artTypeGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtTypeGuid(String value) {
        this.artTypeGuid = value;
    }

    /**
     * Gets the value of the artGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtGuid() {
        return artGuid;
    }

    /**
     * Sets the value of the artGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtGuid(String value) {
        this.artGuid = value;
    }

}
