//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.09.14 at 05:06:42 PM MST
//

package org.eclipse.osee.framework.messaging.event.res.msgs;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.eclipse.osee.framework.core.data.BranchId;
import org.eclipse.osee.framework.messaging.event.res.RemoteEvent;

/**
 * <p>
 * Java class for RemoteBasicGuidRelationReorder1 complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RemoteBasicGuidRelationReorder1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modTypeGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branchGuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relTypeGuid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="parentArt" type="{}RemoteBasicGuidArtifact1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoteBasicGuidRelationReorder1", propOrder = {
   "modTypeGuid",
   "branchGuid",
   "relTypeGuid",
   "parentArt"})
public class RemoteBasicGuidRelationReorder1 extends RemoteEvent {

   @XmlElement(required = true)
   protected String modTypeGuid;
   @XmlElement(required = true)
   protected String branchGuid;
   protected long relTypeGuid;
   @XmlElement(required = true)
   protected RemoteBasicGuidArtifact1 parentArt;

   /**
    * Gets the value of the modTypeGuid property.
    *
    * @return possible object is {@link String }
    */
   public String getModTypeGuid() {
      return modTypeGuid;
   }

   /**
    * Sets the value of the modTypeGuid property.
    *
    * @param value allowed object is {@link String }
    */
   public void setModTypeGuid(String value) {
      this.modTypeGuid = value;
   }

   /**
    * Gets the value of the branchGuid property.
    *
    * @return possible object is {@link String }
    */
   public String getBranchGuid() {
      return branchGuid;
   }

   public void setBranchGuid(BranchId branch) {
      this.branchGuid = branch.getIdString();
   }

   /**
    * Gets the value of the relTypeGuid property.
    */
   public long getRelTypeGuid() {
      return relTypeGuid;
   }

   /**
    * Sets the value of the relTypeGuid property.
    */
   public void setRelTypeGuid(long value) {
      this.relTypeGuid = value;
   }

   /**
    * Gets the value of the parentArt property.
    *
    * @return possible object is {@link RemoteBasicGuidArtifact1 }
    */
   public RemoteBasicGuidArtifact1 getParentArt() {
      return parentArt;
   }

   /**
    * Sets the value of the parentArt property.
    *
    * @param value allowed object is {@link RemoteBasicGuidArtifact1 }
    */
   public void setParentArt(RemoteBasicGuidArtifact1 value) {
      this.parentArt = value;
   }

}
