/*
 * generated by Xtext
 */
package org.eclipse.osee.framework.core.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OseeDslRuntimeModule extends org.eclipse.osee.framework.core.dsl.AbstractOseeDslRuntimeModule {

}
