/*
 * generated by Xtext
 */
package org.eclipse.osee.framework.core.dsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class OseeDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public OseeDslLabelProvider(AdapterFactoryLabelProvider labelProvider) {
		super(labelProvider);
	}
}
