/*********************************************************************
 * Copyright (c) 2021 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/

import { PlatformTypeSentinel } from '@osee/messaging/shared/enumerations';
import type {
	element,
	elementWithPathsAndButtons,
} from '@osee/messaging/shared/types';

export const elementSearch1: element[] = [
	{
		id: '0',
		name: 'name',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '1',
		name: 'name1',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '2',
		name: 'name2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '0',
		name: 'name2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
];

export const elementSearch2: element[] = [
	{
		id: '3',
		name: 'Title0',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '1',
		name: 'Title1',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '5',
		name: 'Title2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '0',
		name: 'Title3',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
	},
];

export const elementSearch3: elementWithPathsAndButtons[] = [
	{
		id: '0',
		name: 'Title0',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		enumLiteral: '',
		paths: ['path 1'],
		buttonNames: ['name 1'],
		units: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '1',
		name: 'Title1',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		enumLiteral: '',
		paths: ['path 1', 'path2'],
		buttonNames: ['name 1', 'name2'],
		units: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '2',
		name: 'Title2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		enumLiteral: '',
		paths: [],
		buttonNames: [],
		units: '',
		platformType: new PlatformTypeSentinel(),
	},
	{
		id: '3',
		name: 'Title3',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		enumLiteral: '',
		paths: ['path 1'],
		buttonNames: ['name 1'],
		units: '',
		platformType: new PlatformTypeSentinel(),
	},
];
