/*********************************************************************
 * Copyright (c) 2021 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/

import {
	ArrayHeaderPlatformType,
	PlatformTypeSentinel,
} from '@osee/messaging/shared/enumerations';
import type {
	element,
	elementWithPathsAndButtons,
} from '@osee/messaging/shared/types';

export const elementSearch1: element[] = [
	{
		id: '0',
		name: 'name',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '1',
		name: 'name1',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '2',
		name: 'name2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '0',
		name: 'name2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
];

export const elementSearch2: element[] = [
	{
		id: '3',
		name: 'Title0',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '1',
		name: 'Title1',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '5',
		name: 'Title2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '0',
		name: 'Title3',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
];

export const elementSearch3: elementWithPathsAndButtons[] = [
	{
		id: '0',
		name: 'Title0',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		enumLiteral: '',
		paths: ['path 1'],
		buttonNames: ['name 1'],
		units: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '1',
		name: 'Title1',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		enumLiteral: '',
		paths: ['path 1', 'path2'],
		buttonNames: ['name 1', 'name2'],
		units: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '2',
		name: 'Title2',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		enumLiteral: '',
		paths: [],
		buttonNames: [],
		units: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
	{
		id: '3',
		name: 'Title3',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: false,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		enumLiteral: '',
		paths: ['path 1'],
		buttonNames: ['name 1'],
		units: '',
		platformType: new PlatformTypeSentinel(),
		arrayElements: [],
	},
];

export const elementSearch4: element[] = [
	{
		id: '0',
		name: 'name',
		description: '',
		notes: '',
		interfaceElementAlterable: true,
		interfaceElementArrayHeader: true,
		interfaceElementWriteArrayHeaderName: false,
		interfaceElementIndexEnd: 1,
		interfaceElementIndexStart: 0,
		interfaceDefaultValue: '',
		interfaceElementArrayIndexOrder: 'OUTER_INNER',
		interfaceElementArrayIndexDelimiterOne: ' ',
		interfaceElementArrayIndexDelimiterTwo: ' ',
		units: '',
		enumLiteral: '',
		platformType: new ArrayHeaderPlatformType(),
		arrayElements: [
			{
				id: '1',
				name: 'name1',
				description: '',
				notes: '',
				interfaceElementAlterable: true,
				interfaceElementArrayHeader: false,
				interfaceElementWriteArrayHeaderName: false,
				interfaceElementIndexEnd: 1,
				interfaceElementIndexStart: 0,
				interfaceDefaultValue: '',
				interfaceElementArrayIndexOrder: 'OUTER_INNER',
				interfaceElementArrayIndexDelimiterOne: ' ',
				interfaceElementArrayIndexDelimiterTwo: ' ',
				units: '',
				enumLiteral: '',
				platformType: new PlatformTypeSentinel(),
				arrayElements: [],
			},
			{
				id: '2',
				name: 'name2',
				description: '',
				notes: '',
				interfaceElementAlterable: true,
				interfaceElementArrayHeader: false,
				interfaceElementWriteArrayHeaderName: false,
				interfaceElementIndexEnd: 1,
				interfaceElementIndexStart: 0,
				interfaceDefaultValue: '',
				interfaceElementArrayIndexOrder: 'OUTER_INNER',
				interfaceElementArrayIndexDelimiterOne: ' ',
				interfaceElementArrayIndexDelimiterTwo: ' ',
				units: '',
				enumLiteral: '',
				platformType: new PlatformTypeSentinel(),
				arrayElements: [],
			},
		],
	},
];
