[package]
name = "applicability_lexer_config_custom"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
nom = "8.0.0"
nom_locate = "5.0.0"
tracing = { version = "0.1.40" }
applicability_lexer_base = { path = "../applicability_lexer_base"}
memchr = "2.7.4"