#
# Copyright (c) 2024 Boeing
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Boeing - initial API and implementation
workspace(name =  "example")
load("@bazel_tools//tools/build_defs/repo:http.bzl",  "http_archive")
http_archive(
    name =  "bazel_skylib",
    sha256 =  "cd55a062e763b9349921f0f5db8c3933288dc8ba4f76dd9416aac68acee3cb94",
    urls = ["https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.5.0/bazel-skylib-1.5.0.tar.gz",
    "https://github.com/bazelbuild/bazel-skylib/releases/download/1.5.0/bazel-skylib-1.5.0.tar.gz"])
load( "@bazel_skylib//:workspace.bzl",  "bazel_skylib_workspace")
bazel_skylib_workspace()
http_archive(
    name = "rules_pkg",
    urls = [
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.10.1/rules_pkg-0.10.1.tar.gz",
    ],
    sha256 = "d250924a2ecc5176808fc4c25d5cf5e9e79e6346d79d5ab1c493e289e722d1d0",
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()
http_archive(
    name = "aspect_bazel_lib",
    sha256 = "f2c1f91cc0a55f7a44c94b8a79974f21349b844075740c01045acaa49e731307",
    strip_prefix = "bazel-lib-1.40.3",
    url = "https://github.com/aspect-build/bazel-lib/releases/download/v1.40.3/bazel-lib-v1.40.3.tar.gz",
)

load("@aspect_bazel_lib//lib:repositories.bzl", "aspect_bazel_lib_dependencies")

aspect_bazel_lib_dependencies()
local_repository(
    name="rules_osee",
    path="../"
)
load("@rules_osee//bat:repositories.bzl","bat_register_toolchains")
bat_register_toolchains()
load("@rules_osee//plconfig:repositories.bzl","product_line_config")
product_line_config(
    name="my_product_line",            
    osee_url="http://host.docker.internal:8089",
    branch_id="8",
    sha256="E2B4B141504947A152618288DE5B58BCAFFA7B48A6D27494F1BF821338BA059C")