= Design
Donald G. Dunne<donald.g.dunne@boeing.com>

Provides the classes necessary to create tasks for different cases and design of task builder use cases, configuration and code classes.

== Use Case 1: Static Task Set

=== Description
* User would like to add a set(s) of tasks from a static list of task names. 
* Creation From Workflow Editor > Task Tab > Gear Pulldown
* Tasks are created based on static (coded) task set rules

=== Configuration
* Defined task set definition token as AtsTaskDefToken.  eg: TaskSetDefinitionTokensDemo
* IAtsTaskSetDefinitionProvider provides TaskSetDefinitions through CreateTasksDefinitionBuilder. eg: AtsTaskSetDefinitionProvider
* Add to Team Defs Task Set in Work Definition through .andTaskSet eg: DemoDatabaseConfig sawSwTeam.createChildTeamDef

=== Use
* Items will show in Gear menu of Workflow's Task Tab for any workflow of that Team Definition

== Use Case 2: Change Report Related Tasks

=== Description
* User would like to auto-create task based on a Team Workflow's Change Report
* Can be created from Workflow Editor state widget OR from state transition
* Can be created from this Team Workflow's change report or a sibling's change report
* Tasks are created based default or configured task generation rules

=== Configuration (both)
* Defined task set definition token as AtsTaskDefToken.  eg: TaskSetDefinitionTokensDemo
* TaskSetDefinitionProvider provides TaskSetDefinitions through CreateChangeReportTasksDefinitionBuilder eg: AtsTaskSetDefinitionProvider 

==== = From Workflow Editor Button
* Configure Task Creation widget in Workflow Definition using above token. eg: WorkDefTeamDemoCode > Implement State > new CreateChangeReportTasksWidgetDefinition("Create Tasks from Requirement Changes", TaskSetDefinitionTokensDemo.SawCreateTasksFromReqChanges). 
* This adds widget on that state with the Set Definition Token given

==== = From Workflow Transition
* Configure Task Creation on transition using above token. eg: WorkDefTeamDemoReq > Completed State > .andTransitionListener(TaskSetDefinitionTokensDemo.SawCreateTasksFromReqChanges);

=== Use
* Tasks will be auto-generated/updated when Team Workflow gets transition to configured state.
 
==== = From Workflow Editor Button
* Select button on Workflow Editor to create/update tasks

==== = From Workflow Transition
* Transition configured Team Workflow to create/update tasks

== Use Case 3: Integration Build Task from Build/Version

=== Description
* User would like to auto-create tasks based on a ATS Build/Version
* User would like tasks based on each ATS Action in a Version
* User would like static tasks that show up each time
* Tasks are assigned to assignee of action or configured assignee if static

=== Configuration
TBD

=== Use
TBD

== Classes: 

=== AtsTaskDefToken
Token used to specify what CreateTasksDefinition to use in generating tasks. This can be specified in XCreateCodeTestTasksButton for use in WorkDef or through ATsTaskService to call programatically. 


=== StaticTaskDefinition
Definition of static task to be created. This is only used by AtsTaskService.addTask and not by tasks to be created by change report changes. TBD: May want to rename this to StaticCreateTaskDefinition? 

=== CreateTasksDefinition
Definition that determines what to do when tasks are to be generated. This is created used the task builder in java code and provided to ATS framework through osgi as IAtsTaskSetDefinitionProvider. See AtsTaskSetDefinitionProvider for examples. It also contains a list of StaticTaskDefinition for static tasks to be defined to create regardless of the change report.

=== ChangeReportTaskData 
Top level pojo that is sent into the ATS endpoint for task from change reports. As creation operation moves through its processing, different values are added and set for future use. 

It contains:
* 1..n of @link ChangeReportTaskTeamWfData - PoJo that represents that work to be done for one Team Workflow and
its generated tasks. There will be one of these for every sibling team workflow configured for tasks.
* 1..n of @link ChangeReportTaskMatch - PoJo that represents 3 things. 
** ChangeReportArt it references 
** Task Title 
** IAtsTask that exists or is null. One object will be created for each art/title pair. This allows for a single change art to be tied to multiple tasks. eg: Different partitions need a task created for the same change art.

