/*******************************************************************************
 * Copyright (c) 2018 Boeing.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Boeing - initial API and implementation
 *******************************************************************************/
package org.eclipse.osee.framework.skynet.core.importing.parsers;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.eclipse.osee.framework.core.enums.CoreAttributeTypes;
import org.eclipse.osee.framework.jdk.core.type.OseeCoreException;
import org.eclipse.osee.framework.jdk.core.util.Strings;
import org.eclipse.osee.framework.skynet.core.importing.RoughArtifact;
import org.eclipse.osee.framework.skynet.core.importing.RoughArtifactKind;
import org.eclipse.osee.framework.skynet.core.importing.operations.RoughArtifactCollector;

/**
 * @author David W. Miller
 */
/**
 * This is a special word outline extractor that handles documents generated by Doors. It is looking for tags, wrapped
 * in {}, that define the scope and type of the artifact that is being created during the import process.
 */
public class DoorsWordOutlineExtractor extends WordOutlineExtractorDelegate {
   private static final Pattern reqnamePattern = Pattern.compile("(\\{[^}]+\\})(.*?</w:p>)");
   private static final Pattern outlinePattern = Pattern.compile("(\\{[^}]+\\})");
   private static final Pattern doorsIdPattern = Pattern.compile("\\{[^-]+\\-([^}]+)\\}");
   private int lastReqNumber = 1;

   @Override
   protected void addChildRoughArtifact(String content, RoughArtifactCollector collector) {
      StringBuilder newName = new StringBuilder();
      StringBuilder newContent = new StringBuilder();
      if (needsNewArt(content, newName, newContent)) {
         setContent(); // finishes the previous rough artifact
         String number = String.format("%s.0.%d", lastHeaderNumber.toString(), lastReqNumber++);

         String name = newName.toString();
         if (name.contains("<w")) { // remove invalid tags from names
            name = name.replaceAll("<[^>]+>", "");
         }
         roughArtifact = new RoughArtifact(getRoughArtifactType(name));
         roughArtifact.setName(name);

         if (collector != null) {
            collector.addRoughArtifact(roughArtifact);
         }
         if (Strings.isValid(number)) {
            roughArtifact.setSectionNumber(number);
            roughArtifact.addAttribute(CoreAttributeTypes.ParagraphNumber, number);
         }
         Matcher match = doorsIdPattern.matcher(name);
         if (match.find()) {
            String toSet = match.group(1);
            roughArtifact.addAttribute(CoreAttributeTypes.StaticId, toSet);
         }
         roughArtifact.addAttribute(CoreAttributeTypes.PublishInline, "True");
         wordFormattedContent.append(newContent.toString());
         previousNamedArtifact = roughArtifact;
      } else {
         wordFormattedContent.append(content);
      }
   }

   private RoughArtifactKind getRoughArtifactType(String newName) {
      RoughArtifactKind toReturn = RoughArtifactKind.PRIMARY;
      if (newName.contains("Doc Dsc")) {
         toReturn = RoughArtifactKind.TERTIARY;
      } else if (newName.contains("Dsg Dsc")) {
         toReturn = RoughArtifactKind.QUATERNARY;
      }
      return toReturn;
   }

   @Override
   public void processHeadingText(RoughArtifact roughArtifact, String headingText) throws OseeCoreException {
      roughArtifact.setRoughArtifactKind(RoughArtifactKind.SECONDARY);
      Matcher match = outlinePattern.matcher(headingText);
      if (match.find()) {
         roughArtifact.setName(headingText.substring(0, match.start(1)).trim());
         Matcher matchId = doorsIdPattern.matcher(headingText);
         if (matchId.find()) {
            roughArtifact.addAttribute(CoreAttributeTypes.StaticId, matchId.group(1));
         }
         return;
      }
      roughArtifact.setName(headingText.trim());
   }

   @Override
   protected boolean checkSectionNumber(String sectionNumber) {
      if (sectionNumber.contains(".0.")) {
         return true; // special case of numbering requirements below a section number
      }
      return false;
   }

   @Override
   public void resetReqNumber() {
      lastReqNumber = 1;
   }

   @Override
   public String getName() {
      return "Doors Word Outline";
   }

   private boolean needsNewArt(String content, StringBuilder newName, StringBuilder newContent) {
      if (content.contains("####")) {
         return false; // special case for match in description
      }
      Matcher match = reqnamePattern.matcher(content);
      if (match.find()) {
         String begin = content.substring(0, match.start(1));
         newName.append(content.substring(match.start(1), match.start(2)));
         String endString = content.substring(match.start(2), match.end(2));
         newContent.append(begin + endString);
         return true; // only finds the first one
      }
      return false;
   }
}
