
java_library(
    name = "framework_core_packages",
    exports = [
               "//org.eclipse.osee.framework.jdk.core:framework_jdk_core",
               "//org.eclipse.osee.framework.core:framework_core",
               "//org.eclipse.osee.framework.logging:framework_logging",
               "//org.eclipse.osee.logger:logger"
              ],
    visibility = ["//visibility:public"]
)
