import { PlatformType } from "../../types/PlatformType";

export const platformTypes1: PlatformType[] = [
    {
        interfaceLogicalType: '',
        interfacePlatform2sComplement: false,
        interfacePlatformTypeAnalogAccuracy: '',
        interfacePlatformTypeBitSize: '8',
        interfacePlatformTypeBitsResolution: '8',
        interfacePlatformTypeCompRate: '',
        interfacePlatformTypeDefaultValue: '',
        interfacePlatformTypeEnumLiteral: '',
        interfacePlatformTypeMaxval: '1',
        interfacePlatformTypeMinval: '0',
        interfacePlatformTypeMsbValue: '0',
        interfacePlatformTypeUnits: '',
        interfacePlatformTypeValidRangeDescription: '',
        id: '0',
        name:'Name'
    },
    {
        interfaceLogicalType: '',
        interfacePlatform2sComplement: false,
        interfacePlatformTypeAnalogAccuracy: '',
        interfacePlatformTypeBitSize: '8',
        interfacePlatformTypeBitsResolution: '8',
        interfacePlatformTypeCompRate: '',
        interfacePlatformTypeDefaultValue: '',
        interfacePlatformTypeEnumLiteral: '',
        interfacePlatformTypeMaxval: '1',
        interfacePlatformTypeMinval: '0',
        interfacePlatformTypeMsbValue: '0',
        interfacePlatformTypeUnits: '',
        interfacePlatformTypeValidRangeDescription: '',
        id: '1',
        name:'Name2'
    },
    {
        interfaceLogicalType: '',
        interfacePlatform2sComplement: false,
        interfacePlatformTypeAnalogAccuracy: '',
        interfacePlatformTypeBitSize: '8',
        interfacePlatformTypeBitsResolution: '8',
        interfacePlatformTypeCompRate: '',
        interfacePlatformTypeDefaultValue: '',
        interfacePlatformTypeEnumLiteral: '',
        interfacePlatformTypeMaxval: '1',
        interfacePlatformTypeMinval: '0',
        interfacePlatformTypeMsbValue: '0',
        interfacePlatformTypeUnits: '',
        interfacePlatformTypeValidRangeDescription: '',
        id: '2',
        name:'Name3'
    },
]

export const platformTypes2: PlatformType[] = [
    {
        interfaceLogicalType: '',
        interfacePlatform2sComplement: false,
        interfacePlatformTypeAnalogAccuracy: '',
        interfacePlatformTypeBitSize: '8',
        interfacePlatformTypeBitsResolution: '8',
        interfacePlatformTypeCompRate: '',
        interfacePlatformTypeDefaultValue: '',
        interfacePlatformTypeEnumLiteral: '',
        interfacePlatformTypeMaxval: '1',
        interfacePlatformTypeMinval: '0',
        interfacePlatformTypeMsbValue: '0',
        interfacePlatformTypeUnits: '',
        interfacePlatformTypeValidRangeDescription: '',
        id: '3',
        name:'Title'
    },
    {
        interfaceLogicalType: '',
        interfacePlatform2sComplement: false,
        interfacePlatformTypeAnalogAccuracy: '',
        interfacePlatformTypeBitSize: '8',
        interfacePlatformTypeBitsResolution: '8',
        interfacePlatformTypeCompRate: '',
        interfacePlatformTypeDefaultValue: '',
        interfacePlatformTypeEnumLiteral: '',
        interfacePlatformTypeMaxval: '1',
        interfacePlatformTypeMinval: '0',
        interfacePlatformTypeMsbValue: '0',
        interfacePlatformTypeUnits: '',
        interfacePlatformTypeValidRangeDescription: '',
        id: '4',
        name:'Title2'
    },
    {
        interfaceLogicalType: '',
        interfacePlatform2sComplement: false,
        interfacePlatformTypeAnalogAccuracy: '',
        interfacePlatformTypeBitSize: '8',
        interfacePlatformTypeBitsResolution: '8',
        interfacePlatformTypeCompRate: '',
        interfacePlatformTypeDefaultValue: '',
        interfacePlatformTypeEnumLiteral: '',
        interfacePlatformTypeMaxval: '1',
        interfacePlatformTypeMinval: '0',
        interfacePlatformTypeMsbValue: '0',
        interfacePlatformTypeUnits: '',
        interfacePlatformTypeValidRangeDescription: '',
        id: '2',
        name:'Title3'
    },
]