/*******************************************************************************
 * Copyright (c) 2004, 2007 Boeing.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Boeing - initial API and implementation
 *******************************************************************************/
package org.eclipse.osee.framework.jdk.core.text.rules;

import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.eclipse.osee.framework.jdk.core.text.Rule;
import org.eclipse.osee.framework.jdk.core.text.change.ChangeSet;

/**
 * @author Ryan D. Brooks
 */
public class InsertTypeGuids extends Rule {
   private static final Pattern classDeclarationP = Pattern.compile("Type \"([^\"]*)\".*?\\{\\s*"); //Type "([^"]*)".*?\{
   private static final Map<String, String> typeGuids = new HashMap<String, String>();

   public InsertTypeGuids() {
      super(null);
      //      super("oseetemp");
      setFileNamePattern(Pattern.compile(".*\\.osee"));
      typeGuids.put("PrivilegedMember","AAMFE9XfiibyK1x2FiwA");
      typeGuids.put("Fault Triggered WCA","AAMFE9huTnrVP25oD0QA");
      typeGuids.put("Work Item","AAMFE9jvEzcbzwAfjzwA");
      typeGuids.put("User Grouping","AAMFE9lpTHwUo4DbvKAA");
      typeGuids.put("Users","AAMFE9nibXSCqcoXkMAA");
      typeGuids.put("Supercedes","AAMFE9qJZC_qegaByjgA");
      typeGuids.put("Default Hierarchical","AAMFE9skWhPMi6I1WdAA");
      typeGuids.put("Dependency","AAMFE9uek34jqArVRuAA");
      typeGuids.put("Supporting Info","AAMFE9wWnVhFW0wtOPAA");
      typeGuids.put("Universal Grouping","AAMFE9yOp2hIrXwZ13wA");
      typeGuids.put("TeamLead","AAMFE90HyTZPyHuQWOQA");
      typeGuids.put("TeamMember","AAMFE92A6gCO9WJ2ijQA");
      typeGuids.put("TeamActionableItem","AAMFE939Ul9Oenq9wWgA");
      typeGuids.put("ActionToWorkflow","AAMFE953ixQThusHUPwA");
      typeGuids.put("SmaToTask","AAMFE97xw1BM5l+GxKAA");
      typeGuids.put("TeamWorkflowTargetedForVersion","AAMFE99pzm4zSibDT9gA");
      typeGuids.put("TeamDefinitionToVersion","AAMFE9_i7zG3lR1kGWQA");
      typeGuids.put("TeamDefinitionToWorkflowDiagram","AAMFE+BpKTGewbN8c3gA");
      typeGuids.put("TeamDefinitionToTaskWorkflowDiagram","AAMFE+DkeQ9mRBPca0QA");
      typeGuids.put("TeamDefinitionToDecisionReviewWorkflowDiagram","AAMFE+Fg4RmKrda_jJQA");
      typeGuids.put("TeamDefinitionToPeerToPeerReviewWorkflowDiagram","AAMFE+HqYUG262IxMFwA");
      typeGuids.put("TeamWorkflowToReview","AAMFE+JqDz+8tuRDdIwA");
      typeGuids.put("SubscribedUser","AAMFE+LkSAkfUWoTHdwA");
      typeGuids.put("FavoriteUser","AAMFE+NegDLK1g2ph+AA");
      typeGuids.put("Functional decomposition ","AAMFE+PYuWYLd90Mm4AA");
      typeGuids.put("Allocation","AAMFE+RS8gRV2BXaCtQA");
      typeGuids.put("Code-Requirement","AAMFE+TNKxG5ytcGHqgA");
      typeGuids.put("Component-Requirement","AAMFE+VoIUTy9BoL1PgA");
      typeGuids.put("Design","AAMFE+XjcSaqnXfOXVQA");
      typeGuids.put("Verification","AAMFE+ZdqgB+D5zP5+gA");
      typeGuids.put("Verification Procedure","AAMFE+bY+ibHHBJu0dAA");
      typeGuids.put("Requirement Trace","AAMFE+dRBVFN6fAPXdwA");
      typeGuids.put("Validation","AAMFE+fMVRM8f9BUD0AA");
      typeGuids.put("Specifying","AAMFE+hPSXzdCioUZHgA");
      typeGuids.put("Test Script to Run Relation","AAMFE+jMyBDK7CV479wA");
      typeGuids.put("Qualification","AAMFE+lNjSyN52Q9wGwA");
      typeGuids.put("RdtReader","AAMFE+nOUn+UAe_brRQA");
      typeGuids.put("TeamDefinitionToLbaCodeEngBuild","AAMFE+_ApD7eaCEnnlgA");
      typeGuids.put("TeamDefinitionToLbaCodePlanCmBuild","AAMFE_B5EQ3r0BYUelAA");
      typeGuids.put("ParallelVersion","AAMFE_EJHSBGb9msPXQA");
      typeGuids.put("Uses","AAMFE_GV43rvba32QqwA");
      typeGuids.put("lba.code.Category","AAMFENvFNCTZ6g00QCQA");
      typeGuids.put("lba.code.Close Detection","AAMFEN2LLBoybDTX+MAA");
      typeGuids.put("lba.code.Code Change Req","AAMFEN4eflpy2Yo_CqAA");
      typeGuids.put("lba.code.CSCI","AAMFEN7h1HR8zWVC5XAA");
      typeGuids.put("lba.code.Defect Code","AAMFEN9wyUHLSFJmPRwA");
      typeGuids.put("lba.code.Detection","AAMFEN_7YSCEzUfTOywA");
      typeGuids.put("lba.code.Include Build","AAMFEOCc4wpYxGP_osAA");
      typeGuids.put("lba.code.LOC Affected","AAMFEOE9TQPNgG7FfKQA");
      typeGuids.put("lba.code.Originating Build","AAMFEOVzel4uyftnX3QA");
      typeGuids.put("lba.code.Req Doc","AAMFEOYuFRHjVkP6M8gA");
      typeGuids.put("lba.code.Subsystem","AAMFEOa9CjUjF4jUItgA");
      typeGuids.put("lba.code.Test Build","AAMFEOdPRVVX+a0uLyAA");
      typeGuids.put("lba.code.Test Mode","AAMFEOfYxWSVzod9nRAA");
      typeGuids.put("lba.code.Test Notes","AAMFEOlUiDnWigR+7+QA");
      typeGuids.put("lba.code.Test Script","AAMFEOno8jHLZ4zqxVQA");
      typeGuids.put("lba.code.Change Type","AAMFEOp1uFJWTap4jWgA");
      typeGuids.put("lba.code.Action","AAMFEOr_OBldJas2C0AA");
      typeGuids.put("lba.code.Volume","AAMFEOuddEJ5kM0qGkAA");
      typeGuids.put("lba.code.Verify Date","AAMFEOwoCxmlUf8OkxQA");
      typeGuids.put("lba.code.Verifyer","AAMFEOyyo3MID+Ux37gA");
      typeGuids.put("lba.code.Verify Note","AAMFEO09OnrXKkm_JWwA");
      typeGuids.put("lba.code.Verify Detection","AAMFEO8bNALP5S0jjBgA");
      typeGuids.put("lba.code.Hold Start","AAMFEO+rQDpHDAiVgxwA");
      typeGuids.put("lba.code.Hold End","AAMFEPA4BkStk4xfuBgA");
      typeGuids.put("lba.code.Verify Mode","AAMFEPDG+33mBi4vVYgA");
      typeGuids.put("lba.code.Verified Build","AAMFEPFQexiraZQ18DgA");
      typeGuids.put("lba.code.Peer Review Reqd","AAMFEPHbEym8mrB8_AQA");
      typeGuids.put("lba.code.Peer Review Id","AAMFEPJxq2qyFZlAtlQA");
      typeGuids.put("lba.code.Ref PCR","AAMFEPMBtyXjHMk9_rQA");
      typeGuids.put("lba.code.References","AAMFEPOYUHjH5XQduAAA");
      typeGuids.put("lba.code.Requirement Id","AAMFEPQlFmyysQBe95QA");
      typeGuids.put("lba.code.Dup CPCR No","AAMFEPSvrSr5zQE7viwA");
      typeGuids.put("lba.code.Dup CSCI","AAMFEPU5LRVQnup9ScwA");
      typeGuids.put("lba.code.Dup CPCR Type","AAMFEPXE3G9g6nE7oogA");
      typeGuids.put("lba.code.Dup of CPCR no seq","AAMFEPZXFwbmOFzyCFgA");
      typeGuids.put("lba.code.Librarian","AAMFEPbmCz7o5ViZ30wA");
      typeGuids.put("lba.code.Promote Date","AAMFEPdz6QdyRceq8_QA");
      typeGuids.put("lba.code.Authorization Notes","AAMFEPgMsC8nIYDLFaAA");
      typeGuids.put("lba.code.Rework Letter","AAMFEPiiMSrFfm_OgTAA");
      typeGuids.put("lba.code.Problem No","AAMFEPlAbWBYXt3vL2gA");
      typeGuids.put("lba.code.DP Effectivity","AAMFEPnRkSmKNkk2XyAA");
      typeGuids.put("lba.code.SP Effectivity","AAMFEPpfbgQaAL6EiNwA");
      typeGuids.put("lba.code.WP Effectivity","AAMFEPrwkg3QDcU6_tgA");
      typeGuids.put("ats.Uses Resolution Options","AAMFEPuOzltN1+Ze1kQA");
      typeGuids.put("lba.deliverable.Doc Number","AAMFEPwf8QUXDACiJLQA");
      typeGuids.put("lba.deliverable.Revision Letter","AAMFEPzwYAtq54BcQrQA");
      typeGuids.put("lba.deliverable.Reference Number","AAMFEP1+PSviLH7Kk3wA");
      typeGuids.put("lba.deliverable.Submitted to Data Management","AAMFEP4LA1LrPyQui9QA");
      typeGuids.put("lba.deliverable.Submitted to Customer","AAMFEP6XyhsQDOPvahAA");
      typeGuids.put("Developmental","AAMFEP8lp3EupVzVp5QA");
      typeGuids.put("Row","AAMFEP_sQ3w5AxKe1EgA");
      typeGuids.put("Summary","AAMFEQCP9GGra4NlyCwA");
      typeGuids.put("Hazard","AAMFEQEe6XK8hGjJNxgA");
      typeGuids.put("AFHA","AAMFEQGsxihCZXcrWtQA");
      typeGuids.put("SFHA","AAMFEQI800ecbF8oCPwA");
      typeGuids.put("Hazard Severity","AAMFEQLLyEqgnjt85bwA");
      typeGuids.put("Safety Objective","AAMFEQNYjjVjRoKuDsAA");
      typeGuids.put("FTA Results","AAMFEQPomlhpBRRUceQA");
      typeGuids.put("GFE / CFE","AAMFEQR0SW+7bERFvXQA");
      typeGuids.put("ats.Require Targeted Version","AAMFEQUBDxMJ67lodTQA");
      typeGuids.put("ats.Metrics from Tasks","AAMFEQWQA3qvWxjeCbgA");
      typeGuids.put("ats.Branch Id","AAMFEQYd4VpF0Fy2+VAA");
      typeGuids.put("ats.Transaction Id","AAMFEQaqpwxoT7Sx9UQA");
      typeGuids.put("ats.Branch Metrics","AAMFEQc7yxE0jUqVA7wA");
      typeGuids.put("ats.Authors","AAMFEQmzoyhG0QNbstQA");
      typeGuids.put("wcafe.AdaName","AAMFEX4gZw5t1SI83jQA");
      typeGuids.put("wcafe.CBIT","AAMFEYA8lTolxAPbAOQA");
      typeGuids.put("wcafe.EUFDText","AAMFEYHOKxNDqsjY0kQA");
      typeGuids.put("wcafe.MinimumOnTime","AAMFEYR8lB_NMhuzq5gA");
      typeGuids.put("wcafe.PBIT","AAMFEYcCnHashcG3Y7AA");
      typeGuids.put("ats.Log","AAMFEdgB1DX3eJSZb0wA");
      typeGuids.put("ats.SMA Note","AAMFEdm7ywte8qayfbAA");
      typeGuids.put("ats.Category3","AAMFEd06oxr8LMzZxdgA");
      typeGuids.put("Common NAL Requirement","AAMFEQpKOwh5p+AgC8wA");
      typeGuids.put("Crew Interface Requirement","AAMFEQrZMEwBcq2pQTgA");
      typeGuids.put("Timing Critical","AAMFEQufzUc+GfevktwA");
      typeGuids.put("Obsolescence date","AAMFEQwtqjmwugHV5cAA");
      typeGuids.put("Complexity Factor","AAMFEQzCFHDHjZRhu0gA");
      typeGuids.put("Weight","AAMFEQ1O2gDzsLbJ9vAA");
      typeGuids.put("Imported Paragraph Number","AAMFEQ3boD3sp6VfArAA");
      typeGuids.put("Legacy Id","AAMFEQ5rrGxHTSvY73gA");
      typeGuids.put("Level 2 IPT","AAMFEQ75igfFmfq_DAgA");
      typeGuids.put("Level 3 IPT","AAMFEQ+eUjbje5ksynAA");
      typeGuids.put("Support IPT","AAMFERAuXgVx1TlareQA");
      typeGuids.put("System Security Requirement","AAMFERC8OyWTMm8tMOQA");
      typeGuids.put("Training Effectivity","AAMFERFJAm0_WZ0WQaQA");
      typeGuids.put("Partition","AAMFERHj9w6pmoLBCaQA");
      typeGuids.put("Subsystem","AAMFERJ1GweNukuSd8QA");
      typeGuids.put("Qualification Method","AAMFERMRKHkM9k_Rg2QA");
      typeGuids.put("lba.Build Increment","AAMFEROyqg8OkmmBviQA");
      typeGuids.put("Test Status","AAMFERRDznjwkYn+ugAA");
      typeGuids.put("Test Pass","AAMFERTXIHAmwjVkjFgA");
      typeGuids.put("Test Fail","AAMFERVnLHThpASHn1wA");
      typeGuids.put("Version","AAMFERX4UAvPcLnvswwA");
      typeGuids.put("Repository Type","AAMFERaLojPfsL4I2AwA");
      typeGuids.put("Modification Flag","AAMFERccxh8La5wlEmgA");
      typeGuids.put("Test Log","AAMFERet6VP3iltwxMwA");
      typeGuids.put("Safety Criticality","AAMFERg99R51HIz45HAA");
      typeGuids.put("TIS Test Number","AAMFERjRSDDgyyBh+OAA");
      typeGuids.put("TIS Test Type","AAMFEVXVuFcy8wCED5AA");
      typeGuids.put("TIS Test Category","AAMFEVbEtV4QJQvA5eQA");
      typeGuids.put("Development Assurance Level","AAMFEVdW8Bdjtx4GvfwA");
      typeGuids.put("Category","AAMFEVfcEjwtly9djdgA");
      typeGuids.put("Technical Performance Parameter","AAMFEVhhNTVx42mlvlQA");
      typeGuids.put("Component","AAMFEVjkKR2EMfwWk4AA");
      typeGuids.put("Outfile URL","AAMFEVlyBndUvySg+gwA");
      typeGuids.put("Test Script URL","AAMFEVn0+mhxtCuACgAA");
      typeGuids.put("Revision","AAMFEWAal2I3j7EJligA");
      typeGuids.put("Modified Flag","AAMFEWCruiS26nCN68wA");
      typeGuids.put("Last Author","AAMFEWE83iPq3+2DGrQA");
      typeGuids.put("Last Modified Date","AAMFEWHw7V1uWv4IKcQA");
      typeGuids.put("OS Architecture","AAMFEWKJtG+Jc8OkRYgA");
      typeGuids.put("OS Name","AAMFEWMdBmP9aCgsysgA");
      typeGuids.put("OS Version","AAMFEWOvQWV6JJvh9NQA");
      typeGuids.put("OSEE Version","AAMFEWQ_TTkstJvjnGQA");
      typeGuids.put("OSEE Server Title","AAMFEWTnXGYRfdzY3gAA");
      typeGuids.put("OSEE Server Jar Version","AAMFEWV1OQtXL67OfOQA");
      typeGuids.put("Processor ID","AAMFEWYOAGkplo4RjTQA");
      typeGuids.put("Start Date","AAMFEWpeXjfr2W5ZT5QA");
      typeGuids.put("End Date","AAMFEWryxym0P9FFckgA");
      typeGuids.put("Elapsed Date","AAMFEWuD6yH04y89M3wA");
      typeGuids.put("Passed","AAMFEWwT92IzQp6Dh3gA");
      typeGuids.put("Failed","AAMFEWynSU+XeRG7nRAA");
      typeGuids.put("Total Test Points","AAMFEW05hBfECFGfZkgA");
      typeGuids.put("Script Aborted","AAMFEW3M12AqHsCve4AA");
      typeGuids.put("Test Script GUID","AAMFEW5fEhinpcjeZ0wA");
      typeGuids.put("Ran In Batch Mode","AAMFEW7uBlg0KLp8mhQA");
      typeGuids.put("Is Batch Mode Allowed","AAMFEW+CcA6F5GEjsSgA");
      typeGuids.put("User ID","AAMFEXATlG8HeyNn9fQA");
      typeGuids.put("Last Date Uploaded","AAMFEXCm5ju5gvq142QA");
      typeGuids.put("Qualification Level","AAMFEXEvTztOWwoGyRAA");
      typeGuids.put("Build Id","AAMFEXG6_W9diA9nUXAA");
      typeGuids.put("Checksum","AAMFEXJbaHt5uKG9kogA");
      typeGuids.put("ROIN","AAMFEXL6uyk3IAg0ipQA");
      typeGuids.put("CSCI","AAMFEXPEnnkY_07EbRgA");
      typeGuids.put("Verification Level","AAMFEXRTkyKVIFqcMwQA");
      typeGuids.put("Bracket Mode","AAMFEXTWhglrEzVajBwA");
      typeGuids.put("On/Off Mode","AAMFEXVYYwt16v7O+tQA");
      typeGuids.put("(N) On/Off Mode","AAMFEXXbVxqIyJXHv4AA");
      typeGuids.put("Box Mode","AAMFEXZfYi1WC5WmxzgA");
      typeGuids.put("(N) Box Mode","AAMFEXbjbSYDvMQIZ2AA");
      typeGuids.put("Upon Crew Selection of (N)","AAMFEXdneDKVh0Lg6mgA");
      typeGuids.put("Disposition","AAMFEXfoPWRZHNiOR3gA");
      typeGuids.put("KU Pre-load String","AAMFEXhqGggHe4SojvQA");
      typeGuids.put("Procedures/Functions","AAMFEXjr9n7GgSPnM1gA");
      typeGuids.put("Verification Event","AAMFEXlt02WfQ0jcQtAA");
      typeGuids.put("lba.config.osee.Project Type","AAMFEXn0DU+HrC5hk4AA");
      typeGuids.put("lba.config.osee.Static Id Prefix","AAMFEXp3ABTn_prr1qQA");
      typeGuids.put("lba.config.osee.Trax Program Name","AAMFEXsDxn3mkRx2S_gA");
      typeGuids.put("lba.config.osee.Project Name","AAMFEXuQjROm9S96jfAA");
      typeGuids.put("lba.config.osee.PeerDb Project","AAMFEXwUmHBzsN7flRgA");
      typeGuids.put("lba.config.osee.PeerDb Program","AAMFEXyXjFxW8B5k5GQA");
      typeGuids.put("lba.config.osee.PeerDb CSCI","AAMFEX0ZaFrTdUhc3qgA");
      typeGuids.put("lba.config.osee.Default User Community","AAMFEX2dc0yyQIYo9RgA");
      typeGuids.put("wcafe.AirCrewText","AAMFEX6kcg3i0s9E1_wA");
      typeGuids.put("wcafe.AncillaryFault","AAMFEX8yUBCYKjNocNAA");
      typeGuids.put("wcafe.AutoPage","AAMFEX+6uD3LQyGvEhgA");
      typeGuids.put("wcafe.CIURecording","AAMFEYC+cTLRkU1ifQQA");
      typeGuids.put("wcafe.Corrective Action","AAMFEYFATmJKYrC_qIAA");
      typeGuids.put("wcafe.FilterTime","AAMFEYK54jICX3zVUMwA");
      typeGuids.put("wcafe.IBITPage","AAMFEYNSqQB3p5GFTtwA");
      typeGuids.put("wcafe.MaintenanceText","AAMFEYPnEwBm827PluQA");
      typeGuids.put("wcafe.MPDText","AAMFEYUic1gRn9YuRswA");
      typeGuids.put("wcafe.PackageName","AAMFEYW6I05TNE3m7swA");
      typeGuids.put("wcafe.Path","AAMFEYZykACYZqEBxOgA");
      typeGuids.put("wcafe.ProcedureCodes","AAMFEYeOS2XdG3VPxoAA");
      typeGuids.put("wcafe.Tones","AAMFEYgw5F1_8ceHTBgA");
      typeGuids.put("Display If","AAMFEYjuxiwEtrLRQcAA");
      typeGuids.put("Barrier If","AAMFEYmCGErrkkX6qOwA");
      typeGuids.put("OIP If","AAMFEYoXmWcQNaGYhdAA");
      typeGuids.put("SF If","AAMFEYqnpVy5F7k3vfwA");
      typeGuids.put("Format (Location)","AAMFEYs54C7fMZxc83AA");
      typeGuids.put("Rename","AAMFEYvJ7F0QONRbvXgA");
      typeGuids.put("Local Data Definition","AAMFEYxY4VR89la41owA");
      typeGuids.put("Index","AAMFEYzmv2W+I_GJT9QA");
      typeGuids.put("Top Mode","AAMFEY2JWG6bhH4daXAA");
      typeGuids.put("Mode","AAMFEY4XNQx8bCdNdFwA");
      typeGuids.put("Bottom Mode","AAMFEY6nQm2siFWpEfAA");
      typeGuids.put("Color Mode","AAMFEY83ThaPi_4SfxwA");
      typeGuids.put("Upon Crew Selection","AAMFEY_SRDq+7n_scSwA");
      typeGuids.put("KU Label","AAMFEZByrkE8tuPAwIwA");
      typeGuids.put("KU Validation","AAMFEZEE6SfIYb0L5jwA");
      typeGuids.put("Current Page Mode","AAMFEZG0m2KYVhjIq4QA");
      typeGuids.put("Total Pages Mode","AAMFEZMcuS7sm+8UrJQA");
      typeGuids.put("Controls and Display Variance","AAMFEZO69VaqJ59rFfgA");
      typeGuids.put("Display (N) If","AAMFEZQ5jDVJEoHWxjwA");
      typeGuids.put("Barrier (N) If","AAMFEZS+rkV5mu9xeQAA");
      typeGuids.put("OIP (N) If","AAMFEZU_c3NqKn+narQA");
      typeGuids.put("SF (N) If","AAMFEZXLInbkpp1x3JwA");
      typeGuids.put("NVM Local Data Definition","AAMFEZZL50p3vAoiutwA");
      typeGuids.put("Transferred NVM Local Data Definition","AAMFEZbO2yLM7gF4Y9gA");
      typeGuids.put("Zeroized NVM Local Data Definition","AAMFEZdPoBP5UubfAkgA");
      typeGuids.put("Zeroized Transferred NVM Local Data Definition","AAMFEZfPTnLKs65LNZQA");
      typeGuids.put("Declaration","AAMFEZhMzVdvMC4P1sAA");
      typeGuids.put("(N) Mode","AAMFEZjNklPSsDW8xrgA");
      typeGuids.put("(N) Top Mode","AAMFEZlOV2ODvb7b7jQA");
      typeGuids.put("(N) Bottom Mode","AAMFEZnPHBGzilFsUiAA");
      typeGuids.put("Type","AAMFEZpP4XjpuH2ti8QA");
      typeGuids.put("lba.Subsystem","AAMFEZrQpi2hR1A0ksgA");
      typeGuids.put("lba.Change Type","AAMFEZtRa1W1_aeS7DQA");
      typeGuids.put("lba.Retirement Date","AAMFEZveMRfQr5olnMwA");
      typeGuids.put("lba.Migration Date","AAMFEZxe913IhZ7iIpgA");
      typeGuids.put("lba.cte.CTE Station","AAMFEZzepCgKQPaH+awA");
      typeGuids.put("lba.cte.CTE Area","AAMFEZ1k3l5GsyVKXVgA");
      typeGuids.put("lba.cte.Material Cost","AAMFEZ3kjFm756zU9GAA");
      typeGuids.put("lba.cte.CTE SW Release","AAMFEZ5jIk_hxkNTlFAA");
      typeGuids.put("lba.cte.File List","AAMFEZ7pXD8KWrsSSaAA");
      typeGuids.put("lba.config.RPCR Letter","AAMFEZ9m20BG13KNKJAA");
      typeGuids.put("lba.config.San RPCR Letter","AAMFEZ_kWh9Wki5eOQgA");
      typeGuids.put("lba.config.Complexity Req Low","AAMFEaHNPnNCZ3xcBewA");
      typeGuids.put("lba.config.Complexity Ctr Low","AAMFEaJWvi45c+78O4AA");
      typeGuids.put("lba.config.Complexity Code High","AAMFEaLeD0Z4L_oBX1AA");
      typeGuids.put("lba.config.Complexity Code Low","AAMFEaNzkFe_cDWia2AA");
      typeGuids.put("lba.config.Complexity Ctr High","AAMFEaQhEyewehIcJewA");
      typeGuids.put("lba.config.Complexity Req High","AAMFEaSmNj9PZuZr8uQA");
      typeGuids.put("lba.config.Complexity Script Low","AAMFEaUl4yBG6bQY5BAA");
      typeGuids.put("lba.config.Complexity Script High","AAMFEaXTZjPD0XV1nXgA");
      typeGuids.put("lba.config.Program Id","AAMFEaZmuUTbQ5rFq+QA");
      typeGuids.put("lba.config.Rank","AAMFEab2xRJyycUO8CQA");
      typeGuids.put("lba.config.Primary DB Id","AAMFEaeNXRWjXBUaUtwA");
      typeGuids.put("lba.config.State Set","AAMFEagj9iPRKQ1b9fAA");
      typeGuids.put("lba.config.Current Build Plan","AAMFEaitdipF9IBAOggA");
      typeGuids.put("lba.config.Working Build PLan","AAMFEalIawimmDWKNGwA");
      typeGuids.put("lba.config.Description","AAMFEanapm6Y9LGIa_QA");
      typeGuids.put("lba.config.CPCR Name","AAMFEap2tHIMC3geBQwA");
      typeGuids.put("lba.config.TPCR Name","AAMFEasI71CaCAxS4LQA");
      typeGuids.put("lba.config.CPCR SAN Name","AAMFEauVtU5LxHuk19QA");
      typeGuids.put("lba.config.TPCR SAN Name","AAMFEawie0ofSiF2QEQA");
      typeGuids.put("lba.config.Ext Program Name","AAMFEayxcEDRkwkMq7QA");
      typeGuids.put("lba.config.Ext Project Name","AAMFEa1BfDKuSzaEhBQA");
      typeGuids.put("lba.config.Ext San Project Name","AAMFEa3bWm1LsJ9JUVgA");
      typeGuids.put("Display (N) Bottom Mode If","AAMFEa5qTzJCV3beYAgA");
      typeGuids.put("Display Bottom Mode If","AAMFEa+JUBmILdOU1IwA");
      typeGuids.put("ats.Allow Create Branch","AAMFEbARuQEvi6rtY5gA");
      typeGuids.put("ats.Allow Commit Branch","AAMFEbCZCkwgj73BsQgA");
      typeGuids.put("ats.Review Defect","AAMFEd+MSVAb8JQ6f5gA");
      typeGuids.put("lba.Active","AAMFEeE14nvq2mLtvHQA");
      typeGuids.put("lba.POC","AAMFEeJLEB_GMacO6nwA");
      typeGuids.put("lba.Platforms","AAMFEgKy5luQ7a+PKIwA");
      typeGuids.put("lba.Developed Using","AAMFEgPvXg91QSBBMawA");
      typeGuids.put("lba.SW Enhancement","AAMFEgVmxCgOdP+DuNwA");
      typeGuids.put("lba.code.Promote Item","AAMFEbEsXAJe32+bS1QA");
      typeGuids.put("Upon KU Enter","AAMFEbGoxG9E0nSLPwgA");
      typeGuids.put("Active","AAMFEbImQyR38BY8A5QA");
      typeGuids.put("User Id","AAMFEbKl8RCQr17bDAQA");
      typeGuids.put("Favorite Branch","AAMFEbMnzS7P92knZKAA");
      typeGuids.put("User Settings","AAMFEbOnewRpnYFgnHQA");
      typeGuids.put("XViewer Customization","AAMFEbQk+hTB9fE3uNAA");
      typeGuids.put("XViewer Defaults","AAMFEbSjkAKRqLzkWpAA");
      typeGuids.put("Phone","AAMFEbUkVSwKu4LSpWAA");
      typeGuids.put("Mobile Phone","AAMFEbWi7AIC1z82PxQA");
      typeGuids.put("Fax Phone","AAMFEbYdJAmEGg0TFhAA");
      typeGuids.put("Email","AAMFEbaZjEVoecDFCCQA");
      typeGuids.put("Dictionary","AAMFEbcV9BXFKOqkVIwA");
      typeGuids.put("Template Match Criteria","AAMFEbeRRENHX5KTmxwA");
      typeGuids.put("Company","AAMFEbgTIG1iJuHoe6wA");
      typeGuids.put("Company Title","AAMFEbiRtwq7hoavdXwA");
      typeGuids.put("City","AAMFEbkRZE1lIUmm_0AA");
      typeGuids.put("Street","AAMFEbmjn19BhPhE2cwA");
      typeGuids.put("State","AAMFEbolfGTBLHnDCRQA");
      typeGuids.put("Zip","AAMFEbqmQUTrgrQ7rKgA");
      typeGuids.put("Country","AAMFEbsk1xGUlmXk8zgA");
      typeGuids.put("Notes","AAMFEbulnFZFQCiyvpAA");
      typeGuids.put("Website","AAMFEbwiBAmrHwSeMHgA");
      typeGuids.put("osee.wi.Work Data","AAMFEbyhslOoQf3+hyAA");
      typeGuids.put("osee.wi.Work Id","AAMFEb0hXw933Zrje2QA");
      typeGuids.put("osee.wi.Work Type","AAMFEb2f9nh42sjMHfAA");
      typeGuids.put("osee.wi.Work Description","AAMFEb57TkhPHyzOLDwA");
      typeGuids.put("osee.wi.Work Parent Id","AAMFEb8R5y9WcjD5hcwA");
      typeGuids.put("osee.wi.Work Page Name","AAMFEb+vCyCjKbzzHoQA");
      typeGuids.put("osee.wi.Transition","AAMFEcBLGB5U+55hJrQA");
      typeGuids.put("osee.wi.Start Page","AAMFEcDfggQLaAdLlpQA");
      typeGuids.put("Name","AAMFEcF1AzV7PKuHmxwA");
      typeGuids.put("Content URL","AAMFEcIP+U+ML_gzH7AA");
      typeGuids.put("Description","AAMFEcK+kyOhG8GYvPgA");
      typeGuids.put("Page Type","AAMFEcNiRF2N5xhkYyAA");
      typeGuids.put("Word Ole Data","AAMFEcP2rmoCzqmzJxQA");
      typeGuids.put("Workflow Definition","AAMFEcSPdVbU8mGugOQA");
      typeGuids.put("Extension","AAMFEcUbJEERZTnwJzAA");
      typeGuids.put("Annotation","AAMFEcWy0xc4e3tcemQA");
      typeGuids.put("Static Id","AAMFEcY5DUbWyuIpZVwA");
      typeGuids.put("General String Data","AAMFEca+MB5ssx+Ax5wA");
      typeGuids.put("Native Content","AAMFEcdBJGBK9nr9TTQA");
      typeGuids.put("Word Template Content","AAMFEcfcGS2V3SqQN2wA");
      typeGuids.put("Whole Word Content","AAMFEchZmAzZo2tHjVAA");
      typeGuids.put("ats.Validation Required","AAMFEcjT0TwkD2R4w1QA");
      typeGuids.put("ats.Active","AAMFEclQOVmzkIvzyWwA");
      typeGuids.put("ats.Released","AAMFEcnMoUZMLA2zB1AA");
      typeGuids.put("ats.Next Version","AAMFEcpH8Xb72hsF5AwA");
      typeGuids.put("ats.Team Uses Versions","AAMFEcrHnzPxQ7w3ligA");
      typeGuids.put("ats.Blocking Review","AAMFEctKkjMRrIy1C7gA");
      typeGuids.put("ats.Actionable","AAMFEcvDtBiaJ3TMatAA");
      typeGuids.put("ats.Need By","AAMFEcxAGzHAKfDNAIwA");
      typeGuids.put("ats.Estimated Release Date","AAMFEcy6VB7Ble5SP1QA");
      typeGuids.put("ats.Estimated Completion Date","AAMFEc18k3Gh+GP7zqAA");
      typeGuids.put("ats.Release Date","AAMFEc3+cGcMDOCdmdAA");
      typeGuids.put("ats.Review Blocks","AAMFEc6G2A8jmRWJgagA");
      typeGuids.put("ats.Priority","AAMFEc8JzH1U6XGD59QA");
      typeGuids.put("ats.Change Type","AAMFEc+MwGHnPCv7HlgA");
      typeGuids.put("ats.User Community","AAMFEdAPtAq1IEwiCQAA");
      typeGuids.put("ats.Estimated Hours","AAMFEdCSqBh+cPyadiwA");
      typeGuids.put("ats.Weekly Benefit","AAMFEdEnEU9AecOHMOwA");
      typeGuids.put("ats.Man Days Needed","AAMFEdGlqFsZp22RMdAA");
      typeGuids.put("ats.Parent Branch Id","AAMFEdIjJ2za2fblEVgA");
      typeGuids.put("ats.Percent Rework","AAMFEdKfjl2TII9+tuwA");
      typeGuids.put("ats.State","AAMFEdMa3wzVvp60xLQA");
      typeGuids.put("ats.Current State","AAMFEdOWL3u6hmX2VbwA");
      typeGuids.put("ats.Problem","AAMFEdQUxRyevvTu+bwA");
      typeGuids.put("ats.Proposed Resolution","AAMFEdSSRDGgBQ5tctAA");
      typeGuids.put("ats.Resolution","AAMFEdUMfV1KdbQNaKwA");
      typeGuids.put("ats.Description","AAMFEdWJ_ChxX6+YKbwA");
      typeGuids.put("ats.Full Name","AAMFEdZI9XLT34cTonAA");
      typeGuids.put("ats.Actionable Item","AAMFEdbcR2zpGzFOLOQA");
      typeGuids.put("ats.Team Definition","AAMFEdd5bFEe18bd0lQA");
      typeGuids.put("ats.State Notes","AAMFEdiWPm7M_xV1EswA");
      typeGuids.put("ats.Related To State","AAMFEdkwHULOmHbMbGgA");
      typeGuids.put("ats.Work Package","AAMFEdpJqRp2wvA2qvAA");
      typeGuids.put("ats.Category","AAMFEdrYniOQYrYUKKQA");
      typeGuids.put("ats.Category2","AAMFEdthBkolbJKLXuAA");
      typeGuids.put("ats.Legacy PCR Id","AAMFEd3TakphMtQX1zgA");
      typeGuids.put("ats.Decision Review Options","AAMFEd5hRy1+SRJRqfwA");
      typeGuids.put("ats.Decision","AAMFEd7uDXcmqq_FrCQA");
      typeGuids.put("ats.Location","AAMFEeAW4QBlesdfacwA");
      typeGuids.put("ats.Role","AAMFEeCqMz0XCSBJ+IQA");
      typeGuids.put("lba.Type","AAMFEeG+ShfYf5zNVeQA");
      typeGuids.put("lba.Description","AAMFEeLnHkwt2f_9pygA");
      typeGuids.put("lba.Vendor","AAMFEeN9tk4GMWsqsIQA");
      typeGuids.put("lba.Kickoff","AAMFEgNy9iP4YBIhXGQA");
      typeGuids.put("lba.Control Source Location","AAMFEgRqrm16tAvWS4QA");
      typeGuids.put("lba.Help","AAMFEgToLQeFRKRKrKQA");
      typeGuids.put("Blam Workflow","AAMFDgPeIEJ7Ni1X1eAA");
      typeGuids.put("Folder","AAMFDg_wmiYHHY5swJwA");
      typeGuids.put("General Document","AAMFDhCjkTvP+VBpBCQA");
      typeGuids.put("Heading","AAMFDhEzni8FpFb5yHwA");
      typeGuids.put("Root Artifact","AAMFDhHDqlbzKcIxcsAA");
      typeGuids.put("Support Document","AAMFDhJOQTCu5A7LNQwA");
      typeGuids.put("Universal Group","AAMFDhLY2TnADPA_EQQA");
      typeGuids.put("Url","AAMFDhOL0VfVy56cqwgA");
      typeGuids.put("General Data","AAMFDhQXfyb2m+jCwlwA");
      typeGuids.put("Team Workflow","AAMFDhSiF2OD+wiUqugA");
      typeGuids.put("Team Definition","AAMFDhUrlytusKbaQGAA");
      typeGuids.put("Actionable Item","AAMFDhW2LmhtRFsVyzwA");
      typeGuids.put("Action","AAMFDhY_rns71KvX14QA");
      typeGuids.put("Task","AAMFDhbTAAB6h+06fuAA");
      typeGuids.put("Version","AAMFDhder0oETnv14xQA");
      typeGuids.put("Decision Review","AAMFDhfrdR7BGTL7H_wA");
      typeGuids.put("PeerToPeer Review","AAMFDhh_300dpgmNtRAA");
      typeGuids.put("MSA Tool","AAMFDhkWdxgkcbJw_8QA");
      typeGuids.put("User","AAMFDhmr+Dqqe5pn3kAA");
      typeGuids.put("Global Preferences","AAMFDho2kBqyoOZEw+gA");
      typeGuids.put("User Group","AAMFDhrEbXqZKPfWkwAA");
      typeGuids.put("XViewer Global Customization","AAMFDhtN7T4of30iYhAA");
      typeGuids.put("Renderer Template","AAMFDhvZnHKgSeFKMXgA");
      typeGuids.put("Work Rule Definition","AAMFDhxjHC2RUV2RkcQA");
      typeGuids.put("Work Page Definition","AAMFDhzuyizN4qu7tXgA");
      typeGuids.put("Work Flow Definition","AAMFDh16eQ1GIHPWlYQA");
      typeGuids.put("Work Widget Definition","AAMFDh4IVzqPgVTpLrwA");
      typeGuids.put("Artifact","AAMFDh6S7gRLupAMwywA");
      typeGuids.put("Hardware Requirement","AAMFDh8dhUflUdK9FdgA");
      typeGuids.put("Software Design","AAMFDh+nBRDS2smKPLAA");
      typeGuids.put("Software Requirement","AAMFDiAwhRFXwIyapJAA");
      typeGuids.put("Indirect Software Requirement","AAMFDiC7HRQMqr5S0QwA");
      typeGuids.put("System Design","AAMFDiFI+lLm46F3HdQA");
      typeGuids.put("Subsystem Design","AAMFDiHVwBo+Yx73BoQA");
      typeGuids.put("Subsystem Requirement","AAMFDiN9KiAkhuLqOhQA");
      typeGuids.put("Supporting Content","AAMFDiQI2QuheFY71jgA");
      typeGuids.put("System Requirement","AAMFDiSTcDGdUd9+tHAA");
      typeGuids.put("Test Procedure WML","AAMFDiUeCG3KWx5XqeQA");
      typeGuids.put("Test Procedure XL","AAMFDiWs_HdDJTbPPQgA");
      typeGuids.put("Template (WordML)","AAMFDiZFwxqmdpH5tAQA");
      typeGuids.put("Work Instruction","AAMFDibSikpSZq4r3SwA");
      typeGuids.put("Work Sheet","AAMFDidfUApCuZS5wzAA");
      typeGuids.put("Work Sheet (WordML)","AAMFDifp52TNlxboIdwA");
      typeGuids.put("Button Requirement","AAMFDih3xCIWj8yAOMgA");
      typeGuids.put("Test Case","AAMFDikEi0TGK27TKPgA");
      typeGuids.put("Narrative","AAMFDimRURwj2YP309gA");
      typeGuids.put("Lba Code Planned CM Build","AAMFDiob6GPfRFr_9cwA");
      typeGuids.put("Lba Code Engineering Build","AAMFDiq1x1h7CRW1iHAA");
      typeGuids.put("Lba CTE Team Workflow","AAMFDit0v3dmfKS2OVQA");
      typeGuids.put("Lba Tech Approach Team Workflow","AAMFDiwXWW07MRl9o_QA");
      typeGuids.put("Lba Program","AAMFDizBlmSoqhxqAuAA");
      typeGuids.put("Fault","AAMFDi1euhaYbUpxBxQA");
      typeGuids.put("wcafe","AAMFDi3731NsCHe7lWAA");
      typeGuids.put("Exceedance","AAMFDi6Tj1ZvsKABRcAA");
      typeGuids.put("WCA","AAMFDi81EQNW6+sH5hQA");
      typeGuids.put("Warning","AAMFDi_5fmAVoLbXBYwA");
      typeGuids.put("Caution","AAMFDjChjTAhsnbGEOgA");
      typeGuids.put("Advisory","AAMFDjFVnGH+ysVi+0gA");
      typeGuids.put("WCAFE Enum Generation Operation","AAMFDjH6ZC1kTasWV0QA");
      typeGuids.put("Exceedance Enum Generation Operation","AAMFDjKIQk46G7Unb_AA");
      typeGuids.put("Fault Enum Generation Operation","AAMFDjMiIDk7YkNMBXAA");
      typeGuids.put("WCA Enum Generation Operation","AAMFDjOyLGkbIwnuPdgA");
      typeGuids.put("UIG Artifact","AAMFDjQ+8jKGk9ck42AA");
      typeGuids.put("Stand Alone Local Data","AAMFDjTM0EmATq+dvjAA");
      typeGuids.put("Lba Code Team Workflow","AAMFDjVarXvBOCuWnUgA");
      typeGuids.put("Lba Test Team Workflow","AAMFDjXmXAh55SM+J6wA");
      typeGuids.put("Lba Req Team Workflow","AAMFDjZ1UVAQTXHk2GgA");
      typeGuids.put("Lba SW Design Team Workflow","AAMFDjcBAHlZLImIZqgA");
      typeGuids.put("Test Run Disposition","AAMFDjeNxhi0KmXZcKQA");
      typeGuids.put("Interface Requirement","AAMFDjgcukv7xEsPf2QA");
      typeGuids.put("System Function","AAMFDjisx2s6BUTDo3wA");
      typeGuids.put("Subsystem Function","AAMFDjk6pAAd3tpGEqwA");
      typeGuids.put("Test Information Sheet","AAMFDjnM3wQxCjwatKAA");
      typeGuids.put("Test Run","AAMFDjqDHWo+orlSpaQA");
      typeGuids.put("Test Procedure","AAMFDjsjiGhoWpqM4PQA");
      typeGuids.put("Checklist","AAMFDjvBxHvMn_Re1RQA");
      typeGuids.put("Checklist (WordML)","AAMFDjxq6Wt28UesPFAA");
      typeGuids.put("Guideline","AAMFDj0G9lWE4GjXpKgA");
      typeGuids.put("How To","AAMFDj2mSlskAziYXnQA");
      typeGuids.put("Roadmap","AAMFDj4_EVrNv4t3otgA");
      typeGuids.put("Template","AAMFDj7nH2PWF7q9i+AA");
      typeGuids.put("Test Support","AAMFDj+FW0f_Ut72ocQA");
      typeGuids.put("Lba Deliverable Team Workflow","AAMFDkB9EywYs81QTuQA");
      typeGuids.put("Code Unit","AAMFDkEh216dzK1mTZgA");
      typeGuids.put("Component","AAMFDkG6omAsD6dXPYgA");
      typeGuids.put("Spreadsheet","AAMFDkJTaUYm5ACe8QAA");
      typeGuids.put("Safety Assessment","AAMFDkLwjkgP8iAj8KAA");
   }

   @Override
   public ChangeSet computeChanges(CharSequence seq) {
      ChangeSet changeSet = new ChangeSet(seq);

      Matcher matcher = classDeclarationP.matcher(seq);
      while (matcher.find()) {
         setRuleWasApplicable(true);
         String typeName = matcher.group(1);
         String typeGuid = typeGuids.get(typeName);
         if (typeGuid == null) {
            if (!typeName.contains(".enum") && !typeName.contains("demo") && !typeName.contains("Demo")) {
               System.out.println(String.format("%s => %s", typeName, typeGuid));
            }
         } else {
            String ins = String.format("typeGuid \"%s\"\r\n\t", typeGuid);
            changeSet.insertBefore(matcher.end(), ins);
         }
      }

      return changeSet;
   }
}