pipeline {
  agent {
    kubernetes {
      label 'my-agent-pod'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: timbru31/node-chrome:14-alpine
    command:
    - cat
    tty: true
"""
    }
  }
  stages {
      
    
  
    stage('Run node') {
          
      steps {
          
        container('node') {
            
          sh 'node -v'
          
        }
       
      }
    }
  }
}
