java_library(
     name = "org.eclipse.osee.ats.core.demo",
     srcs = glob(["**/*.java"]),
     deps = ["//org.eclipse.osee.ats.api","//org.eclipse.osee.ats.core","//org.eclipse.osee.framework.core.packages", "//org.eclipse.framework.jdk.core"],
)
