java_test(
    name = "LdapAuthenticationTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.authentication.ldap","@maven//:org_mockito_mockito_core",
            "//org.eclipse.osee.authentication.admin"]
)
