java_test(
    name = "LdapAuthenticationTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.authentication.ldap:authentication_ldap","@maven//:org_mockito_mockito_core",
            "//:authentication_admin"]
)
