package(default_visibility = ["//visibility:public"])

alias(
   name = "account_rest_client",
   actual = "//org.eclipse.osee.account.rest.client:account_rest_client"
)


alias(
   name = "account_admin",
   actual = "//org.eclipse.osee.account.admin:account_admin"
)

alias(
   name = "account_rest",
   actual = "//org.eclipse.osee.account.rest:account_rest"
)

alias(
   name = "account_rest_model",
   actual = "//org.eclipse.osee.account.rest.model:account_rest_model"
)

alias(
   name = "activity",
   actual = "//org.eclipse.osee.activity:activity"
)

alias(
   name = "activity_api",
   actual = "//org.eclipse.osee.activity.api:activity_api"
)

alias(
   name = "app",
   actual = "//org.eclipse.osee.app:app"
)

alias(
   name = "ats_api",
   actual = "//org.eclipse.osee.ats.api:ats_api"
)

alias(
   name = "ats_core",
   actual = "//org.eclipse.osee.ats.core:ats_core"
)

alias(
   name = "ats_rest",
   actual = "//org.eclipse.osee.ats.rest:ats_rest"
)

alias(
   name = "authentication_admin", 
   actual = "//org.eclipse.osee.authentication.admin:authentication_admin"
)

alias(
   name = "cache_admin", 
   actual = "//org.eclipse.osee.cache.admin:cache_admin"
)

alias(
   name = "console_admin", 
   actual = "//org.eclipse.osee.console.admin:console_admin"
)

alias(
   name = "define",
   actual = "//org.eclipse.osee.define:define"
)

alias(
   name = "define_api",
   actual = "//org.eclipse.osee.define.api:define_api"
)

alias(
   name = "define_ide",
   actual = "//org.eclipse.osee.define.ide:define_ide"
)

alias(
   name = "framework_core_model",
   actual = "//org.eclipse.osee.framework.core.model:framework_core_model"
)

alias(
   name = "framework_core_client",
   actual = "//org.eclipse.osee.framework.core.client:framework_core_client"
)

alias(
   name = "framework_core_server",
   actual = "//org.eclipse.osee.framework.core.server:framework_core_server"
)

alias(
   name = "framework_messaging",
   actual = "//org.eclipse.osee.framework.messaging:framework_messaging"
)

alias(
   name = "framework_help_ui",
   actual = "//org.eclipse.osee.framework.help.ui:framework_help_ui"
)

alias(
   name = "framework_messaging_event_res",
   actual = "//org.eclipse.osee.framework.messaging.event.res:framework_messaging_event_res"
)

alias(
   name = "framework_plugin_core",
   actual = "//org.eclipse.osee.framework.plugin.core:framework_plugin_core"
)

alias(
   name = "framework_skynet_core",
   actual = "//org.eclipse.osee.framework.skynet.core:framework_skynet_core"
)

alias(
   name = "framework_resource_management",
   actual = "//org.eclipse.osee.framework.resource.management:framework_resource_management"
)

alias(
   name = "framework_server_ide",
   actual = "//org.eclipse.osee.framework.server.ide:framework_server_ide"
)

alias(
   name = "framework_server_ide_api",
   actual = "//org.eclipse.osee.framework.server.ide.api:framework_server_ide_api"
)

alias(
   name = "framework_ui_swt",
   actual = "//org.eclipse.osee.framework.ui.swt:framework_ui_swt"
)

alias(
   name = "framework_ui_plugin",
   actual = "//org.eclipse.osee.framework.ui.plugin:framework_ui_plugin"
)

alias(
   name = "framework_ui_skynet",
   actual = "//org.eclipse.osee.framework.ui.skynet:framework_ui_skynet"
)

alias(
   name = "framework_ui_ws",
   actual = "//org.eclipse.osee.framework.ui.ws:framework_ui_ws"
)

alias(
   name = "jaxrs",
   actual = "//org.eclipse.osee.jaxrs:jaxrs"
)

alias(
   name = "jaxrs_server",
   actual = "//org.eclipse.osee.jaxrs.server:jaxrs_server"
)

alias(
   name = "jdbc",
   actual = "//org.eclipse.osee.jdbc:jdbc"
)

alias(
    name = "orcs",
    actual = "//org.eclipse.osee.orcs:orcs",
)

alias(
    name = "orcs_core",
    actual = "//org.eclipse.osee.orcs.core:orcs_core",
)

alias(
    name = "orcs_rest",
    actual = "//org.eclipse.osee.orcs.rest:orcs_rest",
)

alias(
    name = "orcs_rest_model",
    actual = "//org.eclipse.osee.orcs.rest.model:orcs_rest_model",
)

alias(
    name = "ote_define",
    actual = "//org.eclipse.osee.ote.define:ote_define",
)

alias(
    name = "ote_ui_define",
    actual = "//org.eclipse.osee.ote.ui.define:ote_ui_define",
)

alias(
    name = "template_engine",
    actual = "//org.eclipse.osee.template.engine:template_engine"
)
