package(default_visibility = ["//visibility:public"])

test_suite(
    name = "server_tests",
    tests = ["//org.eclipse.osee.framework.jdk.core.test:JdkCoreTestSuite",
	     "//org.eclipse.osee.account.admin.test:AccountAdmin_JUnit_TestSuite",
	     "//org.eclipse.osee.account.rest.test:AccountRestTestSuite",
	     "//org.eclipse.osee.ats.core.test:AllAtsCoreTestSuite",
	     "//org.eclipse.osee.ats.rest.test:AtsServer_JUnit_TestSuite",
	     "//org.eclipse.osee.authentication.admin.test:AuthAdminTestSuite",
	     "//org.eclipse.osee.authentication.ldap.test:LdapAuthenticationTestSuite",
	     "//org.eclipse.osee.authorization.admin.test:AuthAdminTestSuite",
	     "//org.eclipse.osee.cache.admin.test:CacheAdminTestSuite",
	     "//org.eclipse.osee.config.admin.test:ConfigAdminTestSuite",
	     "//org.eclipse.osee.console.admin.test:AllConsoleAdminTestSuite",
	     "//org.eclipse.osee.define.rest.test:OseeDefineTestSuite",
	     "//org.eclipse.osee.disposition.rest.test:Disposition_JUnit_TestSuite",
	     "//org.eclipse.osee.framework.core.model.test:AllCoreModelTestSuite",
	     "//org.eclipse.osee.framework.core.server.test:CoreServerTestSuite",
	     "//org.eclipse.osee.framework.help.ui.test:HelpUiTestSuite",
	     "//org.eclipse.osee.framework.core.test:FrameworkCoreTestSuite",
	     "//org.eclipse.osee.framework.logging.test:AllLoggingTestSuite",
	     "//org.eclipse.osee.framework.messaging.event.res.test:AllEventResTestSuite",
	     "//org.eclipse.osee.framework.messaging.test:AllMessagingIntegrationTestSuite",
	     "//org.eclipse.osee.framework.resource.management.test:ResourceManagementTestSuite",
	     "//org.eclipse.osee.jaxrs.server.test:JaxRsServerTestSuite",
	     "//org.eclipse.osee.jdbc.test:AllJdbcTestSuite",
	     "//org.eclipse.osee.orcs.core.test:OrcsCoreTestSuite", 
	     "//org.eclipse.osee.orcs.db.test:OrcsDb_JUnit_TestSuite",
	     "//org.eclipse.osee.orcs.rest.test:OrcsRest_JUnit_TestSuite",
	     "//org.eclipse.osee.template.engine.test:OseeTemplateEngineTestSuite",
	    ],
    

)

test_suite(
    name = "client_tests",
    tests = ["//org.eclipse.osee.ats.ide.help.ui.test:AtsHelpUiTestSuite",
	     "//org.eclipse.osee.framework.skynet.core.test:AllSkynetCoreJunitTestSuite",
    	     "//org.eclipse.osee.define.ide.test:AllDefineJunitTestSuite",
    	     "//org.eclipse.osee.framework.ui.skynet.test:AllUiSkynetJunitTestSuite"]
)

alias(
   name = "accessor",
   actual = "//org.eclipse.osee.accessor:accessor"
)

alias(
   name = "account_rest_client",
   actual = "//org.eclipse.osee.account.rest.client:account_rest_client"
)


alias(
   name = "account_admin",
   actual = "//org.eclipse.osee.account.admin:account_admin"
)

alias(
   name = "account_rest",
   actual = "//org.eclipse.osee.account.rest:account_rest"
)

alias(
   name = "account_rest_model",
   actual = "//org.eclipse.osee.account.rest.model:account_rest_model"
)

alias(
   name = "activity",
   actual = "//org.eclipse.osee.activity"
)

alias(
   name = "activity_api",
   actual = "//org.eclipse.osee.activity.api"
)

alias(
   name = "app",
   actual = "//org.eclipse.osee.app"
)

alias(
   name = "ats_api",
   actual = "//org.eclipse.osee.ats.api"
)

alias(
   name = "ats_ide",
   actual = "//org.eclipse.osee.ats.ide"
)

alias(
   name = "ats_core",
   actual = "//org.eclipse.osee.ats.core"
)

alias(
   name = "ats_rest",
   actual = "//org.eclipse.osee.ats.rest"
)

alias(
   name = "authentication_admin", 
   actual = "//org.eclipse.osee.authentication.admin"
)

alias(
   name = "authentication_ldap", 
   actual = "//org.eclipse.osee.authentication.ldap"
)

alias(
   name = "authorization_admin", 
   actual = "//org.eclipse.osee.authorization.admin"
)

alias(
   name = "cache_admin", 
   actual = "//org.eclipse.osee.cache.admin"
)

alias(
   name = "config_admin", 
   actual = "//org.eclipse.osee.config.admin"
)

alias(
   name = "console_admin", 
   actual = "//org.eclipse.osee.console.admin"
)

alias(
   name = "define",
   actual = "//org.eclipse.osee.define"
)

alias(
   name = "define_api",
   actual = "//org.eclipse.osee.define.api"
)

alias(
   name = "define_ide",
   actual = "//org.eclipse.osee.define.ide"
)

alias(
   name = "disposition_rest",
   actual = "//org.eclipse.osee.disposition.rest"
)

alias(
   name = "disposition_rest_model",
   actual = "//org.eclipse.osee.disposition.rest.model"
)

alias(
   name = "framework_core_model",
   actual = "//org.eclipse.osee.framework.core.model"
)

alias(
   name = "framework_core_client",
   actual = "//org.eclipse.osee.framework.core.client"
)

alias(
   name = "framework_core_server",
   actual = "//org.eclipse.osee.framework.core.server"
)

alias(
   name = "framework_jdk_core",
   actual = "//org.eclipse.osee.framework.jdk.core"
)

alias(
   name = "framework_jdk_core_test",
   actual = "//org.eclipse.osee.framework.jdk.core.test"
)

alias(
   name = "framework_messaging",
   actual = "//org.eclipse.osee.framework.messaging"
)

alias(
   name = "framework_help_ui",
   actual = "//org.eclipse.osee.framework.help.ui"
)

alias(
   name = "framework_messaging_event_res",
   actual = "//org.eclipse.osee.framework.messaging.event.res"
)

alias(
   name = "framework_plugin_core",
   actual = "//org.eclipse.osee.framework.plugin.core"
)

alias(
   name = "framework_skynet_core",
   actual = "//org.eclipse.osee.framework.skynet.core"
)

alias(
   name = "framework_resource_management",
   actual = "//org.eclipse.osee.framework.resource.management"
)

alias(
   name = "framework_server_ide",
   actual = "//org.eclipse.osee.framework.server.ide"
)

alias(
   name = "framework_server_ide_api",
   actual = "//org.eclipse.osee.framework.server.ide.api"
)

alias(
   name = "framework_ui_swt",
   actual = "//org.eclipse.osee.framework.ui.swt"
)

alias(
   name = "framework_ui_plugin",
   actual = "//org.eclipse.osee.framework.ui.plugin"
)

alias(
   name = "framework_ui_skynet",
   actual = "//org.eclipse.osee.framework.ui.skynet"
)

alias(
   name = "framework_ui_ws",
   actual = "//org.eclipse.osee.framework.ui.ws"
)

alias(
   name = "jaxrs",
   actual = "//org.eclipse.osee.jaxrs"
)

alias(
   name = "jaxrs_server",
   actual = "//org.eclipse.osee.jaxrs.server"
)

alias(
   name = "jdbc",
   actual = "//org.eclipse.osee.jdbc"
)


alias(
   name = "logger",
   actual = "//org.eclipse.osee.logger"
)

alias(
   name = "logger_slf4j",
   actual = "//org.eclipse.osee.logger.slf4j"
)

alias(
   name = "mim",
   actual = "//org.eclipse.osee.mim"
)

alias(
    name = "orcs",
    actual = "//org.eclipse.osee.orcs",
)

alias(
    name = "orcs_core",
    actual = "//org.eclipse.osee.orcs.core",
)

alias(
    name = "orcs_rest",
    actual = "//org.eclipse.osee.orcs.rest",
)

alias(
    name = "orcs_rest_model",
    actual = "//org.eclipse.osee.orcs.rest.model",
)

alias(
    name = "ote_define",
    actual = "//org.eclipse.osee.ote.define",
)

alias(
    name = "ote_ui_define",
    actual = "//org.eclipse.osee.ote.ui.define",
)

alias(
    name = "template_engine",
    actual = "//org.eclipse.osee.template.engine"
)

alias(
    name = "vcast",
    actual = "//org.eclipse.osee.vcast"
)
