load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")



http_archive(
    name = "rules_pkg",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.9.1/rules_pkg-0.9.1.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.9.1/rules_pkg-0.9.1.tar.gz",
    ],
    sha256 = "8f9ee2dc10c1ae514ee599a8b42ed99fa262b757058f65ad3c384289ff70c4b8",
)


load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()

RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

local_repository(
    name = "ext_jars",
    path = "ext.jars"
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

load("@rules_jvm_external//private/rules:jvm_import.bzl", "jvm_import")


rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")

load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
    	"org.apache.commons:commons-compress:1.26.0",
        "com.fasterxml.jackson.core:jackson-core:2.10.3",
        "com.fasterxml.jackson.core:jackson-databind:2.10.3",
        "com.fasterxml.jackson.core:jackson-annotations:2.10.3",
        "com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.12.1",
	"com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.12.1",
	"com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.14.0",
	"com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.0",
	"org.yaml:snakeyaml:1.33",
	"com.vladsch.flexmark:flexmark:0.64.8",
	"com.vladsch.flexmark:flexmark-ext-tables:0.64.8",
	"com.vladsch.flexmark:flexmark-util-data:0.64.8",
	"com.vladsch.flexmark:flexmark-util-ast:0.64.8",
	"com.vladsch.flexmark:flexmark-ext-gfm-tasklist:0.64.8",
	"com.vladsch.flexmark:flexmark-ext-toc:0.64.8",
        "com.vladsch.flexmark:flexmark-ext-autolink:0.64.8",
	"commons-codec:commons-codec:1.6",
	"io.github.classgraph:classgraph:4.8.149",
	"org.apache.sling:org.apache.sling.testing.osgi-mock.junit5:3.3.8",
	"org.apache.sling:org.apache.sling.testing.osgi-mock.core:3.3.8",
        "org.eclipse.jdt:org.eclipse.jdt.core:3.22.0",
        "org.eclipse.jdt:org.eclipse.jdt.annotation:2.2.600",
        "javax.ws.rs:javax.ws.rs-api:2.1",
	"jakarta.ws.rs:jakarta.ws.rs-api:2.1.6",
	"jakarta.activation:jakarta.activation-api:2.1.0",
        "javax.activation:activation:1.1",
        "jakarta.xml.bind:jakarta.xml.bind-api:3.0.1",
	"com.googlecode.com.googlecode.javaewah.JavaEWAH:com.googlecode.javaewah.JavaEWAH:1.1.7",
        "org.slf4j:slf4j-api:1.7.30",
        "javax.mail:mail:1.4.1",
        "org.antlr:antlr-runtime:3.2",
        "com.google.guava:guava:30.1-jre",
	"org.apache.poi:poi:4.1.1",
        "org.apache.poi:poi-ooxml:4.1.1",
	"org.apache.poi:poi-ooxml-schemas:4.1.1",
        "org.mockito:mockito-core:2.23.0",
       	"org.hamcrest:hamcrest-core:1.3",
        "org.junit:junit5-api:5.0.0-ALPHA",
	"org.apache.felix:org.apache.felix.gogo.runtime:1.1.0",
	"org.apache.felix:org.apache.felix.gogo.command:1.0.2",
	"org.apache.felix:org.apache.felix.gogo.shell:1.1.0",
	"org.apache.felix:org.apache.felix.scr:2.1.16",
        "org.apache.cxf:cxf-core:3.3.12",
	"org.apache.cxf:cxf-rt-frontend-jaxrs:3.3.12",
	"org.apache.cxf:cxf-rt-rs-client:3.3.12",
	"org.apache.cxf:cxf-rt-rs-security-oauth:3.3.12",
 	"org.apache.cxf:cxf-rt-rs-security-oauth2:3.3.12",
	"org.apache.cxf:cxf-rt-security:3.3.12",
	"org.apache.cxf:cxf-rt-transports-http:3.3.12",
	"org.apache.cxf:cxf-rt-rs-service-description:3.3.12",
	"org.apache.cxf:cxf-rt-rs-security-jose:3.3.12",
	"org.apache.cxf:cxf-rt-rs-security-jose-jaxrs:3.3.12",
	"org.apache.cxf:cxf-tools-wadlto-jaxrs:2.6.17",
	"org.hsqldb:hsqldb:2.6.1",
	"com.google.protobuf:protobuf-java:4.26.1",
	"javax.servlet:javax.servlet-api:3.1.0",
	"io.swagger.core.v3:swagger-core:2.2.7",
        "io.swagger.core.v3:swagger-jaxrs2:2.2.7",
        "io.swagger.core.v3:swagger-models:2.2.7",
	"io.swagger.core.v3:swagger-annotations:2.2.7",
	"io.swagger.core.v3:swagger-integration:2.2.7",
        "org.eclipse.jgit:org.eclipse.jgit:5.8.0.202006091008-r",
        "org.jsoup:jsoup:1.8.3",
        "com.jcraft:jsch:0.1.55",
        "org.apache.commons:commons-math3:3.6.1",
        "org.apache.geronimo.specs:geronimo-jms_1.1_spec:1.1",
        "org.apache.activemq:activemq-all:5.14.0",
	"org.glassfish.jaxb:jaxb-runtime:3.0.1",
	"org.apache.commons:commons-lang3:3.12.0",
	"org.apache.commons:commons-collections4:4.4",
	"net.oauth.core:oauth:20090531",
	"org.apache.ws.xmlschema:xmlschema-core:2.2.5",
	"org.eclipse.jetty:jetty-http:9.4.51.v20230217",
	"org.eclipse.jetty:jetty-server:9.4.51.v20230217",
	"org.eclipse.jetty:jetty-io:9.4.51.v20230217",
	"org.eclipse.jetty:jetty-security:9.4.51.v20230217",
	"org.eclipse.jetty:jetty-util:9.4.51.v20230217",
	"org.eclipse.jetty:jetty-util-ajax:9.4.51.v20230217",
 	"org.eclipse.jetty:jetty-servlet:9.4.51.v20230217",
 	"com.intellij:annotations:12.0"
	],

    repositories = [
        # Private repositories are supported through HTTP Basic auth
        "https://repo1.maven.org/maven2",
    ]
    ,
)


http_jar(
      name = "eclipse_core_net",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.net_1.3.900.v20200428-1255.jar&r=1",
      downloaded_file_name = "org.eclipse.core.net_1.3.900.v20200428-1255.jar"
)

http_jar(
      name = "equinox_security",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.security_1.3.500.v20200114-1637.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.security_1.3.500.v20200114-1637.jar"
)

http_jar(
      name = "jcraft",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/com.jcraft.jsch_0.1.55.v20190404-1902.jar&r=1",
      downloaded_file_name = "com.jcraft.jsch_0.1.55.v20190404-1902.jar"
)

http_jar(
      name = "javax_annotation",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/javax.annotation_1.3.5.v20200504-1837.jar&r=1",
      downloaded_file_name = "javax.annotation_1.3.5.v20200504-1837.jar"
)

http_jar(
      name = "javax_activation",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/javax.activation_1.1.0.v201211130549.jar&r=1",
      downloaded_file_name = "javax.activation_1.1.0.v201211130549.jar"
)

http_jar(
      name = "javax_transaction",
      url = "https://download.eclipse.org/tools/orbit/downloads/drops/R20181102183712/repository/plugins/javax.transaction_1.1.1.v201105210645.jar",
      downloaded_file_name = "javax.transaction_1.1.1.v201105210645.jar"
)

http_jar(
      name = "javax_ws_rs",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/javax.ws.rs_2.1.6.v20200505-2127.jar&r=1",
      downloaded_file_name = "javax.ws.rs_2.1.6.v20200505-2127.jar"
)

http_jar(
      name = "javax_xml",
      url = "https://www.eclipse.org/downloads/download.php?file=/tools/orbit/downloads/drops/R20230531010532/repository/plugins/javax.xml_1.4.1.v20220503-2331.jar",
      downloaded_file_name = "javax.xml_1.4.1.v20220503-2331.jar"
)

http_jar(
      name = "javax_xml_bind",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/javax.xml.bind_2.2.0.v201105210648.jar&r=1",
      downloaded_file_name = "javax.xml.bind_2.2.0.v201105210648.jar"
)

http_jar(
      name = "javax_xml_ws",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/javax.xml.ws_2.1.0.v200902101523.jar&r=1",
      downloaded_file_name = "javax.xml.ws.jar"
)

http_jar(
      name = "javax_xml_soap",
      url = "https://download.eclipse.org/tools/orbit/downloads/drops/R20181102183712/repository/plugins/javax.xml.soap_1.3.0.v201105210645.jar",
      downloaded_file_name = "javax.xml.soap_1.3.0.v201105210645.jar"
)

http_jar(
      name = "javax_servlet",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/javax.servlet_3.1.0.v201410161800.jar&r=1",
      downloaded_file_name = "javax.servlet_3.1.0.v201410161800.jar"
)

http_jar(
      name = "javax_validation",
      url = "https://www.eclipse.org/downloads/download.php?file=/tools/orbit/downloads/drops/R20230531010532/repository/plugins/javax.validation_1.1.0.v20221112-0806.jar",
      downloaded_file_name = "javax.validation_1.1.0.v20221112-0806.jar"
)

http_jar(
      name = "javax_mail",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/javax.mail_1.4.0.v201005080615.jar&r=1",
      downloaded_file_name = "javax.mail_1.4.0.v201005080615.jar"
)

http_jar(
      name = "eclipse_draw2d",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.draw2d_3.10.100.201606061308.jar&r=1",
      downloaded_file_name = "org.eclipse.draw2d_3.10.100.201606061308.jar"
)

http_jar(
      name = "eclipse_core_runtime",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.runtime_3.18.0.v20200506-2143.jar&r=1",
      downloaded_file_name = "org.eclipse.core.runtime_3.18.0.v20200506-2143.jar"
)

http_jar(
      name = "eclipse_gef",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.gef_3.11.0.201606061308.jar&r=1",
      downloaded_file_name = "org.eclipse.gef_3.11.0.201606061308.jar"
)

http_jar(
      name = "eclipse_core_jobs",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.jobs_3.10.800.v20200421-0950.jar&r=1",
      downloaded_file_name = "org.eclipse.core.jobs_3.10.800.v20200421-0950.jar"
)

http_jar(
      name = "eclipse_graphiti_ui",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.graphiti.ui_0.17.0.202005151449.jar&r=1",
      downloaded_file_name = "org.eclipse.graphiti.ui_0.17.0.202005151449.jar"
)

http_jar(
      name = "eclipse_graphiti",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.graphiti_0.17.0.202005151449.jar&r=1",
      downloaded_file_name = "org.eclipse.graphiti_0.17.0.202005151449.jar"
)

http_jar(
      name = "eclipse_core_resources",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.resources_3.13.700.v20200209-1624.jar&r=1",
      downloaded_file_name = "org.eclipse.core.resources_3.13.700.v20200209-1624.jar"
)

http_jar(
      name = "eclipse_core_commands",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.commands_3.9.700.v20191217-1850.jar&r=1",
      downloaded_file_name = "org.eclipse.core.commands_3.9.700.v20191217-1850.jar"
)

http_jar(
      name = "eclipse_core_filesystem",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.filesystem_1.7.700.v20200110-1734.jar&r=1",
      downloaded_file_name = "org.eclipse.core.filesystem_1.7.700.v20200110-1734.jar"
)

http_jar(
      name = "eclipse_core_filebuffers",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.filebuffers_3.6.1000.v20200409-1035.jar&r=1",
      downloaded_file_name = "org.eclipse.core.filebuffers_3.6.1000.v20200409-1035.jar"
)

http_jar(
      name = "eclipse_core_expressions",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.expressions_3.6.800.v20200319-0911.jar&r=1",
      downloaded_file_name = "org.eclipse.core.expressions_3.6.800.v20200319-0911.jar"
)

http_jar(
      name = "eclipse_core_contenttype",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.contenttype_3.7.700.v20200517-1644.jar&r=1",
      downloaded_file_name = "org.eclipse.core.contenttype_3.7.700.v20200517-1644.jar"
)

http_jar(
      name = "eclipse_core_variables",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.core.variables_3.4.800.v20200120-1101.jar&r=1",
      downloaded_file_name = "org.eclipse.core.variables_3.4.800.v20200120-1101.jar"
)

http_jar(
      name = "eclipse_debug_core",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.debug.core_3.15.100.v20200514-0816.jar&r=1",
      downloaded_file_name = "org.eclipse.debug.core_3.15.100.v20200514-0816.jar"
)

http_jar(
      name = "eclipse_text",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.text_3.10.200.v20200428-0633.jar&r=1",
      downloaded_file_name = "org.eclipse.text_3.10.200.v20200428-0633.jar"
)

http_jar(
      name = "eclipse_equinox_common",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.common_3.12.0.v20200504-1602.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.common_3.12.0.v20200504-1602.jar"
)

http_jar(
      name = "eclipse_equinox_registry",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.registry_3.8.800.v20200406-0956.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.registry_3.8.800.v20200406-0956.jar"
)

http_jar(
      name = "eclipse_equinox_preferences",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.preferences_3.8.0.v20200422-1833.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.preferences_3.8.0.v20200422-1833.jar"
)

http_jar(
      name = "eclipse_equinox_app",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.app_1.4.500.v20200422-1833.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.app_1.4.500.v20200422-1833.jar"
)

http_jar(
      name = "eclipse_equinox_bidi",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.bidi_1.2.300.v20191213-1901.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.bidi_1.2.300.v20191213-1901.jar"
)

http_jar(
      name = "eclipse_equinox_console",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.console_1.4.100.v20200525-1407.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.console_1.4.100.v20200525-1407.jar"
)
http_jar(
      name = "eclipse_equinox_launcher",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar"
)

http_jar(
      name = "eclipse_equinox_http_jetty",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.http.jetty_3.7.400.v20200123-1333.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.http.jetty_3.7.400.v20200123-1333.jar"
)

http_jar(
      name = "eclipse_equinox_http_servlet",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.http.servlet_1.6.500.v20200511-1535.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.http.servlet_1.6.500.v20200511-1535.jar"
)

http_jar(
      name = "eclipse_equinox_metatype",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.metatype_1.5.300.v20200422-1833.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.metatype_1.5.300.v20200422-1833.jar"
)

http_jar(
      name = "eclipse_equinox_event",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.event_1.5.400.v20200511-1702.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.event_1.5.400.v20200511-1702.jar"
)

http_jar(
      name = "eclipse_equinox_ds",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.apache.felix.scr_1.6.200.v20200422-1833.jar&r=1",
      downloaded_file_name = "org.apache.felix.scr_1.6.200.v20200422-1833.jar"
)

http_jar(
      name = "eclipse_equinox_cm",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.equinox.cm_1.4.400.v20200422-1833.jar&r=1",
      downloaded_file_name = "org.eclipse.equinox.cm_1.4.400.v20200422-1833.jar"
)

http_jar(
      name = "eclipse_osgi",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.osgi_3.18.0.v20220516-2155.jar&r=1",
      downloaded_file_name = "org.eclipse.osgi_3.18.0.v20220516-2155.jar"
)

http_jar(
      name = "eclipse_osgi_services",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.osgi.services_3.10.200.v20210723-0643.jar&r=1",
      downloaded_file_name = "org.eclipse.osgi.services_3.10.200.v20210723-0643.jar"
)

http_jar(
      name = "eclipse_osgi_util",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.osgi.util_3.5.300.v20190708-1141.jar&r=1",
      downloaded_file_name = "org.eclipse.osgi.util_3.5.300.v20190708-1141.jar"
)

http_jar(
      name = "eclipse_zest_core",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.zest.core_1.5.300.201606061308.jar&r=1",
      downloaded_file_name = "org.eclipse.zest.core_1.5.300.201606061308.jar"
)

http_jar(
      name = "eclipse_zest_layouts",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.zest.layouts_1.1.300.201606061308.jar&r=1",
      downloaded_file_name = "org.eclipse.zest.layouts_1.1.300.201606061308.jar"
)

http_jar(
      name = "eclipse_search",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.search_3.11.1000.v20200410-1852.jar&r=1",
      downloaded_file_name = "org.eclipse.search_3.11.1000.v20200410-1852.jar"
)

http_jar(
      name = "eclipse_compare",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.compare_3.7.1000.v20200511-1203.jar&r=1",
      downloaded_file_name = "org.eclipse.compare_3.7.1000.v20200511-1203.jar"
)

http_jar(
      name = "eclipse_emf_transaction",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.eclipse.emf.transaction_1.9.1.201805140824.jar&r=1",
      downloaded_file_name = "org.eclipse.emf.transaction_1.9.1.201805140824.jar"
)

http_jar(
      name = "apache_commons_codec",
      url = "https://www.eclipse.org/downloads/download.php?file=/tools/orbit/downloads/drops/R20230531010532/repository/plugins/org.apache.commons.codec_1.14.0.v20221112-0806.jar",
      downloaded_file_name = "org.apache.commons.codec_1.14.0.v20221112-0806.jar"
)

http_jar(
      name = "apache_xerces",
      url = "https://www.eclipse.org/downloads/download.php?file=/tools/orbit/downloads/drops/R20230531010532/repository/plugins/org.apache.xerces_2.12.2.v20220131-0835.jar",
      downloaded_file_name = "org.apache.xerces_2.12.2.v20220131-0835.jar"
)

http_jar(
      name = "apache_xml_resolver",
      url = "https://www.eclipse.org/downloads/download.php?file=/tools/orbit/downloads/drops/R20230531010532/repository/plugins/org.apache.xml.resolver_1.2.0.v20220715-1206.jar",
      downloaded_file_name = "org.apache.xml.resolver_1.2.0.v20220715-1206.jar"
)

http_jar(
      name = "antlr_runtime",
      url = "https://www.eclipse.org/downloads/download.php?file=/releases/2020-06/202006171000/plugins/org.antlr.runtime_3.2.0.v201101311130.jar&r=1",
      downloaded_file_name = "org.antlr.runtime_3.2.0.v201101311130.jar"
)

http_jar(
      name = "google_guava",
      url = "https://www.eclipse.org/downloads/download.php?file=/tools/orbit/downloads/drops/R20230531010532/repository/plugins/com.google.guava_30.1.0.v20221112-0806.jar",
      downloaded_file_name = "com.google.guava_30.1.0.v20221112-0806.jar"
)

http_jar(
      name = "slf4j_api",
      url = "https://www.eclipse.org/downloads/download.php?file=/tools/orbit/downloads/drops/R20230531010532/repository/plugins/org.slf4j.api_1.7.30.v20221112-0806.jar",
      downloaded_file_name = "org.slf4j.api_1.7.30.v20221112-0806.jar"
)

http_jar(
      name = "io.swagger.core.v3.swagger_core",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/io.swagger.core.v3.swagger-core_2.2.7.jar",
      downloaded_file_name = "io.swagger.core.v3.swagger-core_2.2.7.jar"
)

http_jar(
      name = "io.swagger.core.v3.swagger_annotations",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/io.swagger.core.v3.swagger-annotations_2.2.7.jar",
      downloaded_file_name = "io.swagger.core.v3.swagger-annotations_2.2.7.jar"
)

http_jar(
      name = "io.swagger.core.v3.swagger_integration",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/io.swagger.core.v3.swagger-integration_2.2.7.jar",
      downloaded_file_name = "io.swagger.core.v3.swagger-integration_2.2.7.jar"
)

http_jar(
      name = "io.swagger.core.v3.swagger_jaxrs2",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/io.swagger.core.v3.swagger-jaxrs2_2.2.7.jar",
      downloaded_file_name = "io.swagger.core.v3.swagger-jaxrs2_2.2.7.jar"
)

http_jar(
      name = "io.swagger.core.v3.swagger_models",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/io.swagger.core.v3.swagger-models_2.2.7.jar",
      downloaded_file_name = "io.swagger.core.v3.swagger-models_2.2.7.jar"
)

http_jar(
      name = "apache_poi",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/org.apache.poi_4.1.1.v20221112-0806.jar",
      downloaded_file_name = "org.apache.poi_4.1.1.v20221112-0806.jar"
)

http_jar(
      name = "apache_poi_ooxml",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/org.apache.poi.ooxml_4.1.1.v20221112-0806.jar",
      downloaded_file_name = "org.apache.poi.ooxml_4.1.1.v20221112-0806.jar"
)

http_jar(
      name = "apache_poi_ooxml.schemas",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/org.apache.poi.ooxml.schemas_4.1.1.v20221112-0806.jar",
      downloaded_file_name = "org.apache.poi.ooxml.schemas_4.1.1.v20221112-0806.jar"
)

http_jar(
      name = "com.vladsch.flexmark",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.ext-autolink",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.ext-autolink_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.ext-autolink_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.ext-gfm-tasklist",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.ext-gfm-tasklist_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.ext-gfm-tasklist_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.ext-gitlab",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.ext-gitlab_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.ext-gitlab_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.ext-tables",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.ext-tables_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.ext-tables_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.ext-toc",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.ext-toc_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.ext-toc_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-format",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-format_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-format_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-collection",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-collection_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-collection_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-misc",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-misc_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-misc_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-ast",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-ast_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-ast_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-sequence",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-sequence_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-sequence_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-data",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-data_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-data_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-visitor",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-visitor_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-visitor_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-html",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-html_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-html_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-dependency",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-dependency_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-dependency_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-builder",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-builder_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-builder_0.64.8.jar"
)

http_jar(
      name = "com.vladsch.flexmark.util-options",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/com.vladsch.flexmark.util-options_0.64.8.jar",
      downloaded_file_name = "com.vladsch.flexmark.util-options_0.64.8.jar"
)

http_jar(
      name = "org.nibor.autolink",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/org.nibor.autolink_0.6.0.jar",
      downloaded_file_name = "org.nibor.autolink_0.6.0.jar"
)

http_jar(
      name = "org.jetbrains.annotations",
      url = "https://ci.eclipse.org/osee/job/osee_nightly/lastSuccessfulBuild/artifact/org.eclipse.osee/plugins/org.eclipse.osee.server.p2/target/repository/plugins/org.jetbrains.annotations_24.0.1.jar",
      downloaded_file_name = "org.jetbrains.annotations_24.0.1.jar"
)



