-- OSEE_HTTP_SESSION_ID
CREATE TABLE OSEE_HTTP_SESSION_ID (
	ID VARCHAR(120) NOT NULL,
	CONSTRAINT OSEE_HTTP_SESSION_ID__ID PRIMARY KEY(ID)
);

-- OSEE_HTTP_SESSION
CREATE TABLE OSEE_HTTP_SESSION (
	CONTEXT_PATH VARCHAR(60),
	SESSION_ROW_ID VARCHAR(120) NOT NULL,
	LAST_SAVED_TIME ${db.bigint},
	ACCESS_TIME ${db.bigint},
	CREATED_ON ${db.bigint},
	EXPIRES_IN ${db.bigint},
	LAST_ACCESS_TIME ${db.bigint},
	ATTRIBUTES ${db.blob},
	SESSION_ID VARCHAR(120) NOT NULL,
	COOKIE_SET_ON ${db.bigint},
	LAST_NODE VARCHAR(60),
	VIRTUAL_HOST VARCHAR(60),
	CONSTRAINT OSEE_HTTP_SESSION__ID PRIMARY KEY(SESSION_ROW_ID)
);

CREATE INDEX OSEE_HTTP_SESSION__E_IDX ON OSEE_HTTP_SESSION(EXPIRES_IN);
CREATE INDEX OSEE_HTTP_SESSION__SC_IDX ON OSEE_HTTP_SESSION(SESSION_ID,CONTEXT_PATH);