
java_library(
    name = "org.eclipse.osee.framework.core.packages",
    exports = [
               "//org.eclipse.osee.framework.jdk.core",
               "//org.eclipse.osee.framework.core",
               "//org.eclipse.osee.framework.logging",
               "//org.eclipse.osee.logger"
              ],
    visibility = ["//visibility:public"]
)


