/*
* generated by Xtext
*/
package org.eclipse.osee.framework.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import org.eclipse.osee.framework.services.OseeTypesGrammarAccess;

public class OseeTypesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private OseeTypesGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		org.eclipse.osee.framework.parser.antlr.internal.InternalOseeTypesLexer lexer = new org.eclipse.osee.framework.parser.antlr.internal.InternalOseeTypesLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		org.eclipse.osee.framework.parser.antlr.internal.InternalOseeTypesParser parser = new org.eclipse.osee.framework.parser.antlr.internal.InternalOseeTypesParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "OseeTypeModel";
	}
	
	public OseeTypesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OseeTypesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
