/*********************************************************************
 * Copyright (c) 2021 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/
import {
  changeInstance,
  ignoreType,
  changeTypeNumber,
  changeTypeEnum,
  ModificationType,
} from 'src/app/types/change-report/change-report';

export const changeReportMock: changeInstance[] = [
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      typeId: 2834799904,
      notAttributeChange: true,
      notRelationChange: true,
      idIntValue: 111,
      idString: '111',
    },
    artId: '10',
    itemId: '1234',
    itemTypeId: '7890',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '-1',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '-1',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '-1',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '-1',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '-1',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '2',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201289',
    itemId: '10312',
    itemTypeId: '1152921504606847089',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20606',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="ABCkGXcC9BtOVW8ceggA,AAkKSN_MmEVt8yIw4sQA,ABEYW415xCGFe1Wi1NwA,ABIN5ZrPVFEVTDcmr9gA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20618',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="ABCkGXcC9BtOVW8ceggA,AAkKSN_MmEVt8yIw4sQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20636',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="ABCkGXcC9BtOVW8ceggA,AAkKSN_MmEVt8yIw4sQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20606',
      modType: ModificationType.MODIFIED,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20636',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="ABCkGXcC9BtOVW8ceggA,AAkKSN_MmEVt8yIw4sQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      notRelationChange: true,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '111',
      idIntValue: 111,
    },
    artId: '201298',
    itemId: '201298',
    itemTypeId: '126164394421696908',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20569',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20569',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '3298521940448053542',
        name: 'Config = Product C',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20569',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20569',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '3298521940448053542',
        name: 'Config = Product C',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201297',
    itemId: '10324',
    itemTypeId: '2455059983007225763',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20563',
      modType: ModificationType.NEW,
      value: '5',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20620',
      modType: ModificationType.MODIFIED,
      value: '10',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20563',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20620',
      modType: ModificationType.MODIFIED,
      value: '10',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      notRelationChange: true,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '111',
      idIntValue: 111,
    },
    artId: '201302',
    itemId: '201302',
    itemTypeId: '126164394421696908',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20602',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20602',
      modType: ModificationType.DELETED,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20602',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20602',
      modType: ModificationType.DELETED,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: true,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.RELATION_CHANGE,
      name: changeTypeEnum.RELATION_CHANGE,
      notRelationChange: false,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '333',
      idIntValue: 333,
    },
    artId: '201289',
    itemId: '5141',
    itemTypeId: {
      id: '2455059983007225780',
      name: 'Interface Message SubMessage Content',
      order: 'USER_DEFINED',
      ordered: true,
      multiplicity: 'MANY_TO_MANY',
      idString: '2455059983007225780',
      idIntValue: 225187764,
    },
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20592',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20592',
      modType: ModificationType.DELETED,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20592',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20592',
      modType: ModificationType.DELETED,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '201300',
    deleted: true,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201298',
    itemId: '10326',
    itemTypeId: '2455059983007225769',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20594',
      modType: ModificationType.MODIFIED,
      value: '68',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20619',
      modType: ModificationType.MODIFIED,
      value: '67',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20594',
      modType: ModificationType.MODIFIED,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20619',
      modType: ModificationType.MODIFIED,
      value: '67',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.RELATION_CHANGE,
      name: changeTypeEnum.RELATION_CHANGE,
      notRelationChange: false,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '333',
      idIntValue: 333,
    },
    artId: '201289',
    itemId: '5143',
    itemTypeId: {
      id: '2455059983007225780',
      name: 'Interface Message SubMessage Content',
      order: 'USER_DEFINED',
      ordered: true,
      multiplicity: 'MANY_TO_MANY',
      idString: '2455059983007225780',
      idIntValue: 225187764,
    },
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20607',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20607',
      modType: ModificationType.DELETED,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20607',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20607',
      modType: ModificationType.DELETED,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '201302',
    deleted: true,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201297',
    itemId: '10328',
    itemTypeId: '1152921504606847089',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20597',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="AAkKSN_MmEVt8yIw4sQA,ABIJ5OzfJC_6z3a8cjQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20631',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="AAkKSN_MmEVt8yIw4sQA,ABIJ5OzfJC_6z3a8cjQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20597',
      modType: ModificationType.MODIFIED,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20631',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="AAkKSN_MmEVt8yIw4sQA,ABIJ5OzfJC_6z3a8cjQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.RELATION_CHANGE,
      name: changeTypeEnum.RELATION_CHANGE,
      notRelationChange: false,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '333',
      idIntValue: 333,
    },
    artId: '201282',
    itemId: '5144',
    itemTypeId: {
      id: '6039606571486514298',
      name: 'Interface Connection Content',
      order: 'LEXICOGRAPHICAL_ASC',
      ordered: true,
      multiplicity: 'MANY_TO_MANY',
      idString: '6039606571486514298',
      idIntValue: 1955695738,
    },
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20616',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20616',
      modType: ModificationType.DELETED,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20616',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20616',
      modType: ModificationType.DELETED,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '201303',
    deleted: true,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.RELATION_CHANGE,
      name: changeTypeEnum.RELATION_CHANGE,
      notRelationChange: false,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '333',
      idIntValue: 333,
    },
    artId: '201282',
    itemId: '5145',
    itemTypeId: {
      id: '6039606571486514298',
      name: 'Interface Connection Content',
      order: 'LEXICOGRAPHICAL_ASC',
      ordered: true,
      multiplicity: 'MANY_TO_MANY',
      idString: '6039606571486514298',
      idIntValue: 1955695738,
    },
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20629',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20629',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '201304',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      notRelationChange: true,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '111',
      idIntValue: 111,
    },
    artId: '201305',
    itemId: '201305',
    itemTypeId: '126164394421696908',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20630',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20630',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.RELATION_CHANGE,
      name: changeTypeEnum.RELATION_CHANGE,
      notRelationChange: false,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '333',
      idIntValue: 333,
    },
    artId: '201297',
    itemId: '5146',
    itemTypeId: {
      id: '2455059983007225780',
      name: 'Interface Message SubMessage Content',
      order: 'USER_DEFINED',
      ordered: true,
      multiplicity: 'MANY_TO_MANY',
      idString: '2455059983007225780',
      idIntValue: 225187764,
    },
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20635',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20635',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '201305',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      notRelationChange: true,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '111',
      idIntValue: 111,
    },
    artId: '201304',
    itemId: '201304',
    itemTypeId: '2455059983007225775',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20621',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20621',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.RELATION_CHANGE,
      name: changeTypeEnum.RELATION_CHANGE,
      notRelationChange: false,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '333',
      idIntValue: 333,
    },
    artId: '201289',
    itemId: '5147',
    itemTypeId: {
      id: '2455059983007225780',
      name: 'Interface Message SubMessage Content',
      order: 'USER_DEFINED',
      ordered: true,
      multiplicity: 'MANY_TO_MANY',
      idString: '2455059983007225780',
      idIntValue: 225187764,
    },
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20637',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20637',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '201305',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201302',
    itemId: '10339',
    itemTypeId: '1152921504606847088',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20603',
      modType: ModificationType.NEW,
      value: 'test submessage 6',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20603',
      modType: ModificationType.ARTIFACT_DELETED,
      value: 'test submessage 6',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20603',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20603',
      modType: ModificationType.ARTIFACT_DELETED,
      value: 'test submessage 6',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: true,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201302',
    itemId: '10340',
    itemTypeId: '2455059983007225769',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20605',
      modType: ModificationType.NEW,
      value: '762',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20605',
      modType: ModificationType.ARTIFACT_DELETED,
      value: '762',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20605',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20605',
      modType: ModificationType.ARTIFACT_DELETED,
      value: '762',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: true,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201302',
    itemId: '10341',
    itemTypeId: '1152921504606847090',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20604',
      modType: ModificationType.NEW,
      value: 'uiop',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20604',
      modType: ModificationType.ARTIFACT_DELETED,
      value: 'uiop',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20604',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20604',
      modType: ModificationType.ARTIFACT_DELETED,
      value: 'uiop',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: true,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201304',
    itemId: '10350',
    itemTypeId: '2455059983007225754',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20622',
      modType: ModificationType.NEW,
      value: 'true',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20622',
      modType: ModificationType.NEW,
      value: 'true',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201304',
    itemId: '10351',
    itemTypeId: '1152921504606847088',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20623',
      modType: ModificationType.NEW,
      value: 'test message 7',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20623',
      modType: ModificationType.NEW,
      value: 'test message 7',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201304',
    itemId: '10352',
    itemTypeId: '3899709087455064789',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20626',
      modType: ModificationType.NEW,
      value: 'Periodic',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20626',
      modType: ModificationType.NEW,
      value: 'Periodic',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201304',
    itemId: '10353',
    itemTypeId: '2455059983007225770',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20627',
      modType: ModificationType.NEW,
      value: 'Operational',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20627',
      modType: ModificationType.NEW,
      value: 'Operational',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201304',
    itemId: '10354',
    itemTypeId: '2455059983007225768',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20628',
      modType: ModificationType.NEW,
      value: '741',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20628',
      modType: ModificationType.NEW,
      value: '741',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201304',
    itemId: '10355',
    itemTypeId: '1152921504606847090',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20625',
      modType: ModificationType.NEW,
      value: 'dafda',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20625',
      modType: ModificationType.NEW,
      value: 'dafda',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201304',
    itemId: '10356',
    itemTypeId: '2455059983007225763',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20624',
      modType: ModificationType.NEW,
      value: '20',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20624',
      modType: ModificationType.NEW,
      value: '20',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201305',
    itemId: '10357',
    itemTypeId: '1152921504606847088',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20632',
      modType: ModificationType.NEW,
      value: 'test submessage 8',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20632',
      modType: ModificationType.NEW,
      value: 'test submessage 8',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201305',
    itemId: '10358',
    itemTypeId: '2455059983007225769',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20634',
      modType: ModificationType.NEW,
      value: '85',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20634',
      modType: ModificationType.NEW,
      value: '85',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      notAttributeChange: false,
      typeId: 2834799904,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201305',
    itemId: '10359',
    itemTypeId: '1152921504606847090',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20633',
      modType: ModificationType.NEW,
      value: 'dfd',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20633',
      modType: ModificationType.NEW,
      value: 'dfd',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      notRelationChange: true,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '111',
      idIntValue: 111,
    },
    artId: '201297',
    itemId: '201297',
    itemTypeId: '2455059983007225775',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20597',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="AAkKSN_MmEVt8yIw4sQA,ABIJ5OzfJC_6z3a8cjQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20631',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="AAkKSN_MmEVt8yIw4sQA,ABIJ5OzfJC_6z3a8cjQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20597',
      modType: ModificationType.MODIFIED,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20631',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="AAkKSN_MmEVt8yIw4sQA,ABIJ5OzfJC_6z3a8cjQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: true,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      notRelationChange: true,
      notAttributeChange: true,
      typeId: 2834799904,
      idString: '111',
      idIntValue: 111,
    },
    artId: '201289',
    itemId: '201289',
    itemTypeId: '2455059983007225775',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20606',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="ABCkGXcC9BtOVW8ceggA,AAkKSN_MmEVt8yIw4sQA,ABEYW415xCGFe1Wi1NwA,ABIN5ZrPVFEVTDcmr9gA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20636',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="ABCkGXcC9BtOVW8ceggA,AAkKSN_MmEVt8yIw4sQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20606',
      modType: ModificationType.MODIFIED,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20636',
      modType: ModificationType.MODIFIED,
      value:
        '<OrderList><Order relType="Interface Message SubMessage Content" side="SIDE_B" orderType="AAT0xogoMjMBhARkBZQA" list="ABCkGXcC9BtOVW8ceggA,AAkKSN_MmEVt8yIw4sQA,ABI4Dl_6DDaQ4SDceEQA"/></OrderList>',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: true,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ARTIFACT_CHANGE,
      name: changeTypeEnum.ARTIFACT_CHANGE,
      notRelationChange: true,
      typeId: 2834799904,
      notAttributeChange: true,
      idString: '111',
      idIntValue: 111,
    },
    artId: '201279',
    itemId: '201279',
    itemTypeId: '6039606571486514295',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20484',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20687',
      modType: ModificationType.MODIFIED,
      value: 'changed',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20484',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20687',
      modType: ModificationType.MODIFIED,
      value: 'changed',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: true,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      typeId: 2834799904,
      notAttributeChange: false,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201281',
    itemId: '10249',
    itemTypeId: '1152921504606847090',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20494',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '1015',
        branchId: '1014568291390890988',
      },
      gammaId: '20688',
      modType: ModificationType.MODIFIED,
      value: 'changed',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '977',
        branchId: '8',
      },
      gammaId: '20494',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20688',
      modType: ModificationType.MODIFIED,
      value: 'changed',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
  {
    ignoreType: ignoreType.NONE,
    changeType: {
      id: changeTypeNumber.ATTRIBUTE_CHANGE,
      name: changeTypeEnum.ATTRIBUTE_CHANGE,
      notRelationChange: true,
      typeId: 2834799904,
      notAttributeChange: false,
      idString: '222',
      idIntValue: 222,
    },
    artId: '201279',
    itemId: '10241',
    itemTypeId: '1152921504606847090',
    baselineVersion: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20484',
      modType: ModificationType.NEW,
      value: '',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    firstNonCurrentChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: null,
      modType: ModificationType.NONE,
      value: null,
      uri: '',
      valid: false,
      applicabilityToken: null,
    },
    currentVersion: {
      transactionToken: {
        id: '1014',
        branchId: '1014568291390890988',
      },
      gammaId: '20687',
      modType: ModificationType.MODIFIED,
      value: 'changed',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    destinationVersion: {
      transactionToken: {
        id: '977',
        branchId: '8',
      },
      gammaId: '20484',
      modType: ModificationType.NEW,
      value: null,
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    netChange: {
      transactionToken: {
        id: '-1',
        branchId: '-1',
      },
      gammaId: '20687',
      modType: ModificationType.MODIFIED,
      value: 'changed',
      uri: '',
      valid: true,
      applicabilityToken: {
        id: '1',
        name: 'Base',
      },
    },
    synthetic: false,
    artIdB: '-1',
    deleted: false,
    applicabilityCopy: false,
  },
];
