/*
 * generated by Xtext
 */
package org.eclipse.osee.ats.dsl.ui;

import com.google.inject.Injector;
import org.eclipse.osee.ats.dsl.ui.internal.AtsDslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AtsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AtsDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AtsDslActivator.getInstance().getInjector(AtsDslActivator.ORG_ECLIPSE_OSEE_ATS_DSL_ATSDSL);
	}
	
}
