java_test(
    name = "AuthAdminTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.authentication.admin", "@maven//:org_mockito_mockito_core","//org.eclipse.osee.framework.core.packages"]
) 
