-- DROP ROLE osee;
CREATE ROLE osee LOGIN PASSWORD 'osee' SUPERUSER INHERIT CREATEDB NOCREATEROLE;

--DROP DATABASE "OSEE";
CREATE DATABASE "OSEE" WITH OWNER = osee ENCODING = 'UTF8' TABLESPACE = pg_default;

\connect OSEE

--DROP SCHEMA osee;
CREATE SCHEMA AUTHORIZATION osee;