java_test(
    name = "AtsHelpUiTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.ats.ide.help.ui", "//org.eclipse.osee.framework.core.packages",
            "@ext_jars//:eclipse_equinox_common", "@ext_jars//:eclipse_osgi_services"]
)
