java_test(
    name = "AtsHelpUiTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.ats.ide.help.ui:ats_ide_help_ui", "//framework_core_packages",
            "@ext_jars//:eclipse_equinox_common", "@ext_jars//:eclipse_osgi_services"]
)
