java_test(
    name = "AtsHelpUiTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.ats.ide.help.ui", "//org.eclipse.osee.framework.core.packages",
    		   "@eclipse_equinox_common//jar", "@eclipse_osgi//jar"
           ]
)
