/*********************************************************************
 * Copyright (c) 2022 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/

import { ciNavigationStructure } from '@osee/ci-dashboard/navigation';
import { navigationElement } from '@osee/shared/types';
import { UserRoles } from '@osee/shared/types/auth';

// Adding element(s) requires:
// - Defining the element(s) in this file

// if isDropdown, it has children
// if !isDropdown, it has no children

export const navigationStructure: navigationElement[] = [
	// Level-1
	{
		label: 'Product Line Engineering',
		cypressLabel: 'ple',
		pageTitle: 'OSEE - Product Line Engineering',
		isDropdown: true,
		isDropdownOpen: false,
		requiredRoles: [],
		routerLink: '/ple',
		icon: '',
		description: '',
		children: [
			// Level-2
			{
				label: 'Product Line Engineering - Home',
				cypressLabel: 'ple-home',
				pageTitle: 'OSEE - Product Line Engineering',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/ple',
				icon: '',
				description: '',
				children: [],
			},
			{
				label: 'Product Line Engineering - Help',
				cypressLabel: 'ple-help',
				pageTitle: 'OSEE - Product Line Engineering Help',
				isDropdown: true,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/ple/help',
				icon: '',
				description: '',
				children: [
					{
						label: 'BAT Tool Help',
						cypressLabel: 'bat',
						pageTitle: 'BAT Tool Help',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/help/bat',
						icon: 'sports_cricket',
						description: '',
						children: [],
					},
				],
			},
			{
				label: 'Artifact Explorer',
				cypressLabel: 'artifactExplorer',
				pageTitle: 'Artifact Explorer',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/ple/artifact/explorer',
				icon: '',
				description: '',
				children: [],
			},
			{
				label: 'AsciiDoc Editor',
				cypressLabel: 'adocEditor',
				pageTitle: 'AsciiDoc Editor',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/ple/asciidoc',
				icon: '',
				description: '',
				children: [],
			},
			{
				label: 'Messaging Configuration',
				cypressLabel: 'messaging',
				pageTitle: 'OSEE - MIM',
				isDropdown: true,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/ple/messaging',
				icon: '',
				description: '',
				children: [
					// Level-3
					{
						label: 'Message Configuration - Home',
						cypressLabel: 'messaging',
						pageTitle: 'OSEE - MIM',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging',
						icon: 'home',
						description: '',
						children: [],
					},
					{
						label: 'Connection View',
						cypressLabel: 'connection-nav-button',
						pageTitle: 'OSEE - MIM - Connection View',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging/connections',
						icon: 'device_hub',
						description: '',
						children: [],
					},
					{
						label: 'Type View',
						cypressLabel: 'types-nav-button',
						pageTitle: 'OSEE - MIM - Type View',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging/types',
						icon: 'view_module',
						description: '',
						children: [],
					},
					{
						label: 'Structure Names',
						cypressLabel: 'structure-nav-button',
						pageTitle: 'OSEE - MIM - Structure Names',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging/structureNames',
						icon: 'line_style',
						description: '',
						children: [],
					},
					{
						label: 'Find Elements by Type',
						cypressLabel: 'typesearch-nav-button',
						pageTitle: 'OSEE - MIM - Element TypeSearch',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging/typeSearch',
						icon: 'search',
						description: '',
						children: [],
					},
					{
						label: 'Reports',
						cypressLabel: 'mimreport-nav-button',
						pageTitle: 'OSEE - MIM - Reports',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging/reports',
						icon: 'insert_drive_file',
						description: '',
						children: [],
					},
					{
						label: 'Cross-Reference Data Manager',
						cypressLabel: 'cross-reference-nav-button',
						pageTitle: 'OSEE - MIM - Cross-Reference Data Manager',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging/crossreference',
						icon: 'compare_arrows',
						description: '',
						children: [],
					},
					{
						label: 'Help',
						cypressLabel: 'help-nav-button',
						pageTitle: 'OSEE - MIM - Help',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [],
						routerLink: '/ple/messaging/help',
						icon: 'help_outline',
						description: '',
						children: [],
					},
					{
						label: 'Transport Type Manager',
						cypressLabel: 'transports-nav-button',
						pageTitle: 'OSEE - MIM - Transport Type Manager',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [UserRoles.OSEE_ADMIN],
						routerLink: '/ple/messaging/transports',
						icon: 'timeline',
						description: '',
						children: [],
					},
					{
						label: 'Import',
						cypressLabel: 'mimimport-nav-button',
						pageTitle: 'OSEE - MIM - Import',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [UserRoles.OSEE_ADMIN],
						routerLink: '/ple/messaging/import',
						icon: 'cloud_upload',
						description: '',
						children: [],
					},
					{
						label: 'Enumeration List Configuration',
						cypressLabel: 'enum-list-config-nav-button',
						pageTitle: 'OSEE - MIM - Enum List Configuration',
						isDropdown: false,
						isDropdownOpen: false,
						requiredRoles: [UserRoles.OSEE_ADMIN],
						routerLink: '/ple/messaging/lists',
						icon: 'view_list',
						description: '',
						children: [],
					},
				],
			},
			{
				label: 'Product Line Configuration',
				cypressLabel: 'plconfig',
				pageTitle: 'OSEE - Product Line Configuration',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/ple/plconfig',
				icon: '',
				description: '',
				children: [],
			},
		],
	},
	{
		label: 'Server Health',
		cypressLabel: '',
		pageTitle: '',
		isDropdown: true,
		isDropdownOpen: false,
		requiredRoles: [UserRoles.OSEE_ADMIN],
		routerLink: '/server/health',
		icon: '',
		description: '',
		children: [
			{
				label: 'Server Health Dashboard',
				cypressLabel: '',
				pageTitle: '',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/server/health',
				icon: 'healing',
				description:
					'Provides OSEE Server Health Information and Links',
				children: [],
			},
			{
				label: 'Status',
				cypressLabel: '',
				pageTitle: '',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/server/health/status',
				icon: 'router',
				description: 'OSEE Server Status',
				children: [],
			},
			{
				label: 'Balancers',
				cypressLabel: '',
				pageTitle: '',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/server/health/balancers',
				icon: 'device_hub',
				description: 'OSEE Server Load Balancer Status',
				children: [],
			},

			{
				label: 'Usage',
				cypressLabel: '',
				pageTitle: '',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/server/health/usage',
				icon: 'people',
				description: 'OSEE Server Usage Report In The Last 1 Month',
				children: [],
			},
			{
				label: 'Database',
				cypressLabel: '',
				pageTitle: '',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/server/health/database',
				icon: 'table_chart',
				description: 'OSEE Database Information',
				children: [],
			},
			{
				label: 'Http Headers',
				cypressLabel: '',
				pageTitle: '',
				isDropdown: false,
				isDropdownOpen: false,
				requiredRoles: [],
				routerLink: '/server/health/headers',
				icon: 'rss_feed',
				description:
					'OSEE Server and Web Client Communication Protocols',
				children: [],
			},
		],
	},
	...ciNavigationStructure,
];
