/*********************************************************************
 * Copyright (c) 2021 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import { apiURL } from '@osee/environments';
import { type element } from '../../types/element';
import {
	ATTRIBUTETYPEIDENUM,
	ARTIFACTTYPEIDENUM,
} from '@osee/shared/types/constants';
import {
	TransactionBuilderService,
	TransactionService,
} from '@osee/shared/transactions';
import type { relation, transaction } from '@osee/shared/types';
import { ArrayIndexOrder } from '@osee/messaging/shared/types';
@Injectable({
	providedIn: 'root',
})
export class ElementService {
	constructor(
		private http: HttpClient,
		private builder: TransactionBuilderService,
		private transactionService: TransactionService
	) {}

	getElement(
		branchId: string,
		messageId: string,
		subMessageId: string,
		structureId: string,
		elementId: string,
		connectionId: string
	) {
		return this.http.get<element>(
			apiURL +
				'/mim/branch/' +
				branchId +
				'/connections/' +
				connectionId +
				'/messages/' +
				messageId +
				'/submessages/' +
				subMessageId +
				'/structures/' +
				structureId +
				'/elements/' +
				elementId
		);
	}
	getFilteredElements(branchId: string, filter: string) {
		return this.http.get<element[]>(
			apiURL + `/mim/branch/${branchId}/elements/filter/${filter}`
		);
	}

	getPaginatedFilteredElements(
		branchId: string,
		filter: string,
		count: number,
		pageNum: string
	) {
		return this.http.get<element[]>(
			apiURL + `/mim/branch/${branchId}/elements/filter/${filter}`,
			{
				params: {
					count: count,
					pageNum: pageNum,
					orderByAttributeType: ATTRIBUTETYPEIDENUM.NAME,
				},
			}
		);
	}

	getPaginatedElementsByName(
		branchId: string,
		name: string,
		count: number,
		pageNum: string | number
	) {
		return this.http.get<element[]>(
			apiURL + '/mim/branch/' + branchId + '/elements/name',
			{
				params: {
					name: name,
					count: count,
					pageNum: pageNum,
					orderByAttributeType: ATTRIBUTETYPEIDENUM.NAME,
				},
			}
		);
	}

	getElementsByNameCount(branchId: string, name: string) {
		return this.http.get<number>(
			apiURL + '/mim/branch/' + branchId + '/elements/name/count',
			{
				params: {
					name: name,
				},
			}
		);
	}

	createStructureRelation(
		structureId?: string,
		elementId?: string,
		afterArtifact?: string
	) {
		let relation: relation = {
			typeName: 'Interface Structure Content',
			sideA: structureId,
			sideB: elementId,
			afterArtifact: afterArtifact || 'end',
		};
		return of(relation);
	}

	createPlatformTypeRelation(platformTypeId: string, elementId?: string) {
		let relation: relation = {
			typeName: 'Interface Element Platform Type',
			sideB: platformTypeId,
			sideA: elementId,
		};
		return of(relation);
	}

	createElementArrayRelation(
		arrayHeaderId: string,
		arrayElementId?: string,
		afterArtifactId?: string
	) {
		let relation: relation = {
			typeName: 'Interface Element Array Element',
			sideA: arrayHeaderId,
			sideB: arrayElementId,
			afterArtifact: afterArtifactId || 'end',
		};
		return of(relation);
	}

	createElement(
		body: Partial<element>,
		branchId: string,
		relations: relation[],
		transaction?: transaction,
		key?: string
	) {
		// Delete unused relations and attributes
		delete body.platformType;
		delete body.arrayElements;
		delete body.units;
		delete body.autogenerated;
		return of(
			this.builder.createArtifact(
				body,
				ARTIFACTTYPEIDENUM.ELEMENT,
				relations,
				transaction,
				branchId,
				'Create Element',
				key
			)
		);
	}
	changeElement(
		body: Partial<element>,
		branchId: string,
		transaction?: transaction
	) {
		return of(
			this.builder.modifyArtifact(
				body,
				transaction,
				branchId,
				'Change Element'
			)
		);
	}
	addRelation(
		branchId: string,
		relation: relation,
		transaction?: transaction
	) {
		return of(
			this.builder.addRelation(
				relation.typeName,
				undefined,
				relation.sideA as string,
				relation.sideB as string,
				relation.afterArtifact,
				undefined,
				transaction,
				branchId,
				'Relating Element'
			)
		);
	}

	deleteRelation(
		branchId: string,
		relation: relation,
		transaction?: transaction
	) {
		return of(
			this.builder.deleteRelation(
				relation.typeName,
				undefined,
				relation.sideA as string,
				relation.sideB as string,
				undefined,
				transaction,
				branchId,
				'Relating Element'
			)
		);
	}

	deleteElement(branchId: string, elementId: string) {
		return of(
			this.builder.deleteArtifact(
				elementId,
				undefined,
				branchId,
				'Deleting element'
			)
		);
	}
	performMutation(body: transaction) {
		return this.transactionService.performMutation(body);
	}

	getArrayIndexOrders() {
		return this.http.get<ArrayIndexOrder[]>(
			apiURL + '/mim/enums/arrayIndexOrders'
		);
	}
}
