#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum LexerToken<I> {
    #[default]
    Nothing,
    Illegal,
    Identity,
    Text(I, (usize, u32), (usize, u32)),
    // Eof, This path should be illegal now
    StartCommentSingleLine,
    StartCommentMultiLine,
    SingleLineCommentCharacter,
    EndCommentSingleLine,
    EndCommentMultiLine,
    MultilineCommentCharacter,
    Feature((usize, u32), (usize, u32)),
    FeatureNot((usize, u32), (usize, u32)),
    FeatureSwitch((usize, u32), (usize, u32)),
    FeatureCase((usize, u32), (usize, u32)),
    FeatureElse((usize, u32), (usize, u32)),
    FeatureElseIf((usize, u32), (usize, u32)),
    EndFeature((usize, u32), (usize, u32)),
    Configuration((usize, u32), (usize, u32)),
    ConfigurationNot((usize, u32), (usize, u32)),
    ConfigurationSwitch((usize, u32), (usize, u32)),
    ConfigurationCase((usize, u32), (usize, u32)),
    ConfigurationElse((usize, u32), (usize, u32)),
    ConfigurationElseIf((usize, u32), (usize, u32)),
    EndConfiguration((usize, u32), (usize, u32)),
    ConfigurationGroup((usize, u32), (usize, u32)),
    ConfigurationGroupNot((usize, u32), (usize, u32)),
    ConfigurationGroupSwitch((usize, u32), (usize, u32)),
    ConfigurationGroupCase((usize, u32), (usize, u32)),
    ConfigurationGroupElse((usize, u32), (usize, u32)),
    ConfigurationGroupElseIf((usize, u32), (usize, u32)),
    EndConfigurationGroup((usize, u32), (usize, u32)),
    Substitution((usize, u32), (usize, u32)),
    Space((usize, u32), (usize, u32)),
    CarriageReturn,
    UnixNewLine,
    Tab((usize, u32), (usize, u32)),
    //the following should only be tokenized following one of the Feature|Configuration|ConfigurationGroup Base|Not|Switch|Case
    StartBrace((usize, u32), (usize, u32)),
    EndBrace((usize, u32), (usize, u32)),
    // the following should only be tokenized following a StartBrace and preceding an EndBrace
    StartParen((usize, u32), (usize, u32)),
    EndParen((usize, u32), (usize, u32)),
    Not((usize, u32), (usize, u32)),
    And((usize, u32), (usize, u32)),
    Or((usize, u32), (usize, u32)),
    Tag(I, (usize, u32), (usize, u32)),
}
