java_test(
    name = "CoreServerTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//:framework_core_server", "//framework_core_packages",
            "//:jdbc", "@maven//:org_mockito_mockito_core",]
)