java_test(
    name = "CoreServerTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.framework.core.server", "//org.eclipse.osee.framework.core.packages",
            "//org.eclipse.osee.jdbc", "@maven//:org_mockito_mockito_core",]
)
