java_test(
    name = "JaxRsServerTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//:jaxrs", "//:jaxrs_server", "//org.eclipse.osee.framework.jdk.core:framework_jdk_core",
            "@maven//:org_mockito_mockito_core"]
)