java_test(
    name = "JaxRsServerTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.jaxrs", "//org.eclipse.osee.jaxrs.server", "//org.eclipse.osee.framework.jdk.core",
            "@maven//:org_mockito_mockito_core"]
)
