<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oseeTypes"
    nsURI="http://www.eclipse.org/osee/framework/OseeTypes" nsPrefix="oseeTypes">
  <eClassifiers xsi:type="ecore:EClass" name="OseeTypeModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactTypes" upperBound="-1"
        eType="#//ArtifactType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationTypes" upperBound="-1"
        eType="#//RelationType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeTypes" upperBound="-1"
        eType="#//AttributeType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumTypes" upperBound="-1"
        eType="#//OseeEnumType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumOverrides" upperBound="-1"
        eType="#//OseeEnumOverride" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OseeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OseeType" eSuperTypes="#//OseeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeGuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superArtifactTypes" unique="false"
        upperBound="-1" eType="#//ArtifactType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validAttributeTypes" upperBound="-1"
        eType="#//AttributeTypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validAttributeType" eType="#//AttributeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchGuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseAttributeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="override" eType="#//AttributeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataProvider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taggerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumType" eType="#//OseeEnumType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OseeEnumType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumEntries" upperBound="-1"
        eType="#//OseeEnumEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OseeEnumEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OseeEnumOverride" eSuperTypes="#//OseeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="overridenEnumType" eType="#//OseeEnumType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overrideOptions" upperBound="-1"
        eType="#//OverrideOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OverrideOption"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddEnum" eSuperTypes="#//OverrideOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumEntry" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveEnum" eSuperTypes="#//OverrideOption">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumEntry" eType="#//OseeEnumEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sideAName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sideAArtifactType" eType="#//ArtifactType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sideBName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sideBArtifactType" eType="#//ArtifactType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultOrderType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//RelationMultiplicityEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationMultiplicityEnum">
    <eLiterals name="ONE_TO_ONE" literal="ONE_TO_ONE"/>
    <eLiterals name="ONE_TO_MANY" value="1" literal="ONE_TO_MANY"/>
    <eLiterals name="MANY_TO_ONE" value="2" literal="MANY_TO_ONE"/>
    <eLiterals name="MANY_TO_MANY" value="3" literal="MANY_TO_MANY"/>
  </eClassifiers>
</ecore:EPackage>
