<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oseeTypes"
    nsURI="http://www.eclipse.org/osee/framework/OseeTypes" nsPrefix="oseeTypes">
  <eClassifiers xsi:type="ecore:EClass" name="OseeTypeModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//OseeType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OseeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superArtifactType" eType="#//ArtifactType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validAttributeTypes" upperBound="-1"
        eType="#//AttributeTypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeTypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validAttributeType" eType="#//AttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseAttributeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataProvider" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taggerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumType" eType="#//OseeEnumType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OseeEnumType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumEntries" upperBound="-1"
        eType="#//OseeEnumEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OseeEnumEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordinal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationMultiplicityEnum">
    <eLiterals name="ONE_TO_MANY" literal="ONE_TO_MANY"/>
    <eLiterals name="MANY_TO_MANY" value="1" literal="MANY_TO_MANY"/>
    <eLiterals name="MANY_TO_ONE" value="2" literal="MANY_TO_ONE"/>
    <eLiterals name="ONE_TO_ONE" value="3" literal="ONE_TO_ONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationType" eSuperTypes="#//OseeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sideAName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sideAArtifactType" eType="#//ArtifactType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sideBName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sideBArtifactType" eType="#//ArtifactType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultOrderType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//RelationMultiplicityEnum"/>
  </eClassifiers>
</ecore:EPackage>
