java_test(
    name = "Disposition_JUnit_TestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.disposition.rest:disposition_rest",
            "//org.eclipse.osee.disposition.rest.model:disposition_rest_model",
            "//framework_core_packages","//:orcs", "@maven//:org_mockito_mockito_core",
            "@maven//:javax_ws_rs_javax_ws_rs_api","@maven//:com_fasterxml_jackson_core_jackson_databind"]
)
