/*
 * generated by Xtext
 */
package org.eclipse.osee.framework.core.dsl.ui;

import com.google.inject.Injector;
import org.eclipse.osee.framework.core.dsl.ui.internal.OseeDslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OseeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OseeDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OseeDslActivator.getInstance().getInjector(OseeDslActivator.ORG_ECLIPSE_OSEE_FRAMEWORK_CORE_DSL_OSEEDSL);
	}
	
}
