java_library(
    name = "orcs_packages",
    exports = [
               "//org.eclipse.osee.orcs",
               "//org.eclipse.osee.orcs.core",
               "//org.eclipse.osee.orcs.db",
               "//org.eclipse.osee.orcs.rest",
               "//org.eclipse.osee.orcs.rest.model",
                ],
    visibility = ["//visibility:public"]
)
