java_library(
    name = "orcs_packages",
    exports = [
               "//org.eclipse.osee.orcs:orcs",
               "//org.eclipse.osee.orcs.core:orcs_core",
               "//org.eclipse.osee.orcs.db:orcs_db",
               "//org.eclipse.osee.orcs.rest:orcs_rest",
               "//org.eclipse.osee.orcs.rest.model:orcs_rest_model",
                ],
    visibility = ["//visibility:public"]
)