java_test(
     name = "DevHelpUiTestSuite",
     resources =["//org.eclipse.osee.framework.dev.help.ui:web_files"],
     srcs = glob(["**/*.java"]),
     deps = ["@eclipse_core_runtime//jar","//org.eclipse.osee.framework.jdk.core",
     "@eclipse_osgi//jar","@eclipse_equinox_common//jar","//org.eclipse.osee.framework.core",]
)
