/*********************************************************************
 * Copyright (c) 2021 Boeing
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Boeing - initial API and implementation
 **********************************************************************/
import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { of } from 'rxjs';
import { apiURL } from '@osee/environments';
import type { element } from '@osee/messaging/shared/types';
import { ARTIFACTTYPEIDENUM } from '@osee/shared/types/constants';
import { ATTRIBUTETYPEIDENUM } from '@osee/attributes/constants';
import { TransactionBuilderService } from '@osee/shared/transactions-legacy';
import type {
	legacyRelation,
	legacyTransaction,
	transaction,
} from '@osee/transactions/types';
import { ArrayIndexOrder } from '@osee/messaging/shared/types';
import { TransactionService } from '@osee/transactions/services';
import { createArtifact } from '@osee/transactions/functions';
@Injectable({
	providedIn: 'root',
})
export class ElementService {
	private http = inject(HttpClient);
	private builder = inject(TransactionBuilderService);

	private transactionService = inject(TransactionService);

	getElement(
		branchId: string,
		messageId: string,
		subMessageId: string,
		structureId: string,
		elementId: string,
		connectionId: string
	) {
		return this.http.get<element>(
			apiURL +
				'/mim/branch/' +
				branchId +
				'/connections/' +
				connectionId +
				'/messages/' +
				messageId +
				'/submessages/' +
				subMessageId +
				'/structures/' +
				structureId +
				'/elements/' +
				elementId
		);
	}
	getFilteredElements(branchId: string, filter: string) {
		return this.http.get<element[]>(
			apiURL + `/mim/branch/${branchId}/elements/filter/${filter}`
		);
	}

	getPaginatedFilteredElements(
		branchId: string,
		filter: string,
		count: number,
		pageNum: string
	) {
		return this.http.get<element[]>(
			apiURL + `/mim/branch/${branchId}/elements/filter/${filter}`,
			{
				params: {
					count: count,
					pageNum: pageNum,
					orderByAttributeType: ATTRIBUTETYPEIDENUM.NAME,
				},
			}
		);
	}

	getPaginatedElementsByName(
		branchId: string,
		name: string,
		count: number,
		pageNum: string | number
	) {
		return this.http.get<element[]>(
			apiURL + '/mim/branch/' + branchId + '/elements/name',
			{
				params: {
					name: name,
					count: count,
					pageNum: pageNum,
					orderByAttributeType: ATTRIBUTETYPEIDENUM.NAME,
				},
			}
		);
	}

	getElementsByNameCount(branchId: string, name: string) {
		return this.http.get<number>(
			apiURL + '/mim/branch/' + branchId + '/elements/name/count',
			{
				params: {
					name: name,
				},
			}
		);
	}

	createStructureRelation(
		structureId?: string,
		elementId?: string,
		afterArtifact?: string
	) {
		const relation: legacyRelation = {
			typeName: 'Interface Structure Content',
			sideA: structureId,
			sideB: elementId,
			afterArtifact: afterArtifact || 'end',
		};
		return of(relation);
	}

	createPlatformTypeRelation(platformTypeId: string, elementId?: string) {
		const relation: legacyRelation = {
			typeName: 'Interface Element Platform Type',
			sideB: platformTypeId,
			sideA: elementId,
		};
		return of(relation);
	}

	createElementArrayRelation(
		arrayHeaderId: string,
		arrayElementId?: string,
		afterArtifactId?: string
	) {
		const relation: legacyRelation = {
			typeName: 'Interface Element Array Element',
			sideA: arrayHeaderId,
			sideB: arrayElementId,
			afterArtifact: afterArtifactId || 'end',
		};
		return of(relation);
	}

	addNewElementToTransaction(
		body: element,
		tx: Required<transaction>,
		key?: string
	) {
		const {
			id,
			gammaId,
			autogenerated,
			elementSizeInBits,
			elementSizeInBytes,
			beginByte,
			beginWord,
			endByte,
			endWord,
			arrayElements,
			platformType,
			applicability,
			added,
			deleted,
			changes,
			...element
		} = body;
		const attributeKeys = Object.keys(element) as (keyof typeof element)[];
		const attributes = attributeKeys.map((k) => element[k]);
		const results = createArtifact(
			tx,
			ARTIFACTTYPEIDENUM.ELEMENT,
			applicability,
			[],
			key,
			...attributes
		);
		return results.tx;
	}
	addRelation(
		branchId: string,
		relation: legacyRelation,
		transaction?: legacyTransaction
	) {
		return of(
			this.builder.addRelation(
				relation.typeName,
				undefined,
				relation.sideA as string,
				relation.sideB as string,
				relation.afterArtifact,
				undefined,
				transaction,
				branchId,
				'Relating Element'
			)
		);
	}

	deleteRelation(
		branchId: string,
		relation: legacyRelation,
		transaction?: legacyTransaction
	) {
		return of(
			this.builder.deleteRelation(
				relation.typeName,
				undefined,
				relation.sideA as string,
				relation.sideB as string,
				undefined,
				transaction,
				branchId,
				'Relating Element'
			)
		);
	}

	deleteElement(branchId: string, elementId: string) {
		return of(
			this.builder.deleteArtifact(
				elementId,
				undefined,
				branchId,
				'Deleting element'
			)
		);
	}
	performMutation(body: legacyTransaction) {
		return this.transactionService.performMutation(body);
	}

	getArrayIndexOrders() {
		return this.http.get<ArrayIndexOrder[]>(
			apiURL + '/mim/enums/arrayIndexOrders'
		);
	}
}
