name: SpotBugs
description: Runs SpotBugs Static Analysis Tool

branding:
  icon: 'check-square'  
  color: 'blue'

inputs:
  spotbugs-home:
    description: 'SpotBugs file path'
    required: true
  arguments:
    description: 'Command arguments to be sent to SpotBugs'
    required: true
    default: ''
  output:
    description: 'Output file name'
    required: true
  target:
    description: 'Target for SpotBugs to analyze'
    required: true

runs:
  using: composite
  steps:
    - name: Check folder contents
      shell: bash
      run: |
        pwd
        ls -al
        cd ..
        pwd
        ls -al
        cd ..
        pwd
        ls -al
        cd ..
        pwd
        ls -al
        cd root
        pwd
        ls -al

    - name: Set Environment Variables
      shell: bash
      run: |
        echo "_JAVA_OPTIONS=-Xms9G -Xmx9G -XX:MaxMetaspaceSize=4G" >> $GITHUB_ENV
        echo "JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Djava.awt.headless=true" >> $GITHUB_ENV

    - id: spotbug-analysis
      shell: bash
      run: sh ${{ inputs.spotbugs-home }} -textui -output "${{ inputs.output }}" "${{ inputs.arguments }}" "${{ inputs.target }}"

    - name: Upload XML File
      uses: actions/upload-artifact@v4
      with:
        name: /${output}