java_test(
    name = "AuthAdminTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.authorization.admin", 
            "//org.eclipse.osee.framework.core.packages","@maven//:org_mockito_mockito_core",]
)
