java_test(
    name = "AuthAdminTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.authorization.admin:authorization_admin", 
            "//framework_core_packages","@maven//:org_mockito_mockito_core",]
)
