java_test(
    name = "OrcsCoreTestSuite",
    srcs = glob(["**/*.java"]),
    deps = ["//org.eclipse.osee.orcs.core","//org.eclipse.osee.orcs","//org.eclipse.osee.framework.core.packages",
            "@maven//:org_mockito_mockito_core"]
)
