name: PR cleanup

on:
    pull_request:
        types: [closed]

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

permissions:
    contents: read
    packages: write

env:
    ARTIFACT_PATH: "plugins/org.eclipse.osee.server.p2/target/org.eclipse.osee.server.runtime.zip"
    SERVER_PATH: "osee_server"
    SERVER_ZIP: "org.eclipse.osee.server.runtime.zip"
    IMAGE_DIRECTORY: ".github/docker/osee-server/Dockerfile"

jobs:
    cleanup_platform_specific:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: create artifact ref
              id: artifact_ref
              uses: ./.github/actions/artifact-current-ref

            - uses: geekyeggo/delete-artifact@v5
              continue-on-error: true
              with:
                  name: bat-${{matrix.os}}${{steps.artifact_ref.outputs.artifact_current_ref}}
            - uses: geekyeggo/delete-artifact@v5
              continue-on-error: true
              with:
                  name: pat-${{matrix.os}}${{steps.artifact_ref.outputs.artifact_current_ref}}
            - uses: geekyeggo/delete-artifact@v5
              continue-on-error: true
              with:
                  name: java-rust-ffi-${{matrix.os}}${{steps.artifact_ref.outputs.artifact_current_ref}}
    cleanup_docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: create docker ref
              id: docker_ref
              shell: bash
              run: echo "current_ref=$(echo ${{ github.event.pull_request.number }}-merge | tr '/' '-')" >> "$GITHUB_OUTPUT"

            - id: repo-basename
              run: |
                  echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
              shell: bash

            - name: cleanup osee server
              shell: bash
              run: |
                  curl -L \
                   -X DELETE \
                   -H "Accept: application/vnd.github+json" \
                   -H "Authorization: Bearer ${{github.token}}" \
                   -H "X-GitHub-Api-Version: 2022-11-28" \
                   https://api.github.com/orgs/eclipse-osee/packages/container/$(jq -rn --arg x '${{ steps.repo-basename.outputs.value }}/osee-server/${{steps.docker_ref.outputs.current_ref}}' '$x|@uri')
              continue-on-error: true

            - name: cleanup postgres
              shell: bash
              run: |
                  curl -L \
                   -X DELETE \
                   -H "Accept: application/vnd.github+json" \
                   -H "Authorization: Bearer ${{github.token}}" \
                   -H "X-GitHub-Api-Version: 2022-11-28" \
                   https://api.github.com/orgs/eclipse-osee/packages/container/$(jq -rn --arg x '${{ steps.repo-basename.outputs.value }}/osee-postgres/${{steps.docker_ref.outputs.current_ref}}' '$x|@uri')
              continue-on-error: true

            - name: create artifact ref
              id: artifact_ref
              uses: ./.github/actions/artifact-current-ref

            - uses: geekyeggo/delete-artifact@v5
              continue-on-error: true
              with:
                  name: osee-server${{steps.artifact_ref.outputs.artifact_current_ref}}-binaries

            - uses: geekyeggo/delete-artifact@v5
              continue-on-error: true
              with:
                  name: compose-file${{steps.artifact_ref.outputs.artifact_current_ref}}
